module Temporalio
  module FailureConverter
    interface _FailureConverter
      def to_failure: (Exception, Temporalio::PayloadConverter::_PayloadConverter) -> Temporalio::Api::Failure::V1::Failure
      def from_failure: (Temporalio::Api::Failure::V1::Failure, Temporalio::PayloadConverter::_PayloadConverter) -> Exception
    end

    class Base
      include _FailureConverter
    end
  end
end
