module Temporalio
  module Internal
    module Bridge
      interface _ResultQueue[T]
        def push: (T | Exception) -> void
        def pop: -> T
      end

      def self.async_call: [T] { (_ResultQueue[T] queue) -> void } -> T

      # Defined in Rust

      class Error < StandardError
      end
    end
  end
end