module Temporalio
  module Internal
    module Bridge
      def self.assert_fiber_compatibility!: -> void
      def self.fibers_supported: -> bool

      # Defined in Rust

      class Error < StandardError
      end
    end
  end
end