module Temporalio
  module Internal
    module ProtoUtils
      def self.seconds_to_duration: (Float? seconds_float) -> untyped?

      def self.duration_to_seconds: (untyped? duration) -> Float?

      def self.time_to_timestamp: (Time? time) -> untyped?

      def self.timestamp_to_time: (untyped? timestamp) -> Time?

      def self.memo_to_proto: (
        Hash[String, Object?]? hash,
        Converters::DataConverter | Converters::PayloadConverter converter
      ) -> untyped?

      def self.memo_from_proto: (
        untyped? memo,
        Converters::DataConverter | Converters::PayloadConverter converter
      ) -> Hash[String, Object?]?

      def self.headers_to_proto: (
        Hash[String, Object?]? hash,
        Converters::DataConverter | Converters::PayloadConverter converter
      ) -> untyped?

      def self.headers_from_proto: (
        untyped? headers,
        Converters::DataConverter | Converters::PayloadConverter converter
      ) -> Hash[String, Object?]?

      def self.headers_from_proto_map: (
        Hash[String, untyped]? headers,
        Converters::DataConverter | Converters::PayloadConverter converter
      ) -> Hash[String, Object?]?

      def self.string_or: (String? str, ?nil default) -> String?
                        | (String? str, String default) -> String

      def self.enum_to_int: (untyped enum_mod, untyped enum_val, ?zero_means_nil: bool) -> Integer

      def self.convert_from_payload_array: (
        Converters::DataConverter | Converters::PayloadConverter converter,
        Array[untyped] payloads
      ) -> Array[Object?]

      def self.convert_to_payload_array: (
        Converters::DataConverter | Converters::PayloadConverter converter,
        Array[Object?] values
      ) -> Array[untyped]

      class LazyMemo
        def initialize: (
          untyped? raw_memo,
          Converters::DataConverter | Converters::PayloadConverter converter,
        ) -> void

        def get: -> Hash[String, Object?]?
      end

      class LazySearchAttributes
        def initialize: (untyped? raw_search_attributes) -> void

        def get: -> SearchAttributes?
      end
    end
  end
end