module Temporalio
  class Client
    class Options
      attr_reader connection: Connection
      attr_reader namespace: String
      attr_reader data_converter: Converters::DataConverter
      attr_reader plugins: Array[Plugin]
      attr_reader interceptors: Array[Interceptor]
      attr_reader logger: Logger
      attr_reader default_workflow_query_reject_condition: WorkflowQueryRejectCondition::enum?

      def initialize: (
        connection: Connection,
        namespace: String,
        data_converter: Converters::DataConverter,
        plugins: Array[Plugin],
        interceptors: Array[Interceptor],
        logger: Logger,
        default_workflow_query_reject_condition: WorkflowQueryRejectCondition::enum?
      ) -> void

      def to_h: -> Hash[Symbol, untyped]

      def with: (**untyped) -> Options
    end

    class ListWorkflowPage
      attr_reader executions: Array[WorkflowExecution]
      attr_reader next_page_token: String?

      def initialize: (
        executions: Array[WorkflowExecution],
        next_page_token: String?
      ) -> void
    end

    def self.connect: (
      String target_host,
      String namespace,
      ?api_key: String?,
      ?tls: bool | Connection::TLSOptions | nil,
      ?data_converter: Converters::DataConverter,
      ?plugins: Array[Plugin],
      ?interceptors: Array[Interceptor],
      ?logger: Logger,
      ?default_workflow_query_reject_condition: WorkflowQueryRejectCondition::enum?,
      ?rpc_metadata: Hash[String, String],
      ?rpc_retry: Connection::RPCRetryOptions,
      ?identity: String,
      ?keep_alive: Connection::KeepAliveOptions,
      ?http_connect_proxy: Connection::HTTPConnectProxyOptions?,
      ?runtime: Runtime,
      ?lazy_connect: bool
    ) -> Client

    def self._validate_plugins!: (Array[Plugin] plugins) -> void

    attr_reader options: Options

    def initialize: (
      connection: Connection,
      namespace: String,
      ?data_converter: Converters::DataConverter,
      ?plugins: Array[Plugin],
      ?interceptors: Array[Interceptor],
      ?logger: Logger,
      ?default_workflow_query_reject_condition: WorkflowQueryRejectCondition::enum?
    ) -> void

    def connection: -> Connection
    def namespace: -> String
    def data_converter: -> Converters::DataConverter
    def workflow_service: -> Connection::WorkflowService
    def operator_service: -> Connection::OperatorService

    def start_workflow: (
      singleton(Workflow::Definition) | Workflow::Definition::Info | Symbol | String workflow,
      *Object? args,
      id: String,
      task_queue: String,
      ?static_summary: String?,
      ?static_details: String?,
      ?execution_timeout: duration?,
      ?run_timeout: duration?,
      ?task_timeout: duration?,
      ?id_reuse_policy: WorkflowIDReusePolicy::enum,
      ?id_conflict_policy: WorkflowIDConflictPolicy::enum,
      ?retry_policy: RetryPolicy?,
      ?cron_schedule: String?,
      ?memo: Hash[String | Symbol, Object?]?,
      ?search_attributes: SearchAttributes?,
      ?start_delay: duration?,
      ?request_eager_start: bool,
      ?versioning_override: VersioningOverride?,
      ?priority: Priority,
      ?arg_hints: Array[Object]?,
      ?result_hint: Object?,
      ?rpc_options: RPCOptions?
    ) -> WorkflowHandle

    def execute_workflow: (
      singleton(Workflow::Definition) | Workflow::Definition::Info | Symbol | String workflow,
      *Object? args,
      id: String,
      task_queue: String,
      ?static_summary: String?,
      ?static_details: String?,
      ?execution_timeout: duration?,
      ?run_timeout: duration?,
      ?task_timeout: duration?,
      ?id_reuse_policy: WorkflowIDReusePolicy::enum,
      ?id_conflict_policy: WorkflowIDConflictPolicy::enum,
      ?retry_policy: RetryPolicy?,
      ?cron_schedule: String?,
      ?memo: Hash[String | Symbol, Object?]?,
      ?search_attributes: SearchAttributes?,
      ?start_delay: duration?,
      ?request_eager_start: bool,
      ?versioning_override: VersioningOverride?,
      ?priority: Priority,
      ?arg_hints: Array[Object]?,
      ?result_hint: Object?,
      ?rpc_options: RPCOptions?
    ) -> Object?

    def workflow_handle: (
      String workflow_id,
      ?run_id: String?,
      ?first_execution_run_id: String?,
      ?result_hint: Object?
    ) -> WorkflowHandle

    def start_update_with_start_workflow: (
      Workflow::Definition::Update | Symbol | String update,
      *Object? args,
      start_workflow_operation: WithStartWorkflowOperation,
      wait_for_stage: WorkflowUpdateWaitStage::enum,
      ?id: String,
      ?arg_hints: Array[Object]?,
      ?result_hint: Object?,
      ?rpc_options: RPCOptions?
    ) -> WorkflowUpdateHandle

    def execute_update_with_start_workflow: (
      Workflow::Definition::Update | Symbol | String update,
      *Object? args,
      start_workflow_operation: WithStartWorkflowOperation,
      ?id: String,
      ?arg_hints: Array[Object]?,
      ?result_hint: Object?,
      ?rpc_options: RPCOptions?
    ) -> Object?

    def signal_with_start_workflow: (
      Workflow::Definition::Signal | Symbol | String signal,
      *Object? args,
      start_workflow_operation: WithStartWorkflowOperation,
      ?arg_hints: Array[Object]?,
      ?rpc_options: RPCOptions?
    ) -> WorkflowHandle

    def list_workflows: (
      ?String query,
      ?rpc_options: RPCOptions?
    ) -> Enumerator[WorkflowExecution, WorkflowExecution]

    def list_workflow_page: (
      ?String query,
      ?next_page_token: String?,
      ?page_size: Integer?,
      ?rpc_options: RPCOptions?
    ) -> ListWorkflowPage

    def count_workflows: (
      ?String query,
      ?rpc_options: RPCOptions?
    ) -> WorkflowExecutionCount

    def create_schedule: (
      String id,
      Schedule schedule,
      ?trigger_immediately: bool,
      ?backfills: Array[Schedule::Backfill],
      ?memo: Hash[String, Object?]?,
      ?search_attributes: SearchAttributes?,
      ?rpc_options: RPCOptions?
    ) -> ScheduleHandle

    def schedule_handle: (String id) -> ScheduleHandle

    def list_schedules: (
      ?String query,
      ?rpc_options: RPCOptions?
    ) -> Enumerator[Schedule::List::Description, Schedule::List::Description]

    def async_activity_handle: (
      String | ActivityIDReference task_token_or_id_reference
    ) -> AsyncActivityHandle

    class RPCOptions
      attr_accessor metadata: Hash[String, String]?
      attr_accessor timeout: Float?
      attr_accessor cancellation: Cancellation?
      attr_accessor override_retry: bool?

      def initialize: (
        ?metadata: Hash[String, String]?,
        ?timeout: Float?,
        ?cancellation: Cancellation?,
        ?override_retry: bool?
      ) -> void
    end
  end
end
