module Temporalio
  class Priority
    attr_reader priority_key: Integer?

    def initialize: (?priority_key: Integer?) -> void

    def self._from_proto: (untyped) -> Priority

    def self.default: -> Priority

    def _to_proto: -> untyped

    def empty?: -> bool
  end
end
