module Temporalio
  class Runtime
    class TelemetryOptions
      attr_reader logging: LoggingOptions?
      attr_reader metrics: MetricsOptions?

      def initialize: (
        ?logging: LoggingOptions?,
        ?metrics: MetricsOptions?
      ) -> void

      def _to_bridge: -> Internal::Bridge::Runtime::TelemetryOptions
    end

    class LoggingOptions
      attr_reader log_filter: LoggingFilterOptions | String

      def initialize: (
        ?log_filter: LoggingFilterOptions | String
      ) -> void

      def _to_bridge: -> Internal::Bridge::Runtime::LoggingOptions
    end

    type logging_filter_level = 'TRACE' | 'DEBUG' | 'INFO' | 'WARN' | 'ERROR'

    class LoggingFilterOptions
      attr_reader core_level: logging_filter_level
      attr_reader other_level: logging_filter_level

      def initialize: (
        ?core_level: logging_filter_level,
        ?other_level: logging_filter_level
      ) -> void

      def _to_bridge: -> String
    end

    class MetricsOptions
      attr_reader opentelemetry: OpenTelemetryMetricsOptions?
      attr_reader prometheus: PrometheusMetricsOptions?
      attr_reader attach_service_name: bool
      attr_reader global_tags: Hash[String, String]?
      attr_reader metric_prefix: String?

      def initialize: (
        ?opentelemetry: OpenTelemetryMetricsOptions?,
        ?prometheus: PrometheusMetricsOptions?,
        ?attach_service_name: bool,
        ?global_tags: Hash[String, String]?,
        ?metric_prefix: String?
      ) -> void

      def _to_bridge: -> Internal::Bridge::Runtime::MetricsOptions
    end

    class OpenTelemetryMetricsOptions
      module MetricTemporality
        CUMULATIVE: 1
        DELTA: 2

        type enum = 1 | 2
      end

      attr_reader url: String
      attr_reader headers: Hash[String, String]?
      attr_reader metric_periodicity: Float?
      attr_reader metric_temporality: MetricTemporality
      attr_reader durations_as_seconds: bool

      def initialize: (
        url: String,
        ?headers: Hash[String, String]?,
        ?metric_periodicity: Float?,
        ?metric_temporality: MetricTemporality,
        ?durations_as_seconds: bool
      ) -> void

      def _to_bridge: -> Internal::Bridge::Runtime::OpenTelemetryMetricsOptions
    end

    class PrometheusMetricsOptions
      attr_reader bind_address: String
      attr_reader counters_total_suffix: bool
      attr_reader unit_suffix: bool
      attr_reader durations_as_seconds: bool

      def initialize: (
        bind_address: String,
        ?counters_total_suffix: bool,
        ?unit_suffix: bool,
        ?durations_as_seconds: bool
      ) -> void

      def _to_bridge: -> Internal::Bridge::Runtime::PrometheusMetricsOptions
    end

    def self.default: -> Runtime
    def self.default=: (Runtime runtime) -> void

    attr_reader metric_meter: Metric::Meter

    def initialize: (?telemetry: TelemetryOptions) -> void

    def _core_runtime: -> Internal::Bridge::Runtime
  end
end