module Temporalio
  class SearchAttributes
    class Key
      attr_reader name: String
      attr_reader type: Integer

      def initialize: (String name, Integer type) -> void

      def validate_value: (Object value) -> void

      def value_set: (Object value) -> Update
      def value_unset: -> Update
    end

    class Update
      attr_reader key: Key
      attr_reader value: Object?

      def initialize: (Key key, Object? value) -> void

      def _to_proto_pair: -> [String, untyped]
    end

    def self._from_proto: (
      untyped proto,
      ?disable_mutations: bool,
      ?never_nil: bool
    ) -> SearchAttributes?

    def self._value_from_payload: (untyped payload) -> Object?

    def self._to_proto_pair: (Key key, Object? value) -> [String, untyped]

    def initialize: (SearchAttributes existing) -> void
                  | (Hash[Key, Object] existing) -> void
                  | -> void

    def []=: (Key | String | Symbol key, Object? value) -> void
    def []: (Key key) -> Object?

    def delete: (Key | String | Symbol key) -> void

    def each: { (Key key, Object value) -> void } -> self

    def to_h: -> Hash[Key, Object]

    def dup: -> SearchAttributes

    def empty?: -> bool

    def length: -> Integer

    alias size length

    def update: (*Update updates) -> SearchAttributes

    def update!: (*Update updates) -> void

    def _to_proto: -> untyped

    def _to_proto_hash: -> Hash[String, untyped]

    def _assert_mutations_enabled: -> void

    def _disable_mutations=: (bool value) -> void

    module IndexedValueType
      TEXT: Integer
      KEYWORD: Integer
      INTEGER: Integer
      FLOAT: Integer
      BOOLEAN: Integer
      TIME: Integer
      KEYWORD_LIST: Integer

      PROTO_NAMES: Hash[Integer, String]
      PROTO_VALUES: Hash[String, Integer]
    end
  end
end