module Temporalio
  class WorkflowHistory
    def self.from_history_json: (String json) -> WorkflowHistory

    attr_reader events: Array[Api::History::V1::HistoryEvent]
    
    def initialize: (Array[Api::History::V1::HistoryEvent] events) -> void

    def workflow_id: -> String

    def to_history_json: -> String
  end
end
