module Temporalio
  class Workflow
    module Async
      def self.run: [T] { () -> T } -> Temporalio::Workflow::Future[T]
      def self.all: (*Temporalio::Workflow::Future[untyped] futures) -> Temporalio::Workflow::Future[nil]
      def self.any: (*Temporalio::Workflow::Future[untyped] futures) -> Temporalio::Workflow::Future[nil]
    end
  end
end
