BRIDGE_DIR: String

class Rutie
  def initialize: (Symbol, release: String | Symbol) -> void
  def init: (String, String) -> void
end

module Temporal
  module Bridge
    class Error < StandardError
    end

    class Connection
      def self.connect: (Runtime, String) -> Temporal::Bridge::Connection
      def call: (Symbol, String, Hash[String, String], Integer?) -> String
    end

    class Runtime
      def self.init: () -> Temporal::Bridge::Runtime
      def run_callback_loop: () -> void
    end

    class Worker
      def self.create: (
        Temporal::Bridge::Runtime,
        Temporal::Bridge::Connection,
        String | Symbol,
        String | Symbol
      ) -> Temporal::Bridge::Worker
      def poll_activity_task: () { (String) -> void } -> void
    end
  end
end
