BRIDGE_DIR: String

class Rutie
  def initialize: (
    Symbol bridge,
    ?lib_path: String | Symbol,
    ?lib_suffix: String | Symbol,
    ?lib_prefix: String | Symbol
  ) -> void
  def init: (String, String) -> void
end

module Temporal
  module Bridge
    class Error < StandardError
    end

    class Connection
      def self.connect: (Runtime, String) -> Temporal::Bridge::Connection
      def call: (Symbol, String, Hash[String, String], Integer?) -> String
    end

    class Runtime
      def self.init: () -> Temporal::Bridge::Runtime
      def run_callback_loop: () -> void
    end
  end
end
