module Temporal
  class Error < StandardError
    class RPCError < Error
    end

    class UnexpectedResponse < RPCError
    end

    class UnsupportedQuery < RPCError
    end

    class QueryRejected < RPCError
      attr_reader status: Temporal::Workflow::ExecutionStatus::values

      def initialize: (Temporal::Workflow::ExecutionStatus::values) -> void
    end
  end
end
