module Temporal
  class Runtime
    attr_reader core_runtime: Temporal::Bridge::Runtime
    attr_reader reactor: Temporal::Worker::Reactor

    @thread: Thread

    def self.instance: () -> Runtime
    def initialize: () -> void
    def ensure_callback_loop: () -> void
  end
end
