module Temporalio
  module Api
    module TaskQueue
      module V1
        # See https://docs.temporal.io/docs/concepts/task-queues/
        #
        class TaskQueue < ::Protobuf::Message
          attr_accessor name(): ::String

          def name!: () -> ::String?

          # Default: TASK_QUEUE_KIND_NORMAL.
          #
          attr_accessor kind(): ::Temporalio::Api::Enums::V1::TaskQueueKind

          # Default: TASK_QUEUE_KIND_NORMAL.
          #
          def kind=: (::Temporalio::Api::Enums::V1::TaskQueueKind::values) -> ::Temporalio::Api::Enums::V1::TaskQueueKind::values
                   | ...

          def kind!: () -> ::Temporalio::Api::Enums::V1::TaskQueueKind?

          def initialize: (?name: ::String, ?kind: ::Temporalio::Api::Enums::V1::TaskQueueKind::init) -> void

          def []: (:name) -> ::String
                | (:kind) -> ::Temporalio::Api::Enums::V1::TaskQueueKind
                | (::Symbol) -> untyped

          def []=: (:name, ::String) -> ::String
                 | (:kind, ::Temporalio::Api::Enums::V1::TaskQueueKind) -> ::Temporalio::Api::Enums::V1::TaskQueueKind
                 | (:kind, ::Temporalio::Api::Enums::V1::TaskQueueKind::values) -> ::Temporalio::Api::Enums::V1::TaskQueueKind::values
                 | (::Symbol, untyped) -> untyped

          interface _ToProto
            def to_proto: () -> TaskQueue
          end

          # The type of `#initialize` parameter.
          type init = TaskQueue | _ToProto

          # The type of `repeated` field.
          type field_array = ::Protobuf::Field::FieldArray[TaskQueue, TaskQueue | _ToProto]

          # The type of `map` field.
          type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, TaskQueue, TaskQueue | _ToProto]

          type array = ::Array[TaskQueue | _ToProto]

          type hash[KEY] = ::Hash[KEY, TaskQueue | _ToProto]
        end

        # Only applies to activity task queues
        #
        class TaskQueueMetadata < ::Protobuf::Message
          # Allows throttling dispatch of tasks from this queue
          #
          attr_accessor max_tasks_per_second(): ::Google::Protobuf::DoubleValue?

          # Allows throttling dispatch of tasks from this queue
          #
          def max_tasks_per_second=: [M < ::Google::Protobuf::DoubleValue::_ToProto] (M?) -> M?
                                   | ...

          def max_tasks_per_second!: () -> ::Google::Protobuf::DoubleValue?

          def initialize: (?max_tasks_per_second: ::Google::Protobuf::DoubleValue::init?) -> void

          def []: (:max_tasks_per_second) -> ::Google::Protobuf::DoubleValue?
                | (::Symbol) -> untyped

          def []=: (:max_tasks_per_second, ::Google::Protobuf::DoubleValue?) -> ::Google::Protobuf::DoubleValue?
                 | [M < ::Google::Protobuf::DoubleValue::_ToProto] (:max_tasks_per_second, M?) -> M?
                 | (::Symbol, untyped) -> untyped

          interface _ToProto
            def to_proto: () -> TaskQueueMetadata
          end

          # The type of `#initialize` parameter.
          type init = TaskQueueMetadata | _ToProto

          # The type of `repeated` field.
          type field_array = ::Protobuf::Field::FieldArray[TaskQueueMetadata, TaskQueueMetadata | _ToProto]

          # The type of `map` field.
          type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, TaskQueueMetadata, TaskQueueMetadata | _ToProto]

          type array = ::Array[TaskQueueMetadata | _ToProto]

          type hash[KEY] = ::Hash[KEY, TaskQueueMetadata | _ToProto]
        end

        class TaskQueueStatus < ::Protobuf::Message
          attr_accessor backlog_count_hint(): ::Integer

          def backlog_count_hint!: () -> ::Integer?

          attr_accessor read_level(): ::Integer

          def read_level!: () -> ::Integer?

          attr_accessor ack_level(): ::Integer

          def ack_level!: () -> ::Integer?

          attr_accessor rate_per_second(): ::Float

          def rate_per_second!: () -> ::Float?

          attr_accessor task_id_block(): ::Temporalio::Api::TaskQueue::V1::TaskIdBlock?

          def task_id_block=: [M < ::Temporalio::Api::TaskQueue::V1::TaskIdBlock::_ToProto] (M?) -> M?
                            | ...

          def task_id_block!: () -> ::Temporalio::Api::TaskQueue::V1::TaskIdBlock?

          def initialize: (?backlog_count_hint: ::Integer, ?read_level: ::Integer, ?ack_level: ::Integer, ?rate_per_second: ::Float, ?task_id_block: ::Temporalio::Api::TaskQueue::V1::TaskIdBlock::init?) -> void

          def []: (:backlog_count_hint) -> ::Integer
                | (:read_level) -> ::Integer
                | (:ack_level) -> ::Integer
                | (:rate_per_second) -> ::Float
                | (:task_id_block) -> ::Temporalio::Api::TaskQueue::V1::TaskIdBlock?
                | (::Symbol) -> untyped

          def []=: (:backlog_count_hint, ::Integer) -> ::Integer
                 | (:read_level, ::Integer) -> ::Integer
                 | (:ack_level, ::Integer) -> ::Integer
                 | (:rate_per_second, ::Float) -> ::Float
                 | (:task_id_block, ::Temporalio::Api::TaskQueue::V1::TaskIdBlock?) -> ::Temporalio::Api::TaskQueue::V1::TaskIdBlock?
                 | [M < ::Temporalio::Api::TaskQueue::V1::TaskIdBlock::_ToProto] (:task_id_block, M?) -> M?
                 | (::Symbol, untyped) -> untyped

          interface _ToProto
            def to_proto: () -> TaskQueueStatus
          end

          # The type of `#initialize` parameter.
          type init = TaskQueueStatus | _ToProto

          # The type of `repeated` field.
          type field_array = ::Protobuf::Field::FieldArray[TaskQueueStatus, TaskQueueStatus | _ToProto]

          # The type of `map` field.
          type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, TaskQueueStatus, TaskQueueStatus | _ToProto]

          type array = ::Array[TaskQueueStatus | _ToProto]

          type hash[KEY] = ::Hash[KEY, TaskQueueStatus | _ToProto]
        end

        class TaskIdBlock < ::Protobuf::Message
          attr_accessor start_id(): ::Integer

          def start_id!: () -> ::Integer?

          attr_accessor end_id(): ::Integer

          def end_id!: () -> ::Integer?

          def initialize: (?start_id: ::Integer, ?end_id: ::Integer) -> void

          def []: (:start_id) -> ::Integer
                | (:end_id) -> ::Integer
                | (::Symbol) -> untyped

          def []=: (:start_id, ::Integer) -> ::Integer
                 | (:end_id, ::Integer) -> ::Integer
                 | (::Symbol, untyped) -> untyped

          interface _ToProto
            def to_proto: () -> TaskIdBlock
          end

          # The type of `#initialize` parameter.
          type init = TaskIdBlock | _ToProto

          # The type of `repeated` field.
          type field_array = ::Protobuf::Field::FieldArray[TaskIdBlock, TaskIdBlock | _ToProto]

          # The type of `map` field.
          type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, TaskIdBlock, TaskIdBlock | _ToProto]

          type array = ::Array[TaskIdBlock | _ToProto]

          type hash[KEY] = ::Hash[KEY, TaskIdBlock | _ToProto]
        end

        class TaskQueuePartitionMetadata < ::Protobuf::Message
          attr_accessor key(): ::String

          def key!: () -> ::String?

          attr_accessor owner_host_name(): ::String

          def owner_host_name!: () -> ::String?

          def initialize: (?key: ::String, ?owner_host_name: ::String) -> void

          def []: (:key) -> ::String
                | (:owner_host_name) -> ::String
                | (::Symbol) -> untyped

          def []=: (:key, ::String) -> ::String
                 | (:owner_host_name, ::String) -> ::String
                 | (::Symbol, untyped) -> untyped

          interface _ToProto
            def to_proto: () -> TaskQueuePartitionMetadata
          end

          # The type of `#initialize` parameter.
          type init = TaskQueuePartitionMetadata | _ToProto

          # The type of `repeated` field.
          type field_array = ::Protobuf::Field::FieldArray[TaskQueuePartitionMetadata, TaskQueuePartitionMetadata | _ToProto]

          # The type of `map` field.
          type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, TaskQueuePartitionMetadata, TaskQueuePartitionMetadata | _ToProto]

          type array = ::Array[TaskQueuePartitionMetadata | _ToProto]

          type hash[KEY] = ::Hash[KEY, TaskQueuePartitionMetadata | _ToProto]
        end

        class PollerInfo < ::Protobuf::Message
          # Unix Nano
          #
          attr_accessor last_access_time(): ::Google::Protobuf::Timestamp?

          # Unix Nano
          #
          def last_access_time=: [M < ::Google::Protobuf::Timestamp::_ToProto] (M?) -> M?
                               | ...

          def last_access_time!: () -> ::Google::Protobuf::Timestamp?

          attr_accessor identity(): ::String

          def identity!: () -> ::String?

          attr_accessor rate_per_second(): ::Float

          def rate_per_second!: () -> ::Float?

          # If a worker has specified an ID for use with the worker versioning feature while polling,
          #  that id must appear here.
          #
          attr_accessor worker_versioning_id(): ::Temporalio::Api::TaskQueue::V1::VersionId?

          # If a worker has specified an ID for use with the worker versioning feature while polling,
          #  that id must appear here.
          #
          def worker_versioning_id=: [M < ::Temporalio::Api::TaskQueue::V1::VersionId::_ToProto] (M?) -> M?
                                   | ...

          def worker_versioning_id!: () -> ::Temporalio::Api::TaskQueue::V1::VersionId?

          def initialize: (?last_access_time: ::Google::Protobuf::Timestamp::init?, ?identity: ::String, ?rate_per_second: ::Float, ?worker_versioning_id: ::Temporalio::Api::TaskQueue::V1::VersionId::init?) -> void

          def []: (:last_access_time) -> ::Google::Protobuf::Timestamp?
                | (:identity) -> ::String
                | (:rate_per_second) -> ::Float
                | (:worker_versioning_id) -> ::Temporalio::Api::TaskQueue::V1::VersionId?
                | (::Symbol) -> untyped

          def []=: (:last_access_time, ::Google::Protobuf::Timestamp?) -> ::Google::Protobuf::Timestamp?
                 | [M < ::Google::Protobuf::Timestamp::_ToProto] (:last_access_time, M?) -> M?
                 | (:identity, ::String) -> ::String
                 | (:rate_per_second, ::Float) -> ::Float
                 | (:worker_versioning_id, ::Temporalio::Api::TaskQueue::V1::VersionId?) -> ::Temporalio::Api::TaskQueue::V1::VersionId?
                 | [M < ::Temporalio::Api::TaskQueue::V1::VersionId::_ToProto] (:worker_versioning_id, M?) -> M?
                 | (::Symbol, untyped) -> untyped

          interface _ToProto
            def to_proto: () -> PollerInfo
          end

          # The type of `#initialize` parameter.
          type init = PollerInfo | _ToProto

          # The type of `repeated` field.
          type field_array = ::Protobuf::Field::FieldArray[PollerInfo, PollerInfo | _ToProto]

          # The type of `map` field.
          type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, PollerInfo, PollerInfo | _ToProto]

          type array = ::Array[PollerInfo | _ToProto]

          type hash[KEY] = ::Hash[KEY, PollerInfo | _ToProto]
        end

        class StickyExecutionAttributes < ::Protobuf::Message
          attr_accessor worker_task_queue(): ::Temporalio::Api::TaskQueue::V1::TaskQueue?

          def worker_task_queue=: [M < ::Temporalio::Api::TaskQueue::V1::TaskQueue::_ToProto] (M?) -> M?
                                | ...

          def worker_task_queue!: () -> ::Temporalio::Api::TaskQueue::V1::TaskQueue?

          # (-- api-linter: core::0140::prepositions=disabled
          #      aip.dev/not-precedent: "to" is used to indicate interval. --)
          #
          attr_accessor schedule_to_start_timeout(): ::Google::Protobuf::Duration?

          # (-- api-linter: core::0140::prepositions=disabled
          #      aip.dev/not-precedent: "to" is used to indicate interval. --)
          #
          def schedule_to_start_timeout=: [M < ::Google::Protobuf::Duration::_ToProto] (M?) -> M?
                                        | ...

          def schedule_to_start_timeout!: () -> ::Google::Protobuf::Duration?

          def initialize: (?worker_task_queue: ::Temporalio::Api::TaskQueue::V1::TaskQueue::init?, ?schedule_to_start_timeout: ::Google::Protobuf::Duration::init?) -> void

          def []: (:worker_task_queue) -> ::Temporalio::Api::TaskQueue::V1::TaskQueue?
                | (:schedule_to_start_timeout) -> ::Google::Protobuf::Duration?
                | (::Symbol) -> untyped

          def []=: (:worker_task_queue, ::Temporalio::Api::TaskQueue::V1::TaskQueue?) -> ::Temporalio::Api::TaskQueue::V1::TaskQueue?
                 | [M < ::Temporalio::Api::TaskQueue::V1::TaskQueue::_ToProto] (:worker_task_queue, M?) -> M?
                 | (:schedule_to_start_timeout, ::Google::Protobuf::Duration?) -> ::Google::Protobuf::Duration?
                 | [M < ::Google::Protobuf::Duration::_ToProto] (:schedule_to_start_timeout, M?) -> M?
                 | (::Symbol, untyped) -> untyped

          interface _ToProto
            def to_proto: () -> StickyExecutionAttributes
          end

          # The type of `#initialize` parameter.
          type init = StickyExecutionAttributes | _ToProto

          # The type of `repeated` field.
          type field_array = ::Protobuf::Field::FieldArray[StickyExecutionAttributes, StickyExecutionAttributes | _ToProto]

          # The type of `map` field.
          type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, StickyExecutionAttributes, StickyExecutionAttributes | _ToProto]

          type array = ::Array[StickyExecutionAttributes | _ToProto]

          type hash[KEY] = ::Hash[KEY, StickyExecutionAttributes | _ToProto]
        end

        # Used by the worker versioning APIs, represents a node in the version graph for a particular
        #  task queue
        #
        class VersionIdNode < ::Protobuf::Message
          attr_accessor version(): ::Temporalio::Api::TaskQueue::V1::VersionId?

          def version=: [M < ::Temporalio::Api::TaskQueue::V1::VersionId::_ToProto] (M?) -> M?
                      | ...

          def version!: () -> ::Temporalio::Api::TaskQueue::V1::VersionId?

          # A pointer to the previous version this version is considered to be compatible with
          #
          attr_accessor previous_compatible(): ::Temporalio::Api::TaskQueue::V1::VersionIdNode?

          # A pointer to the previous version this version is considered to be compatible with
          #
          def previous_compatible=: [M < ::Temporalio::Api::TaskQueue::V1::VersionIdNode::_ToProto] (M?) -> M?
                                  | ...

          def previous_compatible!: () -> ::Temporalio::Api::TaskQueue::V1::VersionIdNode?

          # A pointer to the last incompatible version (previous major version)
          #
          attr_accessor previous_incompatible(): ::Temporalio::Api::TaskQueue::V1::VersionIdNode?

          # A pointer to the last incompatible version (previous major version)
          #
          def previous_incompatible=: [M < ::Temporalio::Api::TaskQueue::V1::VersionIdNode::_ToProto] (M?) -> M?
                                    | ...

          def previous_incompatible!: () -> ::Temporalio::Api::TaskQueue::V1::VersionIdNode?

          def initialize: (?version: ::Temporalio::Api::TaskQueue::V1::VersionId::init?, ?previous_compatible: ::Temporalio::Api::TaskQueue::V1::VersionIdNode::init?, ?previous_incompatible: ::Temporalio::Api::TaskQueue::V1::VersionIdNode::init?) -> void

          def []: (:version) -> ::Temporalio::Api::TaskQueue::V1::VersionId?
                | (:previous_compatible) -> ::Temporalio::Api::TaskQueue::V1::VersionIdNode?
                | (:previous_incompatible) -> ::Temporalio::Api::TaskQueue::V1::VersionIdNode?
                | (::Symbol) -> untyped

          def []=: (:version, ::Temporalio::Api::TaskQueue::V1::VersionId?) -> ::Temporalio::Api::TaskQueue::V1::VersionId?
                 | [M < ::Temporalio::Api::TaskQueue::V1::VersionId::_ToProto] (:version, M?) -> M?
                 | (:previous_compatible, ::Temporalio::Api::TaskQueue::V1::VersionIdNode?) -> ::Temporalio::Api::TaskQueue::V1::VersionIdNode?
                 | [M < ::Temporalio::Api::TaskQueue::V1::VersionIdNode::_ToProto] (:previous_compatible, M?) -> M?
                 | (:previous_incompatible, ::Temporalio::Api::TaskQueue::V1::VersionIdNode?) -> ::Temporalio::Api::TaskQueue::V1::VersionIdNode?
                 | [M < ::Temporalio::Api::TaskQueue::V1::VersionIdNode::_ToProto] (:previous_incompatible, M?) -> M?
                 | (::Symbol, untyped) -> untyped

          interface _ToProto
            def to_proto: () -> VersionIdNode
          end

          # The type of `#initialize` parameter.
          type init = VersionIdNode | _ToProto

          # The type of `repeated` field.
          type field_array = ::Protobuf::Field::FieldArray[VersionIdNode, VersionIdNode | _ToProto]

          # The type of `map` field.
          type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, VersionIdNode, VersionIdNode | _ToProto]

          type array = ::Array[VersionIdNode | _ToProto]

          type hash[KEY] = ::Hash[KEY, VersionIdNode | _ToProto]
        end

        # Used by the worker versioning APIs, represents a specific version of something
        #  Currently, that's just a whole-worker id. In the future, if we support
        #  WASM workflow bundle based versioning, for example, then the inside of this
        #  message may become a oneof of different version types.
        #
        class VersionId < ::Protobuf::Message
          # An opaque whole-worker identifier
          #
          attr_accessor worker_build_id(): ::String

          def worker_build_id!: () -> ::String?

          def initialize: (?worker_build_id: ::String) -> void

          def []: (:worker_build_id) -> ::String
                | (::Symbol) -> untyped

          def []=: (:worker_build_id, ::String) -> ::String
                 | (::Symbol, untyped) -> untyped

          interface _ToProto
            def to_proto: () -> VersionId
          end

          # The type of `#initialize` parameter.
          type init = VersionId | _ToProto

          # The type of `repeated` field.
          type field_array = ::Protobuf::Field::FieldArray[VersionId, VersionId | _ToProto]

          # The type of `map` field.
          type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, VersionId, VersionId | _ToProto]

          type array = ::Array[VersionId | _ToProto]

          type hash[KEY] = ::Hash[KEY, VersionId | _ToProto]
        end
      end
    end
  end
end
