module Temporalio
  class Client
    module ActivityExecutionStatus
      type enum = Integer

      UNSPECIFIED: enum
      RUNNING: enum
      COMPLETED: enum
      FAILED: enum
      CANCELED: enum
      TERMINATED: enum
      TIMED_OUT: enum
      PAUSED: enum
    end
  end
end
