module Temporalio
  class Client
    class AsyncActivityHandle
      attr_reader task_token: String?
      attr_reader id_reference: ActivityIDReference?

      def initialize: (
        client: Client,
        task_token: String?,
        id_reference: ActivityIDReference?
      ) -> void

      def heartbeat: (
        *Object? details,
        ?detail_hints: Array[Object]?,
        ?rpc_options: RPCOptions?
      ) -> void

      def complete: (
        ?Object? result,
        ?result_hint: Object?,
        ?rpc_options: RPCOptions?
      ) -> void

      def fail: (
        Exception error,
        ?last_heartbeat_details: Array[Object?],
        ?last_heartbeat_detail_hints: Array[Object]?,
        ?rpc_options: RPCOptions?
      ) -> void

      def report_cancellation: (
        *Object? details,
        ?detail_hints: Array[Object]?,
        ?rpc_options: RPCOptions?
      ) -> void

      private def task_token_or_id_reference: -> (String | ActivityIDReference)
    end
  end
end