module Temporalio
  class Client
    module Interceptor
      def intercept_client: (Outbound next_interceptor) -> Outbound

      class StartWorkflowInput
        attr_reader workflow: singleton(Workflow::Definition) | Workflow::Definition::Info | Symbol | String
        attr_reader args: Array[Object?]
        attr_reader workflow_id: String
        attr_reader task_queue: String
        attr_reader static_summary: String?
        attr_reader static_details: String?
        attr_reader execution_timeout: duration?
        attr_reader run_timeout: duration?
        attr_reader task_timeout: duration?
        attr_reader id_reuse_policy: WorkflowIDReusePolicy::enum
        attr_reader id_conflict_policy: WorkflowIDConflictPolicy::enum
        attr_reader retry_policy: RetryPolicy?
        attr_reader cron_schedule: String?
        attr_reader memo: Hash[String | Symbol, Object?]?
        attr_reader search_attributes: SearchAttributes?
        attr_reader start_delay: duration?
        attr_reader request_eager_start: bool
        attr_reader headers: Hash[String, Object?]
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          workflow: singleton(Workflow::Definition) | Workflow::Definition::Info | Symbol | String,
          args: Array[Object?],
          workflow_id: String,
          task_queue: String,
          static_summary: String?,
          static_details: String?,
          execution_timeout: duration?,
          run_timeout: duration?,
          task_timeout: duration?,
          id_reuse_policy: WorkflowIDReusePolicy::enum,
          id_conflict_policy: WorkflowIDConflictPolicy::enum,
          retry_policy: RetryPolicy?,
          cron_schedule: String?,
          memo: Hash[String | Symbol, Object?]?,
          search_attributes: SearchAttributes?,
          start_delay: duration?,
          request_eager_start: bool,
          headers: Hash[String, Object?],
          rpc_options: RPCOptions?
        ) -> void
      end

      class StartUpdateWithStartWorkflowInput
        attr_reader update_id: String
        attr_reader update: Workflow::Definition::Update | Symbol | String
        attr_reader args: Array[Object?]
        attr_reader wait_for_stage: WorkflowUpdateWaitStage::enum
        attr_reader start_workflow_operation: WithStartWorkflowOperation
        attr_reader headers: Hash[String, Object?]
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          update_id: String,
          update: Workflow::Definition::Update | Symbol | String,
          args: Array[Object?],
          wait_for_stage: WorkflowUpdateWaitStage::enum,
          start_workflow_operation: WithStartWorkflowOperation,
          headers: Hash[String, Object?],
          rpc_options: RPCOptions?
        ) -> void
      end

      class SignalWithStartWorkflowInput
        attr_reader signal: Workflow::Definition::Signal | Symbol | String
        attr_reader args: Array[Object?]
        attr_reader start_workflow_operation: WithStartWorkflowOperation
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          signal: Workflow::Definition::Signal | Symbol | String,
          args: Array[Object?],
          start_workflow_operation: WithStartWorkflowOperation,
          rpc_options: RPCOptions?
        ) -> void
      end

      class ListWorkflowsInput
        attr_reader query: String?
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          query: String?,
          rpc_options: RPCOptions?
        ) -> void
      end

      class CountWorkflowsInput
        attr_reader query: String?
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          query: String?,
          rpc_options: RPCOptions?
        ) -> void
      end

      class DescribeWorkflowInput
        attr_reader workflow_id: String
        attr_reader run_id: String?
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          workflow_id: String,
          run_id: String?,
          rpc_options: RPCOptions?
        ) -> void
      end

      class FetchWorkflowHistoryEventsInput
        attr_reader workflow_id: String
        attr_reader run_id: String?
        attr_reader wait_new_event: bool
        attr_reader event_filter_type: Integer
        attr_reader skip_archival: bool
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          workflow_id: String,
          run_id: String?,
          wait_new_event: bool,
          event_filter_type: Integer,
          skip_archival: bool,
          rpc_options: RPCOptions?
        ) -> void
      end

      class SignalWorkflowInput
        attr_reader workflow_id: String
        attr_reader run_id: String?
        attr_reader signal: Workflow::Definition::Signal | Symbol | String
        attr_reader args: Array[Object?]
        attr_reader headers: Hash[String, Object?]
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          workflow_id: String,
          run_id: String?,
          signal: Workflow::Definition::Signal | Symbol | String,
          args: Array[Object?],
          headers: Hash[String, Object?],
          rpc_options: RPCOptions?
        ) -> void
      end

      class QueryWorkflowInput
        attr_reader workflow_id: String
        attr_reader run_id: String?
        attr_reader query: Workflow::Definition::Query | Symbol | String
        attr_reader args: Array[Object?]
        attr_reader reject_condition: WorkflowQueryRejectCondition::enum?
        attr_reader headers: Hash[String, Object?]
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          workflow_id: String,
          run_id: String?,
          query: Workflow::Definition::Query | Symbol | String,
          args: Array[Object?],
          reject_condition: WorkflowQueryRejectCondition::enum?,
          headers: Hash[String, Object?],
          rpc_options: RPCOptions?
        ) -> void
      end

      class StartWorkflowUpdateInput
        attr_reader workflow_id: String
        attr_reader run_id: String?
        attr_reader update_id: String
        attr_reader update: Workflow::Definition::Update | Symbol | String
        attr_reader args: Array[Object?]
        attr_reader wait_for_stage: WorkflowUpdateWaitStage::enum
        attr_reader headers: Hash[String, Object?]
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          workflow_id: String,
          run_id: String?,
          update_id: String,
          update: Workflow::Definition::Update | Symbol | String,
          args: Array[Object?],
          wait_for_stage: WorkflowUpdateWaitStage::enum,
          headers: Hash[String, Object?],
          rpc_options: RPCOptions?
        ) -> void
      end

      class PollWorkflowUpdateInput
        attr_reader workflow_id: String
        attr_reader run_id: String?
        attr_reader update_id: String
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          workflow_id: String,
          run_id: String?,
          update_id: String,
          rpc_options: RPCOptions?
        ) -> void
      end

      class CancelWorkflowInput
        attr_reader workflow_id: String
        attr_reader run_id: String?
        attr_reader first_execution_run_id: String?
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          workflow_id: String,
          run_id: String?,
          first_execution_run_id: String?,
          rpc_options: RPCOptions?
        ) -> void
      end

      class TerminateWorkflowInput
        attr_reader workflow_id: String
        attr_reader run_id: String?
        attr_reader first_execution_run_id: String?
        attr_reader reason: String?
        attr_reader details: Array[Object?]
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          workflow_id: String,
          run_id: String?,
          first_execution_run_id: String?,
          reason: String?,
          details: Array[Object?],
          rpc_options: RPCOptions?
        ) -> void
      end

      class CreateScheduleInput
        attr_reader id: String
        attr_reader schedule: Schedule
        attr_reader trigger_immediately: bool
        attr_reader backfills: Array[Schedule::Backfill]
        attr_reader memo: Hash[String | Symbol, Object?]?
        attr_reader search_attributes: SearchAttributes?
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          id: String,
          schedule: Schedule,
          trigger_immediately: bool,
          backfills: Array[Schedule::Backfill],
          memo: Hash[String | Symbol, Object?]?,
          search_attributes: SearchAttributes?,
          rpc_options: RPCOptions?
        ) -> void
      end

      class ListSchedulesInput
        attr_reader query: String?
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          query: String?,
          rpc_options: RPCOptions?
        ) -> void
      end

      class BackfillScheduleInput
        attr_reader id: String
        attr_reader backfills: Array[Schedule::Backfill]
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          id: String,
          backfills: Array[Schedule::Backfill],
          rpc_options: RPCOptions?
        ) -> void
      end

      class DeleteScheduleInput
        attr_reader id: String
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          id: String,
          rpc_options: RPCOptions?
        ) -> void
      end

      class DescribeScheduleInput
        attr_reader id: String
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          id: String,
          rpc_options: RPCOptions?
        ) -> void
      end

      class PauseScheduleInput
        attr_reader id: String
        attr_reader note: String
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          id: String,
          note: String,
          rpc_options: RPCOptions?
        ) -> void
      end

      class TriggerScheduleInput
        attr_reader id: String
        attr_reader overlap: Schedule::OverlapPolicy::enum?
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          id: String,
          overlap: Schedule::OverlapPolicy::enum?,
          rpc_options: RPCOptions?
        ) -> void
      end

      class UnpauseScheduleInput
        attr_reader id: String
        attr_reader note: String
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          id: String,
          note: String,
          rpc_options: RPCOptions?
        ) -> void
      end

      class UpdateScheduleInput
        attr_reader id: String
        attr_reader updater: ^(Schedule::Update::Input) -> Schedule::Update?
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          id: String,
          updater: ^(Schedule::Update::Input) -> Schedule::Update?,
          rpc_options: RPCOptions?
        ) -> void
      end

      class HeartbeatAsyncActivityInput
        attr_reader task_token_or_id_reference: String | ActivityIDReference
        attr_reader details: Array[Object?]
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          task_token_or_id_reference: String | ActivityIDReference,
          details: Array[Object?],
          rpc_options: RPCOptions?
        ) -> void
      end

      class CompleteAsyncActivityInput
        attr_reader task_token_or_id_reference: String | ActivityIDReference
        attr_reader result: Object?
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          task_token_or_id_reference: String | ActivityIDReference,
          result: Object?,
          rpc_options: RPCOptions?
        ) -> void
      end

      class FailAsyncActivityInput
        attr_reader task_token_or_id_reference: String | ActivityIDReference
        attr_reader error: Exception
        attr_reader last_heartbeat_details: Array[Object?]
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          task_token_or_id_reference: String | ActivityIDReference,
          error: Exception,
          last_heartbeat_details: Array[Object?],
          rpc_options: RPCOptions?
        ) -> void
      end

      class ReportCancellationAsyncActivityInput
        attr_reader task_token_or_id_reference: String | ActivityIDReference
        attr_reader details: Array[Object?]
        attr_reader rpc_options: RPCOptions?

        def initialize: (
          task_token_or_id_reference: String | ActivityIDReference,
          details: Array[Object?],
          rpc_options: RPCOptions?
        ) -> void
      end

      class Outbound
        attr_reader next_interceptor: Outbound

        def initialize: (Outbound next_interceptor) -> void

        def start_workflow: (StartWorkflowInput input) -> WorkflowHandle

        def start_update_with_start_workflow: (StartUpdateWithStartWorkflowInput input) -> WorkflowUpdateHandle

        def signal_with_start_workflow: (SignalWithStartWorkflowInput input) -> WorkflowHandle

        def list_workflows: (ListWorkflowsInput input) -> Enumerator[WorkflowExecution, WorkflowExecution]

        def count_workflows: (CountWorkflowsInput input) -> WorkflowExecutionCount

        def describe_workflow: (DescribeWorkflowInput input) -> WorkflowExecution::Description

        def fetch_workflow_history_events: (FetchWorkflowHistoryEventsInput input) -> Enumerator[untyped, untyped]

        def signal_workflow: (SignalWorkflowInput input) -> void

        def query_workflow: (QueryWorkflowInput input) -> Object?

        def start_workflow_update: (StartWorkflowUpdateInput input) -> WorkflowUpdateHandle

        def poll_workflow_update: (PollWorkflowUpdateInput input) -> untyped

        def cancel_workflow: (CancelWorkflowInput input) -> void

        def terminate_workflow: (TerminateWorkflowInput input) -> void

        def create_schedule: (CreateScheduleInput input) -> ScheduleHandle

        def list_schedules: (ListSchedulesInput input) -> Enumerator[WorkflowExecution, WorkflowExecution]

        def backfill_schedule: (BackfillScheduleInput input) -> void

        def delete_schedule: (DeleteScheduleInput input) -> void

        def describe_schedule: (DescribeScheduleInput input) -> Schedule::Description

        def pause_schedule: (PauseScheduleInput input) -> void

        def trigger_schedule: (TriggerScheduleInput input) -> void

        def unpause_schedule: (UnpauseScheduleInput input) -> void

        def update_schedule: (UpdateScheduleInput input) -> void

        def heartbeat_async_activity: (HeartbeatAsyncActivityInput input) -> void

        def complete_async_activity: (CompleteAsyncActivityInput input) -> void

        def fail_async_activity: (FailAsyncActivityInput input) -> void

        def report_cancellation_async_activity: (ReportCancellationAsyncActivityInput input) -> void
      end
    end
  end
end