module Temporalio
  class Client
    class Schedule
      attr_accessor action: Action
      attr_accessor spec: Spec
      attr_accessor policy: Policy
      attr_accessor state: State

      def self._from_proto: (
        untyped raw_schedule,
        Converters::DataConverter data_converter
      ) -> Schedule

      def initialize: (
        action: Action,
        spec: Spec,
        ?policy: Policy,
        ?state: State
      ) -> void

      def _to_proto: (Converters::DataConverter data_converter) -> untyped

      class Description
        attr_accessor id: String
        attr_accessor schedule: Schedule
        attr_accessor info: Schedule::Info
        attr_accessor raw_description: untyped

        def initialize: (
          String id,
          untyped raw_description,
          Converters::DataConverter data_converter
        ) -> void

        def memo: -> Hash[String, Object?]?
        def search_attributes: -> SearchAttributes?
      end

      class Info
        attr_accessor num_actions: Integer
        attr_accessor num_actions_missed_catchup_window: Integer
        attr_accessor num_actions_skipped_overlap: Integer
        attr_accessor running_actions: Array[ActionExecution]
        attr_accessor recent_actions: Array[ActionResult]
        attr_accessor next_action_times: Array[Time]
        attr_accessor created_at: Time
        attr_accessor last_updated_at: Time?

        def initialize: (untyped raw_info) -> void
      end

      module Action
        def self._from_proto: (
          untyped raw_action,
          Converters::DataConverter data_converter
        ) -> Action

        def _to_proto: (Converters::DataConverter data_converter) -> untyped

        class StartWorkflow
          include Action

          attr_accessor workflow: String
          attr_accessor args: Array[Object?]
          attr_accessor id: String
          attr_accessor task_queue: String
          attr_accessor execution_timeout: Float?
          attr_accessor run_timeout: Float?
          attr_accessor task_timeout: Float?
          attr_accessor retry_policy: RetryPolicy?
          attr_accessor memo: Hash[String, Object?]?
          attr_accessor search_attributes: SearchAttributes?
          attr_accessor headers: Hash[String, Object?]?

          def self._from_proto: (
            untyped raw_info,
            Converters::DataConverter data_converter
          ) -> StartWorkflow

          def initialize: (
            String workflow,
            *Object? args,
            id: String,
            task_queue: String,
            ?execution_timeout: Float?,
            ?run_timeout: Float?,
            ?task_timeout: Float?,
            ?retry_policy: RetryPolicy?,
            ?memo: Hash[String, Object?]?,
            ?search_attributes: SearchAttributes?,
            ?headers: Hash[String, Object?]?
          ) -> void

          def _to_proto: (Converters::DataConverter data_converter) -> untyped
        end
      end

      module OverlapPolicy
        type enum = Integer
    
        SKIP: enum
        BUFFER_ONE: enum
        BUFFER_ALL: enum
        CANCEL_OTHER: enum
        TERMINATE_OTHER: enum
        ALLOW_ALL: enum
      end

      class Backfill
        attr_accessor start_at: Time
        attr_accessor end_at: Time
        attr_accessor overlap: OverlapPolicy::enum?

        def initialize: (
          start_at: Time,
          end_at: Time,
          ?overlap: OverlapPolicy::enum?
        ) -> void

        def _to_proto: -> untyped
      end

      module ActionExecution
        class StartWorkflow
          include ActionExecution

          attr_accessor workflow_id: String
          attr_accessor first_execution_run_id: String

          def initialize: (untyped raw_execution) -> void
        end
      end

      class ActionResult
        attr_accessor schedule_at: Time
        attr_accessor started_at: Time
        attr_accessor action: ActionExecution

        def initialize: (untyped raw_result) -> void
      end

      class Spec
        attr_accessor calendars: Array[Calendar]
        attr_accessor intervals: Array[Interval]
        attr_accessor cron_expressions: Array[String]
        attr_accessor skip: Array[Calendar]
        attr_accessor start_at: Time?
        attr_accessor end_at: Time?
        attr_accessor jitter: Float?
        attr_accessor time_zone_name: String?

        def self._from_proto: (untyped raw_spec) -> Spec

        def initialize: (
          ?calendars: Array[Calendar],
          ?intervals: Array[Interval],
          ?cron_expressions: Array[String],
          ?skip: Array[Calendar],
          ?start_at: Time?,
          ?end_at: Time?,
          ?jitter: Float?,
          ?time_zone_name: String?
        ) -> void

        def _to_proto: -> untyped

        class Calendar
          attr_accessor second: Array[Schedule::Range]
          attr_accessor minute: Array[Schedule::Range]
          attr_accessor hour: Array[Schedule::Range]
          attr_accessor day_of_month: Array[Schedule::Range]
          attr_accessor month: Array[Schedule::Range]
          attr_accessor year: Array[Schedule::Range]
          attr_accessor day_of_week: Array[Schedule::Range]
          attr_accessor comment: String?

          def self._from_proto: (untyped raw_cal) -> Calendar

          def initialize: (
            ?second: Array[Schedule::Range],
            ?minute: Array[Schedule::Range],
            ?hour: Array[Schedule::Range],
            ?day_of_month: Array[Schedule::Range],
            ?month: Array[Schedule::Range],
            ?year: Array[Schedule::Range],
            ?day_of_week: Array[Schedule::Range],
            ?comment: String?
          ) -> void

          def _to_proto: -> untyped
        end

        class Interval
          attr_accessor every: Float
          attr_accessor offset: Float?

          def self._from_proto: (untyped raw_int) -> Interval

          def initialize: (
            every: Float,
            ?offset: Float?
          ) -> void

          def _to_proto: -> untyped
        end
      end

      class Range
        attr_accessor start: Integer
        attr_accessor finish: Integer
        attr_accessor step: Integer

        def self._from_proto: (untyped raw_range) -> Range
        def self._from_protos: (Array[untyped] raw_ranges) -> Array[Range]
        def self._to_protos: (Array[Range] ranges) -> Array[untyped]

        def initialize: (
          Integer start,
          ?Integer finish,
          ?Integer step
        ) -> void

        def _to_proto: -> untyped
      end

      class Policy
        attr_accessor overlap: OverlapPolicy::enum
        attr_accessor catchup_window: Float
        attr_accessor pause_on_failure: bool

        def self._from_proto: (untyped raw_policies) -> Policy

        def initialize: (
          ?overlap: OverlapPolicy::enum,
          ?catchup_window: Float,
          ?pause_on_failure: bool
        ) -> void

        def _to_proto: -> untyped
      end

      class State
        attr_accessor note: String?
        attr_accessor paused: bool
        attr_accessor limited_actions: bool
        attr_accessor remaining_actions: Integer

        def self._from_proto: (untyped raw_state) -> State

        def initialize: (
          ?note: String?,
          ?paused: bool,
          ?limited_actions: bool,
          ?remaining_actions: Integer
        ) -> void

        def _to_proto: -> untyped
      end

      class Update
        attr_accessor schedule: Schedule
        attr_accessor search_attributes: SearchAttributes?

        def initialize: (
          schedule: Schedule,
          ?search_attributes: SearchAttributes?
        ) -> void

        class Input
          attr_accessor description: Description

          def initialize: (description: Description) -> void
        end
      end

      module List
        class Description
          attr_accessor id: String
          attr_accessor schedule: Schedule
          attr_accessor info: Info
          attr_accessor raw_entry: untyped

          def initialize: (
            untyped raw_entry,
            Converters::DataConverter data_converter
          ) -> void
        end

        class Schedule
          attr_accessor action: Action
          attr_accessor spec: Spec
          attr_accessor state: State

          def initialize: (untyped raw_info) -> void
        end

        module Action
          class StartWorkflow
            include Action

            attr_accessor workflow: String

            def initialize: (String workflow) -> void
          end
        end

        class Info
          attr_accessor recent_actions: Array[ActionResult]
          attr_accessor next_action_times: Array[Time]

          def initialize: (untyped raw_info) -> void
        end

        class State
          attr_accessor note: String?
          attr_accessor paused: bool

          def initialize: (untyped raw_info) -> void
        end
      end
    end
  end
end