AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  Exclude:
    - lib/gen/**/*
    - vendor/**/*

Gemspec/RequireMFA:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Metrics/ClassLength:
  Max: 400
