AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - lib/gen/**/*
    - vendor/**/*
    - spec/support/grpc/**/*

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MultilineBlockChain:
  Exclude:
    - spec/**/*_spec.rb

Style/RedundantReturn:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
  Exclude:
    - spec/**/*_spec.rb

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/AbcSize:
  Max: 75

Metrics/BlockLength:
  Exclude:
    - temporalio.gemspec
    - spec/**/*_spec.rb

Metrics/ClassLength:
  Max: 400

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/MethodLength:
  Max: 100

Metrics/ParameterLists:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 25

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case
