# Code generated by protoc-gen-rbi. DO NOT EDIT.
# source: temporal/api/nexusoperation/v1/message.proto
# typed: strict

# CallbackInfo contains the state of a callback attached to a standalone Nexus operation.
class Temporalio::Api::NexusOperation::V1::CallbackInfo
  include ::Google::Protobuf::MessageExts
  extend ::Google::Protobuf::MessageExts::ClassMethods

  sig do
    params(
      trigger: T.nilable(Temporalio::Api::NexusOperation::V1::CallbackInfo::Trigger),
      info: T.nilable(Temporalio::Api::Callback::V1::CallbackInfo)
    ).void
  end
  def initialize(
    trigger: nil,
    info: nil
  )
  end

  # Trigger for this callback.
  sig { returns(T.nilable(Temporalio::Api::NexusOperation::V1::CallbackInfo::Trigger)) }
  def trigger
  end

  # Trigger for this callback.
  sig { params(value: T.nilable(Temporalio::Api::NexusOperation::V1::CallbackInfo::Trigger)).void }
  def trigger=(value)
  end

  # Trigger for this callback.
  sig { void }
  def clear_trigger
  end

  # Common callback info.
  sig { returns(T.nilable(Temporalio::Api::Callback::V1::CallbackInfo)) }
  def info
  end

  # Common callback info.
  sig { params(value: T.nilable(Temporalio::Api::Callback::V1::CallbackInfo)).void }
  def info=(value)
  end

  # Common callback info.
  sig { void }
  def clear_info
  end

  sig { params(field: String).returns(T.untyped) }
  def [](field)
  end

  sig { params(field: String, value: T.untyped).void }
  def []=(field, value)
  end

  sig { returns(T::Hash[Symbol, T.untyped]) }
  def to_h
  end

  sig { params(str: String).returns(Temporalio::Api::NexusOperation::V1::CallbackInfo) }
  def self.decode(str)
  end

  sig { params(msg: Temporalio::Api::NexusOperation::V1::CallbackInfo).returns(String) }
  def self.encode(msg)
  end

  sig { params(str: String, kw: T.untyped).returns(Temporalio::Api::NexusOperation::V1::CallbackInfo) }
  def self.decode_json(str, **kw)
  end

  sig { params(msg: Temporalio::Api::NexusOperation::V1::CallbackInfo, kw: T.untyped).returns(String) }
  def self.encode_json(msg, **kw)
  end

  sig { returns(::Google::Protobuf::Descriptor) }
  def self.descriptor
  end
end

# When StartNexusOperationExecutionRequest uses the conflict policy NEXUS_OPERATION_ID_CONFLICT_POLICY_USE_EXISTING
# and there is already an existing, running standalone Nexus operation, OnConflictOptions defines actions to be
# taken.
class Temporalio::Api::NexusOperation::V1::OnConflictOptions
  include ::Google::Protobuf::MessageExts
  extend ::Google::Protobuf::MessageExts::ClassMethods

  sig do
    params(
      attach_request_id: T.nilable(T::Boolean),
      attach_completion_callbacks: T.nilable(T::Boolean),
      attach_links: T.nilable(T::Boolean)
    ).void
  end
  def initialize(
    attach_request_id: false,
    attach_completion_callbacks: false,
    attach_links: false
  )
  end

  # Attaches the request ID to the running operation.
  sig { returns(T::Boolean) }
  def attach_request_id
  end

  # Attaches the request ID to the running operation.
  sig { params(value: T::Boolean).void }
  def attach_request_id=(value)
  end

  # Attaches the request ID to the running operation.
  sig { void }
  def clear_attach_request_id
  end

  # Attaches the completion callbacks to the running operation.
  sig { returns(T::Boolean) }
  def attach_completion_callbacks
  end

  # Attaches the completion callbacks to the running operation.
  sig { params(value: T::Boolean).void }
  def attach_completion_callbacks=(value)
  end

  # Attaches the completion callbacks to the running operation.
  sig { void }
  def clear_attach_completion_callbacks
  end

  # Attaches any new links to the running operation.
  sig { returns(T::Boolean) }
  def attach_links
  end

  # Attaches any new links to the running operation.
  sig { params(value: T::Boolean).void }
  def attach_links=(value)
  end

  # Attaches any new links to the running operation.
  sig { void }
  def clear_attach_links
  end

  sig { params(field: String).returns(T.untyped) }
  def [](field)
  end

  sig { params(field: String, value: T.untyped).void }
  def []=(field, value)
  end

  sig { returns(T::Hash[Symbol, T.untyped]) }
  def to_h
  end

  sig { params(str: String).returns(Temporalio::Api::NexusOperation::V1::OnConflictOptions) }
  def self.decode(str)
  end

  sig { params(msg: Temporalio::Api::NexusOperation::V1::OnConflictOptions).returns(String) }
  def self.encode(msg)
  end

  sig { params(str: String, kw: T.untyped).returns(Temporalio::Api::NexusOperation::V1::OnConflictOptions) }
  def self.decode_json(str, **kw)
  end

  sig { params(msg: Temporalio::Api::NexusOperation::V1::OnConflictOptions, kw: T.untyped).returns(String) }
  def self.encode_json(msg, **kw)
  end

  sig { returns(::Google::Protobuf::Descriptor) }
  def self.descriptor
  end
end

# Trigger for when the Nexus operation is completed, covering both success cases as
# well as any type of failure.
class Temporalio::Api::NexusOperation::V1::CallbackInfo::OperationCompleted
  include ::Google::Protobuf::MessageExts
  extend ::Google::Protobuf::MessageExts::ClassMethods

  sig {void}
  def initialize; end

  sig { params(field: String).returns(T.untyped) }
  def [](field)
  end

  sig { params(field: String, value: T.untyped).void }
  def []=(field, value)
  end

  sig { returns(T::Hash[Symbol, T.untyped]) }
  def to_h
  end

  sig { params(str: String).returns(Temporalio::Api::NexusOperation::V1::CallbackInfo::OperationCompleted) }
  def self.decode(str)
  end

  sig { params(msg: Temporalio::Api::NexusOperation::V1::CallbackInfo::OperationCompleted).returns(String) }
  def self.encode(msg)
  end

  sig { params(str: String, kw: T.untyped).returns(Temporalio::Api::NexusOperation::V1::CallbackInfo::OperationCompleted) }
  def self.decode_json(str, **kw)
  end

  sig { params(msg: Temporalio::Api::NexusOperation::V1::CallbackInfo::OperationCompleted, kw: T.untyped).returns(String) }
  def self.encode_json(msg, **kw)
  end

  sig { returns(::Google::Protobuf::Descriptor) }
  def self.descriptor
  end
end

class Temporalio::Api::NexusOperation::V1::CallbackInfo::Trigger
  include ::Google::Protobuf::MessageExts
  extend ::Google::Protobuf::MessageExts::ClassMethods

  sig do
    params(
      operation_completed: T.nilable(Temporalio::Api::NexusOperation::V1::CallbackInfo::OperationCompleted)
    ).void
  end
  def initialize(
    operation_completed: nil
  )
  end

  sig { returns(T.nilable(Temporalio::Api::NexusOperation::V1::CallbackInfo::OperationCompleted)) }
  def operation_completed
  end

  sig { params(value: T.nilable(Temporalio::Api::NexusOperation::V1::CallbackInfo::OperationCompleted)).void }
  def operation_completed=(value)
  end

  sig { void }
  def clear_operation_completed
  end

  sig { returns(T.nilable(Symbol)) }
  def variant
  end

  sig { params(field: String).returns(T.untyped) }
  def [](field)
  end

  sig { params(field: String, value: T.untyped).void }
  def []=(field, value)
  end

  sig { returns(T::Hash[Symbol, T.untyped]) }
  def to_h
  end

  sig { params(str: String).returns(Temporalio::Api::NexusOperation::V1::CallbackInfo::Trigger) }
  def self.decode(str)
  end

  sig { params(msg: Temporalio::Api::NexusOperation::V1::CallbackInfo::Trigger).returns(String) }
  def self.encode(msg)
  end

  sig { params(str: String, kw: T.untyped).returns(Temporalio::Api::NexusOperation::V1::CallbackInfo::Trigger) }
  def self.decode_json(str, **kw)
  end

  sig { params(msg: Temporalio::Api::NexusOperation::V1::CallbackInfo::Trigger, kw: T.untyped).returns(String) }
  def self.encode_json(msg, **kw)
  end

  sig { returns(::Google::Protobuf::Descriptor) }
  def self.descriptor
  end
end
