module Temporalio
  module Internal
    module Worker
      class ActivityWorker
        attr_reader worker: Temporalio::Worker
        attr_reader bridge_worker: Bridge::Worker

        def initialize: (
          worker: Temporalio::Worker,
          bridge_worker: Bridge::Worker,
        ) -> void

        def set_running_activity: (String task_token, RunningActivity? activity) -> void
        def get_running_activity: (String task_token) -> RunningActivity?
        def remove_running_activity: (String task_token) -> void
        def wait_all_complete: -> void

        def handle_task: (untyped task) -> void
        def handle_start_task: (String task_token, untyped start) -> void
        def handle_cancel_task: (String task_token, untyped cancel) -> void

        def execute_activity: (String task_token, Activity::Definition::Info defn, untyped start) -> void
        def run_activity: (
          Activity::Definition::Info defn,
          RunningActivity activity,
          Temporalio::Worker::Interceptor::Activity::ExecuteInput input
        ) -> void

        class RunningActivity < Activity::Context
          attr_accessor instance: Activity::Definition?
          attr_accessor _outbound_impl: Temporalio::Worker::Interceptor::Activity::Outbound?
          attr_accessor _server_requested_cancel: bool

          def initialize: (
            info: Activity::Info,
            cancellation: Cancellation,
            worker_shutdown_cancellation: Cancellation,
            payload_converter: Converters::PayloadConverter,
            logger: ScopedLogger,
            runtime_metric_meter: Metric::Meter
          ) -> void
        end

        class InboundImplementation < Temporalio::Worker::Interceptor::Activity::Inbound
          def initialize: (ActivityWorker worker) -> void
        end

        class OutboundImplementation < Temporalio::Worker::Interceptor::Activity::Outbound
          def initialize: (ActivityWorker worker) -> void
        end
      end
    end
  end
end