module Temporalio
  module Internal
    module Worker
      class WorkflowWorker
        def self.workflow_definitions: (
          Array[singleton(Workflow::Definition) | Workflow::Definition::Info] workflows
        ) -> Hash[String?, Workflow::Definition::Info]

        def self.bridge_workflow_failure_exception_type_options: (
          workflow_failure_exception_types: Array[singleton(Exception)],
          workflow_definitions: Hash[String?, Workflow::Definition::Info]
        ) -> [bool, Array[String]]

        def initialize: (
          bridge_worker: Bridge::Worker,
          namespace: String,
          task_queue: String,
          workflow_definitions: Hash[String?, Workflow::Definition::Info],
          workflow_executor: Temporalio::Worker::WorkflowExecutor,
          logger: Logger,
          data_converter: Converters::DataConverter,
          metric_meter: Temporalio::Metric::Meter,
          workflow_interceptors: Array[Temporalio::Worker::Interceptor::Workflow],
          disable_eager_activity_execution: bool,
          illegal_workflow_calls: Hash[String, :all | Array[Symbol]],
          workflow_failure_exception_types: Array[singleton(Exception)],
          workflow_payload_codec_thread_pool: Temporalio::Worker::ThreadPool?,
          unsafe_workflow_io_enabled: bool,
          debug_mode: bool,
          ?on_eviction: (^(String run_id, untyped cache_remove_job) -> void)?,
          assert_valid_local_activity: ^(String) -> void
        ) -> void

        def handle_activation: (
          runner: MultiRunner,
          activation: untyped,
          decoded: bool
        ) -> void

        def handle_activation_complete: (
          runner: MultiRunner,
          activation_completion: untyped,
          encoded: bool,
          completion_complete_queue: Queue
        ) -> void

        def on_shutdown_complete: -> void

        def decode_activation: (MultiRunner runner, untyped activation) -> void
        def encode_activation_completion: (MultiRunner runner, untyped activation_completion) -> void
        def apply_codec_on_payload_visit: (untyped payload_or_payloads) { (untyped) -> Enumerable[untyped] } -> void

        class State
          attr_reader workflow_definitions: Hash[String?, Workflow::Definition::Info]
          attr_reader bridge_worker: Bridge::Worker
          attr_reader logger: Logger
          attr_reader metric_meter: Temporalio::Metric::Meter
          attr_reader data_converter: Converters::DataConverter
          attr_reader deadlock_timeout: Float?
          attr_reader illegal_calls: Hash[String, :all | Hash[Symbol, bool]]
          attr_reader namespace: String
          attr_reader task_queue: String
          attr_reader disable_eager_activity_execution: bool
          attr_reader workflow_interceptors: Array[Temporalio::Worker::Interceptor::Workflow]
          attr_reader workflow_failure_exception_types: Array[singleton(Exception)]
          attr_reader unsafe_workflow_io_enabled: bool
          attr_reader assert_valid_local_activity: ^(String) -> void

          attr_writer on_eviction: ^(String run_id, untyped cache_remove_job) -> void

          def initialize: (
            workflow_definitions: Hash[String?, Workflow::Definition::Info],
            bridge_worker: Bridge::Worker,
            logger: Logger,
            metric_meter: Temporalio::Metric::Meter,
            data_converter: Converters::DataConverter,
            deadlock_timeout: Float?,
            illegal_calls: Hash[String, :all | Hash[Symbol, bool]],
            namespace: String,
            task_queue: String,
            disable_eager_activity_execution: bool,
            workflow_interceptors: Array[Temporalio::Worker::Interceptor::Workflow],
            workflow_failure_exception_types: Array[singleton(Exception)],
            unsafe_workflow_io_enabled: bool,
            assert_valid_local_activity: ^(String) -> void
          ) -> void

          def get_or_create_running_workflow: [T] (String run_id) { -> T } -> T
          def evict_running_workflow: (String run_id, untyped cache_remove_job) -> void
          def evict_all: -> void
        end
      end
    end
  end
end