module Temporalio
  class Worker
    class ActivityExecutor
      def self.defaults: -> Hash[Symbol, ActivityExecutor]

      def initialize_activity: (Activity::Definition::Info defn) -> void
      def execute_activity: (Activity::Definition::Info defn) { -> void } -> void
      def activity_context: -> Activity::Context?
      def set_activity_context: (Activity::Definition::Info defn, Activity::Context? context) -> void
    end
  end
end