module Temporalio
  class Worker
    module Interceptor
      module Activity
        def intercept_activity: (Inbound next_interceptor) -> Inbound

        class ExecuteInput
          attr_reader proc: Proc
          attr_reader args: Array[Object?]
          attr_reader headers: Hash[String, Object?]

          def initialize: (
            proc: Proc,
            args: Array[Object?],
            headers: Hash[String, Object?]
          ) -> void
        end

        class Inbound
          attr_reader next_interceptor: Inbound

          def initialize: (Inbound next_interceptor) -> void

          def init: (Outbound outbound) -> Outbound

          def execute: (ExecuteInput input) -> Object?
        end

        class HeartbeatInput
          attr_reader details: Array[Object?]

          def initialize: (details: Array[Object?]) -> void
        end

        class Outbound
          attr_reader next_interceptor: Outbound

          def initialize: (Outbound next_interceptor) -> void

          def heartbeat: (HeartbeatInput input) -> void
        end
      end

      module Workflow
        def intercept_workflow: (Inbound next_interceptor) -> Inbound

        class ExecuteInput
          attr_reader args: Array[Object?]
          attr_reader headers: Hash[String, Object?]

          def initialize: (
            args: Array[Object?],
            headers: Hash[String, Object?]
          ) -> void
        end

        class HandleSignalInput
          attr_reader signal: String
          attr_reader args: Array[Object?]
          attr_reader definition: Temporalio::Workflow::Definition::Signal
          attr_reader headers: Hash[String, Object?]

          def initialize: (
            signal: String,
            args: Array[Object?],
            definition: Temporalio::Workflow::Definition::Signal,
            headers: Hash[String, Object?]
          ) -> void
        end

        class HandleQueryInput
          attr_reader id: String
          attr_reader query: String
          attr_reader args: Array[Object?]
          attr_reader definition: Temporalio::Workflow::Definition::Query
          attr_reader headers: Hash[String, Object?]

          def initialize: (
            id: String,
            query: String,
            args: Array[Object?],
            definition: Temporalio::Workflow::Definition::Query,
            headers: Hash[String, Object?]
          ) -> void
        end

        class HandleUpdateInput
          attr_reader id: String
          attr_reader update: String
          attr_reader args: Array[Object?]
          attr_reader definition: Temporalio::Workflow::Definition::Update
          attr_reader headers: Hash[String, Object?]

          def initialize: (
            id: String,
            update: String,
            args: Array[Object?],
            definition: Temporalio::Workflow::Definition::Update,
            headers: Hash[String, Object?]
          ) -> void
        end

        class Inbound
          attr_reader next_interceptor: Inbound

          def initialize: (Inbound next_interceptor) -> void

          def init: (Outbound outbound) -> Outbound

          def execute: (ExecuteInput input) -> Object?

          def handle_signal: (HandleSignalInput input) -> void

          def handle_query: (HandleQueryInput input) -> Object?

          def validate_update: (HandleUpdateInput input) -> void

          def handle_update: (HandleUpdateInput input) -> Object?
        end

        class CancelExternalWorkflowInput
          attr_reader id: String
          attr_reader run_id: String?

          def initialize: (
            id: String,
            run_id: String?
          ) -> void
        end

        class ExecuteActivityInput
          attr_reader activity: String
          attr_reader args: Array[Object?]
          attr_reader task_queue: String
          attr_reader summary: String?
          attr_reader schedule_to_close_timeout: duration?
          attr_reader schedule_to_start_timeout: duration?
          attr_reader start_to_close_timeout: duration?
          attr_reader heartbeat_timeout: duration?
          attr_reader retry_policy: RetryPolicy?
          attr_reader cancellation: Cancellation
          attr_reader cancellation_type: Temporalio::Workflow::ActivityCancellationType::enum
          attr_reader activity_id: String?
          attr_reader disable_eager_execution: bool
          attr_reader headers: Hash[String, Object?]
          attr_reader priority: Temporalio::Priority

          def initialize: (
            activity: String,
            args: Array[Object?],
            task_queue: String,
            summary: String?,
            schedule_to_close_timeout: duration?,
            schedule_to_start_timeout: duration?,
            start_to_close_timeout: duration?,
            heartbeat_timeout: duration?,
            retry_policy: RetryPolicy?,
            cancellation: Cancellation,
            cancellation_type: Temporalio::Workflow::ActivityCancellationType::enum,
            activity_id: String?,
            disable_eager_execution: bool,
            headers: Hash[String, Object?],
            priority: Temporalio::Priority
          ) -> void
        end

        class ExecuteLocalActivityInput
          attr_reader activity: String
          attr_reader args: Array[Object?]
          attr_reader schedule_to_close_timeout: duration?
          attr_reader schedule_to_start_timeout: duration?
          attr_reader start_to_close_timeout: duration?
          attr_reader retry_policy: RetryPolicy?
          attr_reader local_retry_threshold: duration?
          attr_reader cancellation: Cancellation
          attr_reader cancellation_type: Temporalio::Workflow::ActivityCancellationType::enum
          attr_reader activity_id: String?
          attr_reader headers: Hash[String, Object?]

          def initialize: (
            activity: String,
            args: Array[Object?],
            schedule_to_close_timeout: duration?,
            schedule_to_start_timeout: duration?,
            start_to_close_timeout: duration?,
            retry_policy: RetryPolicy?,
            local_retry_threshold: duration?,
            cancellation: Cancellation,
            cancellation_type: Temporalio::Workflow::ActivityCancellationType::enum,
            activity_id: String?,
            headers: Hash[String, Object?]
          ) -> void
        end

        class InitializeContinueAsNewErrorInput
          attr_reader error: Temporalio::Workflow::ContinueAsNewError

          def initialize: (
            error: Temporalio::Workflow::ContinueAsNewError
          ) -> void
        end

        class SignalChildWorkflowInput
          attr_reader id: String
          attr_reader signal: String
          attr_reader args: Array[Object?]
          attr_reader cancellation: Cancellation
          attr_reader headers: Hash[String, Object?]

          def initialize: (
            id: String,
            signal: String,
            args: Array[Object?],
            cancellation: Cancellation,
            headers: Hash[String, Object?]
          ) -> void
        end

        class SignalExternalWorkflowInput
          attr_reader id: String
          attr_reader run_id: String?
          attr_reader signal: String
          attr_reader args: Array[Object?]
          attr_reader cancellation: Cancellation
          attr_reader headers: Hash[String, Object?]

          def initialize: (
            id: String,
            run_id: String?,
            signal: String,
            args: Array[Object?],
            cancellation: Cancellation,
            headers: Hash[String, Object?]
          ) -> void
        end

        class SleepInput
          attr_reader duration: duration?
          attr_reader summary: String?
          attr_reader cancellation: Cancellation

          def initialize: (
            duration: duration?,
            summary: String?,
            cancellation: Cancellation
          ) -> void
        end

        class StartChildWorkflowInput
          attr_reader workflow: String
          attr_reader args: Array[Object?]
          attr_reader id: String
          attr_reader task_queue: String
          attr_reader static_summary: String?
          attr_reader static_details: String?
          attr_reader cancellation: Cancellation
          attr_reader cancellation_type: Temporalio::Workflow::ChildWorkflowCancellationType::enum
          attr_reader parent_close_policy: Temporalio::Workflow::ParentClosePolicy::enum
          attr_reader execution_timeout: duration?
          attr_reader run_timeout: duration?
          attr_reader task_timeout: duration?
          attr_reader id_reuse_policy: WorkflowIDReusePolicy::enum
          attr_reader retry_policy: RetryPolicy?
          attr_reader cron_schedule: String?
          attr_reader memo: Hash[String | Symbol, Object?]?
          attr_reader search_attributes: SearchAttributes?
          attr_reader headers: Hash[String, Object?]
          attr_reader priority: Temporalio::Priority

          def initialize: (
            workflow: String,
            args: Array[Object?],
            id: String,
            task_queue: String,
            static_summary: String?,
            static_details: String?,
            cancellation: Cancellation,
            cancellation_type: Temporalio::Workflow::ChildWorkflowCancellationType::enum,
            parent_close_policy: Temporalio::Workflow::ParentClosePolicy::enum,
            execution_timeout: duration?,
            run_timeout: duration?,
            task_timeout: duration?,
            id_reuse_policy: WorkflowIDReusePolicy::enum,
            retry_policy: RetryPolicy?,
            cron_schedule: String?,
            memo: Hash[String | Symbol, Object?]?,
            search_attributes: SearchAttributes?,
            headers: Hash[String, Object?],
            priority: Temporalio::Priority
          ) -> void
        end

        class Outbound
          attr_reader next_interceptor: Outbound

          def initialize: (Outbound next_interceptor) -> void

          def cancel_external_workflow: (CancelExternalWorkflowInput input) -> void

          def execute_activity: (ExecuteActivityInput input) -> Object?

          def execute_local_activity: (ExecuteLocalActivityInput input) -> Object?

          def initialize_continue_as_new_error: (InitializeContinueAsNewErrorInput input) -> void

          def signal_child_workflow: (SignalChildWorkflowInput input) -> void

          def signal_external_workflow: (SignalExternalWorkflowInput input) -> void

          def sleep: (SleepInput input) -> void

          def start_child_workflow: (StartChildWorkflowInput input) -> Temporalio::Workflow::ChildWorkflowHandle
        end
      end
    end
  end
end
