module Temporalio
  module Activity
    class Info
      attr_reader activity_id: String
      attr_reader activity_type: String
      attr_reader attempt: Integer
      attr_reader current_attempt_scheduled_time: Time
      attr_reader heartbeat_details: Array[Object?]
      attr_reader heartbeat_timeout: Float?
      attr_reader local?: bool
      attr_reader priority: Temporalio::Priority?
      attr_reader schedule_to_close_timeout: Float?
      attr_reader scheduled_time: Time
      attr_reader start_to_close_timeout: Float?
      attr_reader started_time: Time
      attr_reader task_queue: String
      attr_reader task_token: String
      attr_reader workflow_id: String
      attr_reader workflow_namespace: String
      attr_reader workflow_run_id: String
      attr_reader workflow_type: String

      def initialize: (
        activity_id: String,
        activity_type: String,
        attempt: Integer,
        current_attempt_scheduled_time: Time,
        heartbeat_details: Array[Object?],
        heartbeat_timeout: Float?,
        local?: bool,
        priority: Temporalio::Priority?,
        schedule_to_close_timeout: Float?,
        scheduled_time: Time,
        start_to_close_timeout: Float?,
        started_time: Time,
        task_queue: String,
        task_token: String,
        workflow_id: String,
        workflow_namespace: String,
        workflow_run_id: String,
        workflow_type: String
      ) -> void

      def with: (**untyped) -> Info
    end
  end
end