module Temporalio
  module Api
    module OperatorService
      module V1
        # OperatorService API defines how Temporal SDKs and other clients interact with the Temporal server
        #  to perform administrative functions like registering a search attribute or a namespace.
        #  APIs in this file could be not compatible with Temporal Cloud, hence it's usage in SDKs should be limited by
        #  designated APIs that clearly state that they shouldn't be used by the main Application (Workflows & Activities) framework.
        #
        # (-- Search Attribute --)
        #
        class OperatorService < ::Protobuf::Rpc::Service
        end
      end
    end
  end
end
