module Workflow
  class DefinitionTest < TestBase
    class ValidWorkflowAdvancedBase < Temporalio::Workflow::Definition
    end

    def assert_invalid_workflow_code: (
      String message_contains,
      String code_to_eval
    ) -> void
  end
end