module Temporalio
  class Client
    class Implementation
      def initialize: (
        Temporalio::Connection connection,
        Symbol | String namespace,
        Temporalio::DataConverter converter,
        Array[Temporalio::Interceptor::Client::_Interface] interceptors
      ) -> void

      def start_workflow: (Temporalio::Interceptor::Client::StartWorkflowInput input) -> Temporalio::Client::WorkflowHandle
      def describe_workflow: (Temporalio::Interceptor::Client::DescribeWorkflowInput input) -> Temporalio::Workflow::ExecutionInfo
      def query_workflow: (Temporalio::Interceptor::Client::QueryWorkflowInput input) -> untyped
      def signal_workflow: (Temporalio::Interceptor::Client::SignalWorkflowInput input) -> void
      def cancel_workflow: (Temporalio::Interceptor::Client::CancelWorkflowInput input) -> void
      def terminate_workflow: (Temporalio::Interceptor::Client::TerminateWorkflowInput input) -> void
      def await_workflow_result: (String id, String? run_id, bool follow_runs, Hash[String, String] rpc_metadata, Integer? rpc_timeout) -> untyped

      private

      attr_reader connection: Temporalio::Connection
      attr_reader namespace: Symbol | String
      attr_reader converter: Temporalio::DataConverter
      attr_reader interceptor_chain: Interceptor::Chain
      attr_reader identity: String

      def convert_headers: (Hash[Symbol | String, untyped]) -> Temporalio::Api::Common::V1::Header?
      def handle_start_workflow: (Temporalio::Interceptor::Client::StartWorkflowInput input) -> Temporalio::Client::WorkflowHandle
      def handle_describe_workflow: (Temporalio::Interceptor::Client::DescribeWorkflowInput input) -> Temporalio::Workflow::ExecutionInfo
      def handle_query_workflow: (Temporalio::Interceptor::Client::QueryWorkflowInput input) -> nil
      def handle_signal_workflow: (Temporalio::Interceptor::Client::SignalWorkflowInput input) -> nil
      def handle_cancel_workflow: (Temporalio::Interceptor::Client::CancelWorkflowInput input) -> nil
      def handle_terminate_workflow: (Temporalio::Interceptor::Client::TerminateWorkflowInput input) -> nil
      def process_workflow_result_from: (Temporalio::Api::WorkflowService::V1::GetWorkflowExecutionHistoryResponse response, bool follow_runs) -> untyped
      def follow: (String?) -> void
    end
  end
end
