module Temporalio
  class Activity
    class Context
      def initialize: (
        Temporalio::Activity::Info info,
        ^(*untyped) -> void,
        Temporalio::Interceptor::Chain[Temporalio::Interceptor::ActivityOutbound],
        ?shielded: bool
      ) -> void
      def time: -> Time
      def info: -> Temporalio::Activity::Info
      def heartbeat: (*untyped details) -> void
      def shield: { -> untyped } -> untyped
      def cancelled?: -> bool
      def cancel: (String reason, ?by_request: bool) -> void

      private

      @info: Temporalio::Activity::Info
      @heartbeat_proc: ^(*untyped) -> void
      @shielded: bool
      @pending_cancellation: Exception?

      attr_reader thread: Thread
      attr_reader interceptors: Temporalio::Interceptor::Chain[Temporalio::Interceptor::ActivityOutbound]
      attr_reader mutex: Thread::Mutex
    end
  end
end
