module Temporalio
  class Worker
    class ActivityExecutor
      class ThreadPool < ActivityExecutor
        def self.default: -> ThreadPool

        def initialize: (?ThreadPool thread_poll) -> void
      end
    end
  end
end