module Temporalio
  class Worker
    class ActivityExecutor
      class ThreadPool < ActivityExecutor
        def self.default: -> ThreadPool

        def initialize: (?::Temporalio::Worker::ThreadPool thread_pool) -> void
      end
    end
  end
end