module Temporal
  class Worker
    class ActivityTaskProcessor
      def initialize: (Coresdk::ActivityTask::Start task) -> void
      def process: -> untyped

      private

      attr_reader task: Coresdk::ActivityTask::Start
    end
  end
end
