module Temporal
  class Worker
    class ActivityRunner
      def initialize: (
        singleton(Temporal::Activity) activity_class,
        Coresdk::ActivityTask::Start task,
        String task_queue,
        String task_token,
        Temporal::DataConverter converter
      ) -> void
      def run: -> (Temporal::Api::Common::V1::Payload | Temporal::Api::Failure::V1::Failure)
      def cancel: -> void

      private

      attr_reader activity_class: singleton(Temporal::Activity)
      attr_reader task: Coresdk::ActivityTask::Start
      attr_reader task_queue: String
      attr_reader task_token: String
      attr_reader converter: Temporal::DataConverter

      def generate_activity_info: -> Temporal::Activity::Info
    end
  end
end
