module Temporal
  class Worker
    class Reactor
      module Command
        class Start < Struct[untyped]
          attr_accessor block: ^(*untyped) -> void

          def self.new: (^(*untyped) -> void) -> instance
        end

        class Resume < Struct[untyped]
          attr_accessor fiber: Fiber
          attr_accessor value: untyped

          def self.new: (Fiber, untyped) -> instance
        end
      end
    end
  end
end
