# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/enums/v1/time_skipping.proto

require 'google/protobuf'


descriptor_data = "\n)temporal/api/enums/v1/time_skipping.proto\x12\x15temporal.api.enums.v1*\xe2\x01\n\x18\x46\x61stForwardPollingResult\x12+\n\'FAST_FORWARD_POLLING_RESULT_UNSPECIFIED\x10\x00\x12,\n(FAST_FORWARD_POLLING_RESULT_POLL_TIMEOUT\x10\x01\x12\x36\n2FAST_FORWARD_POLLING_RESULT_FAST_FORWARD_COMPLETED\x10\x02\x12\x33\n/FAST_FORWARD_POLLING_RESULT_FAST_FORWARD_FAILED\x10\x03\x42\x89\x01\n\x18io.temporal.api.enums.v1B\x11TimeSkippingProtoP\x01Z!go.temporal.io/api/enums/v1;enums\xaa\x02\x17Temporalio.Api.Enums.V1\xea\x02\x1aTemporalio::Api::Enums::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Temporalio
  module Api
    module Enums
      module V1
        FastForwardPollingResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("temporal.api.enums.v1.FastForwardPollingResult").enummodule
      end
    end
  end
end
