module Gogoproto
end

class ::Google::Protobuf::EnumOptions
  attr_accessor goproto_enum_prefix(): bool

  def goproto_enum_prefix!: () -> bool?

  def []: (:goproto_enum_prefix) -> bool
        | ...

  def []=: (:goproto_enum_prefix, bool) -> bool
         | ...
end

class ::Google::Protobuf::EnumOptions
  attr_accessor goproto_enum_stringer(): bool

  def goproto_enum_stringer!: () -> bool?

  def []: (:goproto_enum_stringer) -> bool
        | ...

  def []=: (:goproto_enum_stringer, bool) -> bool
         | ...
end

class ::Google::Protobuf::EnumOptions
  attr_accessor enum_stringer(): bool

  def enum_stringer!: () -> bool?

  def []: (:enum_stringer) -> bool
        | ...

  def []=: (:enum_stringer, bool) -> bool
         | ...
end

class ::Google::Protobuf::EnumOptions
  attr_accessor enum_customname(): ::String

  def enum_customname!: () -> ::String?

  def []: (:enum_customname) -> ::String
        | ...

  def []=: (:enum_customname, ::String) -> ::String
         | ...
end

class ::Google::Protobuf::EnumOptions
  attr_accessor enumdecl(): bool

  def enumdecl!: () -> bool?

  def []: (:enumdecl) -> bool
        | ...

  def []=: (:enumdecl, bool) -> bool
         | ...
end

class ::Google::Protobuf::EnumValueOptions
  attr_accessor enumvalue_customname(): ::String

  def enumvalue_customname!: () -> ::String?

  def []: (:enumvalue_customname) -> ::String
        | ...

  def []=: (:enumvalue_customname, ::String) -> ::String
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor goproto_getters_all(): bool

  def goproto_getters_all!: () -> bool?

  def []: (:goproto_getters_all) -> bool
        | ...

  def []=: (:goproto_getters_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor goproto_enum_prefix_all(): bool

  def goproto_enum_prefix_all!: () -> bool?

  def []: (:goproto_enum_prefix_all) -> bool
        | ...

  def []=: (:goproto_enum_prefix_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor goproto_stringer_all(): bool

  def goproto_stringer_all!: () -> bool?

  def []: (:goproto_stringer_all) -> bool
        | ...

  def []=: (:goproto_stringer_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor verbose_equal_all(): bool

  def verbose_equal_all!: () -> bool?

  def []: (:verbose_equal_all) -> bool
        | ...

  def []=: (:verbose_equal_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor face_all(): bool

  def face_all!: () -> bool?

  def []: (:face_all) -> bool
        | ...

  def []=: (:face_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor gostring_all(): bool

  def gostring_all!: () -> bool?

  def []: (:gostring_all) -> bool
        | ...

  def []=: (:gostring_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor populate_all(): bool

  def populate_all!: () -> bool?

  def []: (:populate_all) -> bool
        | ...

  def []=: (:populate_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor stringer_all(): bool

  def stringer_all!: () -> bool?

  def []: (:stringer_all) -> bool
        | ...

  def []=: (:stringer_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor onlyone_all(): bool

  def onlyone_all!: () -> bool?

  def []: (:onlyone_all) -> bool
        | ...

  def []=: (:onlyone_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor equal_all(): bool

  def equal_all!: () -> bool?

  def []: (:equal_all) -> bool
        | ...

  def []=: (:equal_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor description_all(): bool

  def description_all!: () -> bool?

  def []: (:description_all) -> bool
        | ...

  def []=: (:description_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor testgen_all(): bool

  def testgen_all!: () -> bool?

  def []: (:testgen_all) -> bool
        | ...

  def []=: (:testgen_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor benchgen_all(): bool

  def benchgen_all!: () -> bool?

  def []: (:benchgen_all) -> bool
        | ...

  def []=: (:benchgen_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor marshaler_all(): bool

  def marshaler_all!: () -> bool?

  def []: (:marshaler_all) -> bool
        | ...

  def []=: (:marshaler_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor unmarshaler_all(): bool

  def unmarshaler_all!: () -> bool?

  def []: (:unmarshaler_all) -> bool
        | ...

  def []=: (:unmarshaler_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor stable_marshaler_all(): bool

  def stable_marshaler_all!: () -> bool?

  def []: (:stable_marshaler_all) -> bool
        | ...

  def []=: (:stable_marshaler_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor sizer_all(): bool

  def sizer_all!: () -> bool?

  def []: (:sizer_all) -> bool
        | ...

  def []=: (:sizer_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor goproto_enum_stringer_all(): bool

  def goproto_enum_stringer_all!: () -> bool?

  def []: (:goproto_enum_stringer_all) -> bool
        | ...

  def []=: (:goproto_enum_stringer_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor enum_stringer_all(): bool

  def enum_stringer_all!: () -> bool?

  def []: (:enum_stringer_all) -> bool
        | ...

  def []=: (:enum_stringer_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor unsafe_marshaler_all(): bool

  def unsafe_marshaler_all!: () -> bool?

  def []: (:unsafe_marshaler_all) -> bool
        | ...

  def []=: (:unsafe_marshaler_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor unsafe_unmarshaler_all(): bool

  def unsafe_unmarshaler_all!: () -> bool?

  def []: (:unsafe_unmarshaler_all) -> bool
        | ...

  def []=: (:unsafe_unmarshaler_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor goproto_extensions_map_all(): bool

  def goproto_extensions_map_all!: () -> bool?

  def []: (:goproto_extensions_map_all) -> bool
        | ...

  def []=: (:goproto_extensions_map_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor goproto_unrecognized_all(): bool

  def goproto_unrecognized_all!: () -> bool?

  def []: (:goproto_unrecognized_all) -> bool
        | ...

  def []=: (:goproto_unrecognized_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor gogoproto_import(): bool

  def gogoproto_import!: () -> bool?

  def []: (:gogoproto_import) -> bool
        | ...

  def []=: (:gogoproto_import, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor protosizer_all(): bool

  def protosizer_all!: () -> bool?

  def []: (:protosizer_all) -> bool
        | ...

  def []=: (:protosizer_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor compare_all(): bool

  def compare_all!: () -> bool?

  def []: (:compare_all) -> bool
        | ...

  def []=: (:compare_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor typedecl_all(): bool

  def typedecl_all!: () -> bool?

  def []: (:typedecl_all) -> bool
        | ...

  def []=: (:typedecl_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor enumdecl_all(): bool

  def enumdecl_all!: () -> bool?

  def []: (:enumdecl_all) -> bool
        | ...

  def []=: (:enumdecl_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor goproto_registration(): bool

  def goproto_registration!: () -> bool?

  def []: (:goproto_registration) -> bool
        | ...

  def []=: (:goproto_registration, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor messagename_all(): bool

  def messagename_all!: () -> bool?

  def []: (:messagename_all) -> bool
        | ...

  def []=: (:messagename_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor goproto_sizecache_all(): bool

  def goproto_sizecache_all!: () -> bool?

  def []: (:goproto_sizecache_all) -> bool
        | ...

  def []=: (:goproto_sizecache_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::FileOptions
  attr_accessor goproto_unkeyed_all(): bool

  def goproto_unkeyed_all!: () -> bool?

  def []: (:goproto_unkeyed_all) -> bool
        | ...

  def []=: (:goproto_unkeyed_all, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor goproto_getters(): bool

  def goproto_getters!: () -> bool?

  def []: (:goproto_getters) -> bool
        | ...

  def []=: (:goproto_getters, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor goproto_stringer(): bool

  def goproto_stringer!: () -> bool?

  def []: (:goproto_stringer) -> bool
        | ...

  def []=: (:goproto_stringer, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor verbose_equal(): bool

  def verbose_equal!: () -> bool?

  def []: (:verbose_equal) -> bool
        | ...

  def []=: (:verbose_equal, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor face(): bool

  def face!: () -> bool?

  def []: (:face) -> bool
        | ...

  def []=: (:face, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor gostring(): bool

  def gostring!: () -> bool?

  def []: (:gostring) -> bool
        | ...

  def []=: (:gostring, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor populate(): bool

  def populate!: () -> bool?

  def []: (:populate) -> bool
        | ...

  def []=: (:populate, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor stringer(): bool

  def stringer!: () -> bool?

  def []: (:stringer) -> bool
        | ...

  def []=: (:stringer, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor onlyone(): bool

  def onlyone!: () -> bool?

  def []: (:onlyone) -> bool
        | ...

  def []=: (:onlyone, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor equal(): bool

  def equal!: () -> bool?

  def []: (:equal) -> bool
        | ...

  def []=: (:equal, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor description(): bool

  def description!: () -> bool?

  def []: (:description) -> bool
        | ...

  def []=: (:description, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor testgen(): bool

  def testgen!: () -> bool?

  def []: (:testgen) -> bool
        | ...

  def []=: (:testgen, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor benchgen(): bool

  def benchgen!: () -> bool?

  def []: (:benchgen) -> bool
        | ...

  def []=: (:benchgen, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor marshaler(): bool

  def marshaler!: () -> bool?

  def []: (:marshaler) -> bool
        | ...

  def []=: (:marshaler, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor unmarshaler(): bool

  def unmarshaler!: () -> bool?

  def []: (:unmarshaler) -> bool
        | ...

  def []=: (:unmarshaler, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor stable_marshaler(): bool

  def stable_marshaler!: () -> bool?

  def []: (:stable_marshaler) -> bool
        | ...

  def []=: (:stable_marshaler, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor sizer(): bool

  def sizer!: () -> bool?

  def []: (:sizer) -> bool
        | ...

  def []=: (:sizer, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor unsafe_marshaler(): bool

  def unsafe_marshaler!: () -> bool?

  def []: (:unsafe_marshaler) -> bool
        | ...

  def []=: (:unsafe_marshaler, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor unsafe_unmarshaler(): bool

  def unsafe_unmarshaler!: () -> bool?

  def []: (:unsafe_unmarshaler) -> bool
        | ...

  def []=: (:unsafe_unmarshaler, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor goproto_extensions_map(): bool

  def goproto_extensions_map!: () -> bool?

  def []: (:goproto_extensions_map) -> bool
        | ...

  def []=: (:goproto_extensions_map, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor goproto_unrecognized(): bool

  def goproto_unrecognized!: () -> bool?

  def []: (:goproto_unrecognized) -> bool
        | ...

  def []=: (:goproto_unrecognized, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor protosizer(): bool

  def protosizer!: () -> bool?

  def []: (:protosizer) -> bool
        | ...

  def []=: (:protosizer, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor compare(): bool

  def compare!: () -> bool?

  def []: (:compare) -> bool
        | ...

  def []=: (:compare, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor typedecl(): bool

  def typedecl!: () -> bool?

  def []: (:typedecl) -> bool
        | ...

  def []=: (:typedecl, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor messagename(): bool

  def messagename!: () -> bool?

  def []: (:messagename) -> bool
        | ...

  def []=: (:messagename, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor goproto_sizecache(): bool

  def goproto_sizecache!: () -> bool?

  def []: (:goproto_sizecache) -> bool
        | ...

  def []=: (:goproto_sizecache, bool) -> bool
         | ...
end

class ::Google::Protobuf::MessageOptions
  attr_accessor goproto_unkeyed(): bool

  def goproto_unkeyed!: () -> bool?

  def []: (:goproto_unkeyed) -> bool
        | ...

  def []=: (:goproto_unkeyed, bool) -> bool
         | ...
end

class ::Google::Protobuf::FieldOptions
  attr_accessor nullable(): bool

  def nullable!: () -> bool?

  def []: (:nullable) -> bool
        | ...

  def []=: (:nullable, bool) -> bool
         | ...
end

class ::Google::Protobuf::FieldOptions
  attr_accessor embed(): bool

  def embed!: () -> bool?

  def []: (:embed) -> bool
        | ...

  def []=: (:embed, bool) -> bool
         | ...
end

class ::Google::Protobuf::FieldOptions
  attr_accessor customtype(): ::String

  def customtype!: () -> ::String?

  def []: (:customtype) -> ::String
        | ...

  def []=: (:customtype, ::String) -> ::String
         | ...
end

class ::Google::Protobuf::FieldOptions
  attr_accessor customname(): ::String

  def customname!: () -> ::String?

  def []: (:customname) -> ::String
        | ...

  def []=: (:customname, ::String) -> ::String
         | ...
end

class ::Google::Protobuf::FieldOptions
  attr_accessor jsontag(): ::String

  def jsontag!: () -> ::String?

  def []: (:jsontag) -> ::String
        | ...

  def []=: (:jsontag, ::String) -> ::String
         | ...
end

class ::Google::Protobuf::FieldOptions
  attr_accessor moretags(): ::String

  def moretags!: () -> ::String?

  def []: (:moretags) -> ::String
        | ...

  def []=: (:moretags, ::String) -> ::String
         | ...
end

class ::Google::Protobuf::FieldOptions
  attr_accessor casttype(): ::String

  def casttype!: () -> ::String?

  def []: (:casttype) -> ::String
        | ...

  def []=: (:casttype, ::String) -> ::String
         | ...
end

class ::Google::Protobuf::FieldOptions
  attr_accessor castkey(): ::String

  def castkey!: () -> ::String?

  def []: (:castkey) -> ::String
        | ...

  def []=: (:castkey, ::String) -> ::String
         | ...
end

class ::Google::Protobuf::FieldOptions
  attr_accessor castvalue(): ::String

  def castvalue!: () -> ::String?

  def []: (:castvalue) -> ::String
        | ...

  def []=: (:castvalue, ::String) -> ::String
         | ...
end

class ::Google::Protobuf::FieldOptions
  attr_accessor stdtime(): bool

  def stdtime!: () -> bool?

  def []: (:stdtime) -> bool
        | ...

  def []=: (:stdtime, bool) -> bool
         | ...
end

class ::Google::Protobuf::FieldOptions
  attr_accessor stdduration(): bool

  def stdduration!: () -> bool?

  def []: (:stdduration) -> bool
        | ...

  def []=: (:stdduration, bool) -> bool
         | ...
end

class ::Google::Protobuf::FieldOptions
  attr_accessor wktpointer(): bool

  def wktpointer!: () -> bool?

  def []: (:wktpointer) -> bool
        | ...

  def []=: (:wktpointer, bool) -> bool
         | ...
end
