class ClientActivityOperatorCommandsTest < Test
  PAUSED_STATES: Array[Integer]

  def assert_eventually_paused: (Temporalio::Client::ActivityHandle handle) -> void

  def with_activity_worker: (Array[singleton(Temporalio::Activity::Definition)] activities) { (String) -> untyped } -> untyped

  def start_running_slow_activity: (String task_queue, **untyped kwargs) -> Temporalio::Client::ActivityHandle

  def start_backed_off_heartbeat_activity: (String task_queue) -> Temporalio::Client::ActivityHandle
end
