class WorkerThreadPoolTest < Test
  class RecordingContext < Temporalio::Worker::ThreadPool::ThreadContext
    attr_reader entered: Queue
    attr_reader exited: Queue
    def initialize: (?var_value: String) -> void
    def call: { -> void } -> void
  end

  class RaisesOnceContext < Temporalio::Worker::ThreadPool::ThreadContext
    attr_reader raised: Queue
    def initialize: -> void
    def call: { -> void } -> void
  end

  class AlwaysRaisesContext < Temporalio::Worker::ThreadPool::ThreadContext
    attr_reader raised: Queue
    def initialize: -> void
    def call: { -> void } -> void
  end

  class RestartingContext < Temporalio::Worker::ThreadPool::ThreadContext
    def initialize: (fail_times: Integer) -> void
    def count: -> Integer
    def call: { -> void } -> void
  end

  def wait_until: (?timeout: Float) { () -> boolish } -> boolish
  def run_and_wait: (Temporalio::Worker::ThreadPool pool, ?timeout: Float) -> void
end
