# Code generated by protoc-gen-rbi. DO NOT EDIT.
# source: temporal/api/enums/v1/time_skipping.proto
# typed: strict

module Temporalio::Api::Enums::V1::FastForwardPollingResult
  self::FAST_FORWARD_POLLING_RESULT_UNSPECIFIED = T.let(0, Integer)
  self::FAST_FORWARD_POLLING_RESULT_POLL_TIMEOUT = T.let(1, Integer)
  self::FAST_FORWARD_POLLING_RESULT_FAST_FORWARD_COMPLETED = T.let(2, Integer)
  self::FAST_FORWARD_POLLING_RESULT_FAST_FORWARD_FAILED = T.let(3, Integer)

  sig { params(value: Integer).returns(T.nilable(Symbol)) }
  def self.lookup(value)
  end

  sig { params(value: Symbol).returns(T.nilable(Integer)) }
  def self.resolve(value)
  end

  sig { returns(::Google::Protobuf::EnumDescriptor) }
  def self.descriptor
  end
end
