module Temporalio
  module Bridge
    class RetryConfig
      attr_reader initial_interval_millis: Integer
      attr_reader randomization_factor: Float
      attr_reader multiplier: Float
      attr_reader max_interval_millis: Integer
      attr_reader max_elapsed_time_millis: Integer?
      attr_reader max_retries: Integer

      def initialize: (
          initial_interval_millis: Integer,
          randomization_factor: Float,
          multiplier: Float,
          max_interval_millis: Integer,
          max_elapsed_time_millis: Integer?,
          max_retries: Integer,
      ) -> void
    end
  end
end
