module Temporal
  class Workflow
    module ExecutionStatus
      type values =
        :RUNNING | :COMPLETED | :FAILED | :CANCELED | :TERMINATED | :CONTINUED_AS_NEW | :TIMED_OUT

      RUNNING: :RUNNING
      COMPLETED: :COMPLETED
      FAILED: :FAILED
      CANCELED: :CANCELED
      TERMINATED: :TERMINATED
      CONTINUED_AS_NEW: :CONTINUED_AS_NEW
      TIMED_OUT: :TIMED_OUT
      STATUSES: Array[values]
      API_MAP: Hash[Temporal::Api::Enums::V1::WorkflowExecutionStatus::init, values]

      def self.to_raw: (values) -> Temporal::Api::Enums::V1::WorkflowExecutionStatus::init
      def self.from_raw: (Temporal::Api::Enums::V1::WorkflowExecutionStatus::init) -> values
    end
  end
end
