module Temporal
  class Workflow
    EXECUTION_INFO_ATTRIBUTES: [:raw, :workflow, :id, :run_id, :task_queue, :status, :parent_id, :parent_run_id, :start_time, :close_time, :execution_time, :history_length, :memo, :search_attributes]

    class ExecutionInfo < Struct[untyped]
      attr_accessor raw(): Temporal::Api::WorkflowService::V1::DescribeWorkflowExecutionResponse
      attr_accessor workflow(): String
      attr_accessor id(): String
      attr_accessor run_id(): String
      attr_accessor task_queue(): String
      attr_accessor status(): Symbol
      attr_accessor parent_id(): String
      attr_accessor parent_run_id(): String
      attr_accessor start_time(): Time
      attr_accessor close_time(): Time
      attr_accessor execution_time(): Time
      attr_accessor history_length(): Integer
      attr_accessor memo(): Hash[Symbol | String, untyped]
      attr_accessor search_attributes(): Hash[Symbol | String, untyped]

      def self.from_raw: (
        Temporal::Api::WorkflowService::V1::DescribeWorkflowExecutionResponse response,
        Temporal::DataConverter converter
      ) -> ExecutionInfo

      def self.new: (
        raw: Temporal::Api::WorkflowService::V1::DescribeWorkflowExecutionResponse,
        workflow: String?,
        id: String?,
        run_id: String?,
        task_queue: String?,
        status: Symbol?,
        parent_id: String?,
        parent_run_id: String?,
        start_time: Time?,
        close_time: Time?,
        execution_time: Time?,
        history_length: Integer?,
        memo: Hash[Symbol | String, untyped]?,
        search_attributes: Hash[Symbol | String, untyped]?
      ) -> ExecutionInfo

      # NOTE: RBS doesn't understand define_method semantics
      def self.status: () -> Symbol

      def running?: -> bool
      def completed?: -> bool
      def failed?: -> bool
      def canceled?: -> bool
      def terminated?: -> bool
      def continued_as_new?: -> bool
      def timed_out?: -> bool
    end
  end
end
