module Temporal
  module Interceptor
    class Chain
      def initialize: (?Array[Temporal::Interceptor::Client] interceptors) -> void
      def invoke: [U, T] (Symbol method, U input) ?{ (U) -> T } -> T

      private

      attr_reader interceptors: Array[Temporal::Interceptor::Client]
    end
  end
end
