module Temporalio
  module Testing
    class TimeSkippingInterceptor
      include Temporalio::Interceptor::Client

      def initialize: (Temporalio::Testing::WorkflowEnvironment env) -> void

      private

      attr_reader env: Temporalio::Testing::WorkflowEnvironment
    end
  end
end
