module Temporalio
  module Testing
    class WorkflowEnvironment
      attr_reader connection: Temporalio::Connection
      attr_reader namespace: String

      def initialize: (Temporalio::Bridge::TestServer server, Temporalio::Connection connection, String namespace) -> void
      def client: -> Temporalio::Client
      def sleep: (Integer duration) -> void
      def current_time: -> Time?
      def supports_time_skipping?: -> bool
      def shutdown: -> void
      def with_time_skipping: { () -> untyped } -> untyped

      private

      @client: Temporalio::Client

      attr_reader server: Temporalio::Bridge::TestServer
    end
  end
end
