# The original RBS signatured were generated using the rbs_protobuf gem which is meant for the
# Ruby's native protobuf gem, but we are using google-protobuf instead. While most types are
# identical, there are a few exceptions which are corrected here.

# Source: google/protobuf/well_known_types
class Google::Protobuf::Timestamp
  def to_time: () -> Time
end

# Source: google/protobuf
class Coresdk::ActivityTaskCompletion
  def self.encode: (Coresdk::ActivityTaskCompletion) -> String
end

class Temporal::Api::WorkflowService::V1::RegisterNamespaceRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::RegisterNamespaceRequest) -> String
end

class Temporal::Api::WorkflowService::V1::DescribeNamespaceRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::DescribeNamespaceRequest) -> String
end

class Temporal::Api::WorkflowService::V1::ListNamespacesRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::ListNamespacesRequest) -> String
end

class Temporal::Api::WorkflowService::V1::UpdateNamespaceRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::UpdateNamespaceRequest) -> String
end

class Temporal::Api::WorkflowService::V1::DeprecateNamespaceRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::DeprecateNamespaceRequest) -> String
end

class Temporal::Api::WorkflowService::V1::StartWorkflowExecutionRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::StartWorkflowExecutionRequest) -> String
end

class Temporal::Api::WorkflowService::V1::GetWorkflowExecutionHistoryRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::GetWorkflowExecutionHistoryRequest) -> String
end

class Temporal::Api::WorkflowService::V1::GetWorkflowExecutionHistoryReverseRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::GetWorkflowExecutionHistoryReverseRequest) -> String
end

class Temporal::Api::WorkflowService::V1::PollWorkflowTaskQueueRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::PollWorkflowTaskQueueRequest) -> String
end

class Temporal::Api::WorkflowService::V1::RespondWorkflowTaskCompletedRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::RespondWorkflowTaskCompletedRequest) -> String
end

class Temporal::Api::WorkflowService::V1::RespondWorkflowTaskFailedRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::RespondWorkflowTaskFailedRequest) -> String
end

class Temporal::Api::WorkflowService::V1::PollActivityTaskQueueRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::PollActivityTaskQueueRequest) -> String
end

class Temporal::Api::WorkflowService::V1::RecordActivityTaskHeartbeatRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::RecordActivityTaskHeartbeatRequest) -> String
end

class Temporal::Api::WorkflowService::V1::RecordActivityTaskHeartbeatByIdRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::RecordActivityTaskHeartbeatByIdRequest) -> String
end

class Temporal::Api::WorkflowService::V1::RespondActivityTaskCompletedRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::RespondActivityTaskCompletedRequest) -> String
end

class Temporal::Api::WorkflowService::V1::RespondActivityTaskCompletedByIdRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::RespondActivityTaskCompletedByIdRequest) -> String
end

class Temporal::Api::WorkflowService::V1::RespondActivityTaskFailedRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::RespondActivityTaskFailedRequest) -> String
end

class Temporal::Api::WorkflowService::V1::RespondActivityTaskFailedByIdRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::RespondActivityTaskFailedByIdRequest) -> String
end

class Temporal::Api::WorkflowService::V1::RespondActivityTaskCanceledRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::RespondActivityTaskCanceledRequest) -> String
end

class Temporal::Api::WorkflowService::V1::RespondActivityTaskCanceledByIdRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::RespondActivityTaskCanceledByIdRequest) -> String
end

class Temporal::Api::WorkflowService::V1::RequestCancelWorkflowExecutionRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::RequestCancelWorkflowExecutionRequest) -> String
end

class Temporal::Api::WorkflowService::V1::SignalWorkflowExecutionRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::SignalWorkflowExecutionRequest) -> String
end

class Temporal::Api::WorkflowService::V1::SignalWithStartWorkflowExecutionRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::SignalWithStartWorkflowExecutionRequest) -> String
end

class Temporal::Api::WorkflowService::V1::ResetWorkflowExecutionRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::ResetWorkflowExecutionRequest) -> String
end

class Temporal::Api::WorkflowService::V1::TerminateWorkflowExecutionRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::TerminateWorkflowExecutionRequest) -> String
end

class Temporal::Api::WorkflowService::V1::ListOpenWorkflowExecutionsRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::ListOpenWorkflowExecutionsRequest) -> String
end

class Temporal::Api::WorkflowService::V1::ListClosedWorkflowExecutionsRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::ListClosedWorkflowExecutionsRequest) -> String
end

class Temporal::Api::WorkflowService::V1::ListWorkflowExecutionsRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::ListWorkflowExecutionsRequest) -> String
end

class Temporal::Api::WorkflowService::V1::ListArchivedWorkflowExecutionsRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::ListArchivedWorkflowExecutionsRequest) -> String
end

class Temporal::Api::WorkflowService::V1::ScanWorkflowExecutionsRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::ScanWorkflowExecutionsRequest) -> String
end

class Temporal::Api::WorkflowService::V1::CountWorkflowExecutionsRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::CountWorkflowExecutionsRequest) -> String
end

class Temporal::Api::WorkflowService::V1::GetSearchAttributesRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::GetSearchAttributesRequest) -> String
end

class Temporal::Api::WorkflowService::V1::RespondQueryTaskCompletedRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::RespondQueryTaskCompletedRequest) -> String
end

class Temporal::Api::WorkflowService::V1::ResetStickyTaskQueueRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::ResetStickyTaskQueueRequest) -> String
end

class Temporal::Api::WorkflowService::V1::QueryWorkflowRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::QueryWorkflowRequest) -> String
end

class Temporal::Api::WorkflowService::V1::DescribeWorkflowExecutionRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::DescribeWorkflowExecutionRequest) -> String
end

class Temporal::Api::WorkflowService::V1::DescribeTaskQueueRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::DescribeTaskQueueRequest) -> String
end

class Temporal::Api::WorkflowService::V1::GetClusterInfoRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::GetClusterInfoRequest) -> String
end

class Temporal::Api::WorkflowService::V1::GetSystemInfoRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::GetSystemInfoRequest) -> String
end

class Temporal::Api::WorkflowService::V1::ListTaskQueuePartitionsRequest
  def self.encode: (Temporal::Api::WorkflowService::V1::ListTaskQueuePartitionsRequest) -> String
end
