# The original RBS signatured were generated using the rbs_protobuf gem which is meant for the
# Ruby's native protobuf gem, but we are using google-protobuf instead. While most types are
# identical, there are a few exceptions which are corrected here.

# Source: google/protobuf/well_known_types
class Google::Protobuf::Timestamp
  def to_time: () -> Time
end

class Google::Protobuf::Duration
  def to_f: () -> Float
end

class Temporalio::Bridge::Api::WorkflowActivation::WorkflowActivationJob
  def variant: -> Symbol
end
