# Missing signatures for Ruby's stdlib

class Thread
  # https://rubyapi.org/3.1/o/thread#method-c-handle_interrupt
  def self.handle_interrupt: (Hash[singleton(Exception), Symbol]) { -> untyped } -> untyped
                           | ...

  # https://rubyapi.org/3.1/o/thread#method-i-raise
  def raise: () -> bot
           | (::String arg0) -> bot
           | (::_Exception arg0, ?untyped arg1, ?::Array[::String] arg2) -> bot
end
