module Temporalio
  module Internal
    module Worker
      class WorkflowInstance
        class IllegalCallTracer
          def self.frozen_validated_illegal_calls: (
            Hash[String, :all | Array[Symbol | Temporalio::Worker::IllegalWorkflowCallValidator] | Temporalio::Worker::IllegalWorkflowCallValidator] illegal_calls
          ) -> Hash[String, :all | Hash[Symbol, TrueClass | Temporalio::Worker::IllegalWorkflowCallValidator] | Temporalio::Worker::IllegalWorkflowCallValidator]

          def initialize: (
            Hash[String, :all | Hash[Symbol, TrueClass | Temporalio::Worker::IllegalWorkflowCallValidator] | Temporalio::Worker::IllegalWorkflowCallValidator] illegal_calls
          ) -> void

          def enable: [T] { -> T } -> T
          def disable_temporarily: [T] { -> T } -> T
        end
      end
    end
  end
end