require 'thermite/tasks'
require 'thermite_patch'

Thermite::Tasks.new(
  cargo_project_path: File.expand_path('../bridge', __dir__),
  ruby_project_path: File.expand_path('..', __dir__),
)

task default: 'thermite:build'
