module Coresdk
  module Workflow_completion
    # / Result of a single workflow activation, reported from lang to core
    #
    class WorkflowActivationCompletion < ::Protobuf::Message
      # The run id from the workflow activation you are completing
      #
      attr_accessor run_id(): ::String

      def run_id!: () -> ::String?

      attr_accessor successful(): ::Coresdk::Workflow_completion::Success?

      def successful=: [M < ::Coresdk::Workflow_completion::Success::_ToProto] (M?) -> M?
                     | ...

      def successful!: () -> ::Coresdk::Workflow_completion::Success?

      attr_accessor failed(): ::Coresdk::Workflow_completion::Failure?

      def failed=: [M < ::Coresdk::Workflow_completion::Failure::_ToProto] (M?) -> M?
                 | ...

      def failed!: () -> ::Coresdk::Workflow_completion::Failure?

      def initialize: (?run_id: ::String, ?successful: ::Coresdk::Workflow_completion::Success::init?, ?failed: ::Coresdk::Workflow_completion::Failure::init?) -> void

      def []: (:run_id) -> ::String
            | (:successful) -> ::Coresdk::Workflow_completion::Success?
            | (:failed) -> ::Coresdk::Workflow_completion::Failure?
            | (::Symbol) -> untyped

      def []=: (:run_id, ::String) -> ::String
             | (:successful, ::Coresdk::Workflow_completion::Success?) -> ::Coresdk::Workflow_completion::Success?
             | [M < ::Coresdk::Workflow_completion::Success::_ToProto] (:successful, M?) -> M?
             | (:failed, ::Coresdk::Workflow_completion::Failure?) -> ::Coresdk::Workflow_completion::Failure?
             | [M < ::Coresdk::Workflow_completion::Failure::_ToProto] (:failed, M?) -> M?
             | (::Symbol, untyped) -> untyped

      interface _ToProto
        def to_proto: () -> WorkflowActivationCompletion
      end

      # The type of `#initialize` parameter.
      type init = WorkflowActivationCompletion | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[WorkflowActivationCompletion, WorkflowActivationCompletion | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, WorkflowActivationCompletion, WorkflowActivationCompletion | _ToProto]

      type array = ::Array[WorkflowActivationCompletion | _ToProto]

      type hash[KEY] = ::Hash[KEY, WorkflowActivationCompletion | _ToProto]
    end

    # / Successful workflow activation with a list of commands generated by the workflow execution
    #
    class Success < ::Protobuf::Message
      # A list of commands to send back to the temporal server
      #
      attr_accessor commands(): ::Coresdk::Workflow_commands::WorkflowCommand::field_array

      # A list of commands to send back to the temporal server
      #
      def commands=: (::Coresdk::Workflow_commands::WorkflowCommand::array) -> ::Coresdk::Workflow_commands::WorkflowCommand::array
                   | ...

      def commands!: () -> ::Coresdk::Workflow_commands::WorkflowCommand::field_array?

      def initialize: (?commands: ::Coresdk::Workflow_commands::WorkflowCommand::array) -> void

      def []: (:commands) -> ::Coresdk::Workflow_commands::WorkflowCommand::field_array
            | (::Symbol) -> untyped

      def []=: (:commands, ::Coresdk::Workflow_commands::WorkflowCommand::field_array) -> ::Coresdk::Workflow_commands::WorkflowCommand::field_array
             | (:commands, ::Coresdk::Workflow_commands::WorkflowCommand::array) -> ::Coresdk::Workflow_commands::WorkflowCommand::array
             | (::Symbol, untyped) -> untyped

      interface _ToProto
        def to_proto: () -> Success
      end

      # The type of `#initialize` parameter.
      type init = Success | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[Success, Success | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, Success, Success | _ToProto]

      type array = ::Array[Success | _ToProto]

      type hash[KEY] = ::Hash[KEY, Success | _ToProto]
    end

    # / Failure to activate or execute a workflow
    #
    class Failure < ::Protobuf::Message
      attr_accessor failure(): ::Temporal::Api::Failure::V1::Failure?

      def failure=: [M < ::Temporal::Api::Failure::V1::Failure::_ToProto] (M?) -> M?
                  | ...

      def failure!: () -> ::Temporal::Api::Failure::V1::Failure?

      def initialize: (?failure: ::Temporal::Api::Failure::V1::Failure::init?) -> void

      def []: (:failure) -> ::Temporal::Api::Failure::V1::Failure?
            | (::Symbol) -> untyped

      def []=: (:failure, ::Temporal::Api::Failure::V1::Failure?) -> ::Temporal::Api::Failure::V1::Failure?
             | [M < ::Temporal::Api::Failure::V1::Failure::_ToProto] (:failure, M?) -> M?
             | (::Symbol, untyped) -> untyped

      interface _ToProto
        def to_proto: () -> Failure
      end

      # The type of `#initialize` parameter.
      type init = Failure | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[Failure, Failure | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, Failure, Failure | _ToProto]

      type array = ::Array[Failure | _ToProto]

      type hash[KEY] = ::Hash[KEY, Failure | _ToProto]
    end
  end
end
