module Temporal
  module FailureConverter
    interface _FailureConverter
      def to_failure: (Exception) -> Temporal::Api::Failure::V1::Failure
      def from_failure: (Temporal::Api::Failure::V1::Failure) -> Exception
    end

    class Base
      include _FailureConverter
    end
  end
end
