module Temporal
  module FailureConverter
    interface _FailureConverter
      def to_failure: (Exception, Temporal::PayloadConverter::_PayloadConverter) -> Temporal::Api::Failure::V1::Failure
      def from_failure: (Temporal::Api::Failure::V1::Failure, Temporal::PayloadConverter::_PayloadConverter) -> Exception
    end

    class Base
      include _FailureConverter
    end
  end
end
