module Temporalio
  class Client
    class Connection
      class Service
        def initialize: (Connection, untyped) -> void

        def invoke_rpc: [REQ < Object, RESP < Object] (
          rpc: String,
          request_class: class REQ,
          response_class: class RESP,
          request: REQ,
          rpc_options: RPCOptions?
        ) -> RESP
      end
    end
  end
end