module Temporalio
  class Client
    class Connection
      class Service
        def initialize: (Connection, untyped) -> void

        def invoke_rpc: (
          rpc: String,
          request_class: untyped,
          response_class: untyped,
          request: ::Google::Protobuf::AbstractMessage,
          rpc_options: RPCOptions?
        ) -> untyped
      end
    end
  end
end
