module Temporalio
  module Converters
    class PayloadConverter
      class Encoding
        def encoding: -> String

        def to_payload: (Object? value, ?hint: Object?) -> Temporalio::Api::Common::V1::Payload?

        def from_payload: (Temporalio::Api::Common::V1::Payload payload, ?hint: Object?) -> Object?
      end
    end
  end
end
