module Temporalio
  module Converters
    class PayloadConverter
      class JSONPlain < Encoding
        ENCODING: String

        def initialize: (
          ?parse_options: Hash[Symbol, untyped],
          ?generate_options: Hash[Symbol, untyped]
        ) -> void
      end
    end
  end
end
