module Temporal
  module Api
    module Enums
      module V1
        class BatchOperationType < ::Protobuf::Enum
          type names = :BATCH_OPERATION_TYPE_UNSPECIFIED | :BATCH_OPERATION_TYPE_TERMINATE | :BATCH_OPERATION_TYPE_CANCEL | :BATCH_OPERATION_TYPE_SIGNAL | :BATCH_OPERATION_TYPE_DELETE

          type strings = "BATCH_OPERATION_TYPE_UNSPECIFIED" | "BATCH_OPERATION_TYPE_TERMINATE" | "BATCH_OPERATION_TYPE_CANCEL" | "BATCH_OPERATION_TYPE_SIGNAL" | "BATCH_OPERATION_TYPE_DELETE"

          type tags = 0 | 1 | 2 | 3 | 4

          type values = names | strings | tags

          attr_reader name(): names

          attr_reader tag(): tags

          BATCH_OPERATION_TYPE_UNSPECIFIED: BatchOperationType

          BATCH_OPERATION_TYPE_TERMINATE: BatchOperationType

          BATCH_OPERATION_TYPE_CANCEL: BatchOperationType

          BATCH_OPERATION_TYPE_SIGNAL: BatchOperationType

          BATCH_OPERATION_TYPE_DELETE: BatchOperationType

          # The type of `#initialize` parameter.
          type init = BatchOperationType | values

          # The type of `repeated` field.
          type field_array = ::Protobuf::Field::FieldArray[BatchOperationType, BatchOperationType | values]

          # The type of `map` field.
          type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, BatchOperationType, BatchOperationType | values]

          type array = ::Array[BatchOperationType | values]

          type hash[KEY] = ::Hash[KEY, BatchOperationType | values]
        end

        class BatchOperationState < ::Protobuf::Enum
          type names = :BATCH_OPERATION_STATE_UNSPECIFIED | :BATCH_OPERATION_STATE_RUNNING | :BATCH_OPERATION_STATE_COMPLETED | :BATCH_OPERATION_STATE_FAILED

          type strings = "BATCH_OPERATION_STATE_UNSPECIFIED" | "BATCH_OPERATION_STATE_RUNNING" | "BATCH_OPERATION_STATE_COMPLETED" | "BATCH_OPERATION_STATE_FAILED"

          type tags = 0 | 1 | 2 | 3

          type values = names | strings | tags

          attr_reader name(): names

          attr_reader tag(): tags

          BATCH_OPERATION_STATE_UNSPECIFIED: BatchOperationState

          BATCH_OPERATION_STATE_RUNNING: BatchOperationState

          BATCH_OPERATION_STATE_COMPLETED: BatchOperationState

          BATCH_OPERATION_STATE_FAILED: BatchOperationState

          # The type of `#initialize` parameter.
          type init = BatchOperationState | values

          # The type of `repeated` field.
          type field_array = ::Protobuf::Field::FieldArray[BatchOperationState, BatchOperationState | values]

          # The type of `map` field.
          type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, BatchOperationState, BatchOperationState | values]

          type array = ::Array[BatchOperationState | values]

          type hash[KEY] = ::Hash[KEY, BatchOperationState | values]
        end
      end
    end
  end
end
