module Temporal
  module Api
    module Enums
      module V1
        # Whenever this list of command types is changed do change the function shouldBufferEvent in mutableStateBuilder.go to make sure to do the correct event ordering.
        #
        class CommandType < ::Protobuf::Enum
          type names = :COMMAND_TYPE_UNSPECIFIED | :COMMAND_TYPE_SCHEDULE_ACTIVITY_TASK | :COMMAND_TYPE_REQUEST_CANCEL_ACTIVITY_TASK | :COMMAND_TYPE_START_TIMER | :COMMAND_TYPE_COMPLETE_WORKFLOW_EXECUTION | :COMMAND_TYPE_FAIL_WORKFLOW_EXECUTION | :COMMAND_TYPE_CANCEL_TIMER | :COMMAND_TYPE_CANCEL_WORKFLOW_EXECUTION | :COMMAND_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION | :COMMAND_TYPE_RECORD_MARKER | :COMMAND_TYPE_CONTINUE_AS_NEW_WORKFLOW_EXECUTION | :COMMAND_TYPE_START_CHILD_WORKFLOW_EXECUTION | :COMMAND_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION | :COMMAND_TYPE_UPSERT_WORKFLOW_SEARCH_ATTRIBUTES | :COMMAND_TYPE_ACCEPT_WORKFLOW_UPDATE | :COMMAND_TYPE_COMPLETE_WORKFLOW_UPDATE

          type strings = "COMMAND_TYPE_UNSPECIFIED" | "COMMAND_TYPE_SCHEDULE_ACTIVITY_TASK" | "COMMAND_TYPE_REQUEST_CANCEL_ACTIVITY_TASK" | "COMMAND_TYPE_START_TIMER" | "COMMAND_TYPE_COMPLETE_WORKFLOW_EXECUTION" | "COMMAND_TYPE_FAIL_WORKFLOW_EXECUTION" | "COMMAND_TYPE_CANCEL_TIMER" | "COMMAND_TYPE_CANCEL_WORKFLOW_EXECUTION" | "COMMAND_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION" | "COMMAND_TYPE_RECORD_MARKER" | "COMMAND_TYPE_CONTINUE_AS_NEW_WORKFLOW_EXECUTION" | "COMMAND_TYPE_START_CHILD_WORKFLOW_EXECUTION" | "COMMAND_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION" | "COMMAND_TYPE_UPSERT_WORKFLOW_SEARCH_ATTRIBUTES" | "COMMAND_TYPE_ACCEPT_WORKFLOW_UPDATE" | "COMMAND_TYPE_COMPLETE_WORKFLOW_UPDATE"

          type tags = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15

          type values = names | strings | tags

          attr_reader name(): names

          attr_reader tag(): tags

          COMMAND_TYPE_UNSPECIFIED: CommandType

          COMMAND_TYPE_SCHEDULE_ACTIVITY_TASK: CommandType

          COMMAND_TYPE_REQUEST_CANCEL_ACTIVITY_TASK: CommandType

          COMMAND_TYPE_START_TIMER: CommandType

          COMMAND_TYPE_COMPLETE_WORKFLOW_EXECUTION: CommandType

          COMMAND_TYPE_FAIL_WORKFLOW_EXECUTION: CommandType

          COMMAND_TYPE_CANCEL_TIMER: CommandType

          COMMAND_TYPE_CANCEL_WORKFLOW_EXECUTION: CommandType

          COMMAND_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION: CommandType

          COMMAND_TYPE_RECORD_MARKER: CommandType

          COMMAND_TYPE_CONTINUE_AS_NEW_WORKFLOW_EXECUTION: CommandType

          COMMAND_TYPE_START_CHILD_WORKFLOW_EXECUTION: CommandType

          COMMAND_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION: CommandType

          COMMAND_TYPE_UPSERT_WORKFLOW_SEARCH_ATTRIBUTES: CommandType

          # Indicates that an update has been accepted for processing workflow code
          #
          COMMAND_TYPE_ACCEPT_WORKFLOW_UPDATE: CommandType

          # Indicates that an update has completed and carries either the success or
          #  failure outcome of said update.
          #
          COMMAND_TYPE_COMPLETE_WORKFLOW_UPDATE: CommandType

          # The type of `#initialize` parameter.
          type init = CommandType | values

          # The type of `repeated` field.
          type field_array = ::Protobuf::Field::FieldArray[CommandType, CommandType | values]

          # The type of `map` field.
          type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, CommandType, CommandType | values]

          type array = ::Array[CommandType | values]

          type hash[KEY] = ::Hash[KEY, CommandType | values]
        end
      end
    end
  end
end
