module Temporal
  module Api
    module Enums
      module V1
        class QueryResultType < ::Protobuf::Enum
          type names = :QUERY_RESULT_TYPE_UNSPECIFIED | :QUERY_RESULT_TYPE_ANSWERED | :QUERY_RESULT_TYPE_FAILED

          type strings = "QUERY_RESULT_TYPE_UNSPECIFIED" | "QUERY_RESULT_TYPE_ANSWERED" | "QUERY_RESULT_TYPE_FAILED"

          type tags = 0 | 1 | 2

          type values = names | strings | tags

          attr_reader name(): names

          attr_reader tag(): tags

          QUERY_RESULT_TYPE_UNSPECIFIED: QueryResultType

          QUERY_RESULT_TYPE_ANSWERED: QueryResultType

          QUERY_RESULT_TYPE_FAILED: QueryResultType

          # The type of `#initialize` parameter.
          type init = QueryResultType | values

          # The type of `repeated` field.
          type field_array = ::Protobuf::Field::FieldArray[QueryResultType, QueryResultType | values]

          # The type of `map` field.
          type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, QueryResultType, QueryResultType | values]

          type array = ::Array[QueryResultType | values]

          type hash[KEY] = ::Hash[KEY, QueryResultType | values]
        end

        class QueryRejectCondition < ::Protobuf::Enum
          type names = :QUERY_REJECT_CONDITION_UNSPECIFIED | :QUERY_REJECT_CONDITION_NONE | :QUERY_REJECT_CONDITION_NOT_OPEN | :QUERY_REJECT_CONDITION_NOT_COMPLETED_CLEANLY

          type strings = "QUERY_REJECT_CONDITION_UNSPECIFIED" | "QUERY_REJECT_CONDITION_NONE" | "QUERY_REJECT_CONDITION_NOT_OPEN" | "QUERY_REJECT_CONDITION_NOT_COMPLETED_CLEANLY"

          type tags = 0 | 1 | 2 | 3

          type values = names | strings | tags

          attr_reader name(): names

          attr_reader tag(): tags

          QUERY_REJECT_CONDITION_UNSPECIFIED: QueryRejectCondition

          # None indicates that query should not be rejected.
          #
          QUERY_REJECT_CONDITION_NONE: QueryRejectCondition

          # NotOpen indicates that query should be rejected if workflow is not open.
          #
          QUERY_REJECT_CONDITION_NOT_OPEN: QueryRejectCondition

          # NotCompletedCleanly indicates that query should be rejected if workflow did not complete cleanly.
          #
          QUERY_REJECT_CONDITION_NOT_COMPLETED_CLEANLY: QueryRejectCondition

          # The type of `#initialize` parameter.
          type init = QueryRejectCondition | values

          # The type of `repeated` field.
          type field_array = ::Protobuf::Field::FieldArray[QueryRejectCondition, QueryRejectCondition | values]

          # The type of `map` field.
          type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, QueryRejectCondition, QueryRejectCondition | values]

          type array = ::Array[QueryRejectCondition | values]

          type hash[KEY] = ::Hash[KEY, QueryRejectCondition | values]
        end
      end
    end
  end
end
