module Temporal
  module Api
    module Enums
      module V1
        class WorkflowUpdateResultAccessStyle < ::Protobuf::Enum
          type names = :WORKFLOW_UPDATE_RESULT_ACCESS_STYLE_UNSPECIFIED | :WORKFLOW_UPDATE_RESULT_ACCESS_STYLE_REQUIRE_INLINE

          type strings = "WORKFLOW_UPDATE_RESULT_ACCESS_STYLE_UNSPECIFIED" | "WORKFLOW_UPDATE_RESULT_ACCESS_STYLE_REQUIRE_INLINE"

          type tags = 0 | 1

          type values = names | strings | tags

          attr_reader name(): names

          attr_reader tag(): tags

          WORKFLOW_UPDATE_RESULT_ACCESS_STYLE_UNSPECIFIED: WorkflowUpdateResultAccessStyle

          # Indicates that the update response _must_ be included as part of the gRPC
          #  response body
          #
          WORKFLOW_UPDATE_RESULT_ACCESS_STYLE_REQUIRE_INLINE: WorkflowUpdateResultAccessStyle

          # The type of `#initialize` parameter.
          type init = WorkflowUpdateResultAccessStyle | values

          # The type of `repeated` field.
          type field_array = ::Protobuf::Field::FieldArray[WorkflowUpdateResultAccessStyle, WorkflowUpdateResultAccessStyle | values]

          # The type of `map` field.
          type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, WorkflowUpdateResultAccessStyle, WorkflowUpdateResultAccessStyle | values]

          type array = ::Array[WorkflowUpdateResultAccessStyle | values]

          type hash[KEY] = ::Hash[KEY, WorkflowUpdateResultAccessStyle | values]
        end
      end
    end
  end
end
