module Temporalio
  module Converters
    class FailureConverter
      def self.default: -> FailureConverter

      def initialize: (?encode_common_attributes: bool) -> void

      def to_failure: (Exception error, DataConverter | PayloadConverter converter) -> untyped
      def from_failure: (untyped failure, DataConverter | PayloadConverter converter) -> Exception
    end
  end
end