module Temporalio
  module Converters
    class FailureConverter
      def self.default: -> FailureConverter

      def initialize: (?encode_common_attributes: bool) -> void

      def to_failure: (Exception error, DataConverter | PayloadConverter converter) -> Api::Failure::V1::Failure
      def from_failure: (Api::Failure::V1::Failure failure, DataConverter | PayloadConverter converter) -> Exception
    end
  end
end
