module Temporalio
  module Converters
    class PayloadConverter
      def self.default: -> Composite

      def self.new_with_defaults: (
        ?json_parse_options: Hash[Symbol, untyped],
        ?json_generate_options: Hash[Symbol, untyped]
      ) -> Composite

      def to_payload: (Object? value, ?hint: Object?) -> untyped
      def to_payloads: (Array[Object?] values, ?hints: Array[Object]?) -> untyped

      def from_payload: (untyped payload, ?hint: Object?) -> Object?
      def from_payloads: (untyped payloads, ?hints: Array[Object]?) -> Array[Object?]
    end
  end
end