module Temporalio
  module Converters
    class StorageDriverStoreContext
      attr_reader target: storageDriverTargetInfo?
      attr_reader cancellation: Cancellation

      def initialize: (
        target: storageDriverTargetInfo?,
        cancellation: Cancellation
      ) -> void
    end
  end
end
