module Temporalio
  module PayloadConverter
    class Composite < Base
      class ConverterNotFound < Temporalio::Error
      end

      class EncodingNotSet < Temporalio::Error
      end

      include _PayloadConverter

      def initialize: (*_EncodingPayloadConverter converters) -> void

      private

      attr_reader converters: Hash[String, _EncodingPayloadConverter]
    end
  end
end
