module Temporalio
  class Connection
    class Service
      def initialize: (Temporalio::Bridge::Connection core_connectio, Symbol service) -> void

      private

      attr_reader core_connection: Temporalio::Bridge::Connection
      attr_reader service: Symbol

      def call: (Symbol, String, Hash[String, String], Integer?) -> String
    end
  end
end
