module Coresdk
  module Bridge
    class LogLevel < ::Protobuf::Enum
      type names = :LOG_LEVEL_UNSPECIFIED | :OFF | :ERROR | :WARN | :INFO | :DEBUG | :TRACE

      type strings = "LOG_LEVEL_UNSPECIFIED" | "OFF" | "ERROR" | "WARN" | "INFO" | "DEBUG" | "TRACE"

      type tags = 0 | 1 | 2 | 3 | 4 | 5 | 6

      type values = names | strings | tags

      attr_reader name(): names

      attr_reader tag(): tags

      LOG_LEVEL_UNSPECIFIED: LogLevel

      OFF: LogLevel

      ERROR: LogLevel

      WARN: LogLevel

      INFO: LogLevel

      DEBUG: LogLevel

      TRACE: LogLevel

      # The type of `#initialize` parameter.
      type init = LogLevel | values

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[LogLevel, LogLevel | values]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, LogLevel, LogLevel | values]

      type array = ::Array[LogLevel | values]

      type hash[KEY] = ::Hash[KEY, LogLevel | values]
    end

    class InitTelemetryRequest < ::Protobuf::Message
      class ConsoleLoggerOptions < ::Protobuf::Message
        def initialize: () -> void

        interface _ToProto
          def to_proto: () -> ConsoleLoggerOptions
        end

        # The type of `#initialize` parameter.
        type init = ConsoleLoggerOptions | _ToProto

        # The type of `repeated` field.
        type field_array = ::Protobuf::Field::FieldArray[ConsoleLoggerOptions, ConsoleLoggerOptions | _ToProto]

        # The type of `map` field.
        type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, ConsoleLoggerOptions, ConsoleLoggerOptions | _ToProto]

        type array = ::Array[ConsoleLoggerOptions | _ToProto]

        type hash[KEY] = ::Hash[KEY, ConsoleLoggerOptions | _ToProto]
      end

      class ForwardLoggerOptions < ::Protobuf::Message
        attr_accessor level(): ::Temporalio::Bridge::Api::Bridge::LogLevel

        def level=: (::Temporalio::Bridge::Api::Bridge::LogLevel::values) -> ::Temporalio::Bridge::Api::Bridge::LogLevel::values
                  | ...

        def level!: () -> ::Temporalio::Bridge::Api::Bridge::LogLevel?

        def initialize: (?level: ::Temporalio::Bridge::Api::Bridge::LogLevel::init) -> void

        def []: (:level) -> ::Temporalio::Bridge::Api::Bridge::LogLevel
              | (::Symbol) -> untyped

        def []=: (:level, ::Temporalio::Bridge::Api::Bridge::LogLevel) -> ::Temporalio::Bridge::Api::Bridge::LogLevel
               | (:level, ::Temporalio::Bridge::Api::Bridge::LogLevel::values) -> ::Temporalio::Bridge::Api::Bridge::LogLevel::values
               | (::Symbol, untyped) -> untyped

        interface _ToProto
          def to_proto: () -> ForwardLoggerOptions
        end

        # The type of `#initialize` parameter.
        type init = ForwardLoggerOptions | _ToProto

        # The type of `repeated` field.
        type field_array = ::Protobuf::Field::FieldArray[ForwardLoggerOptions, ForwardLoggerOptions | _ToProto]

        # The type of `map` field.
        type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, ForwardLoggerOptions, ForwardLoggerOptions | _ToProto]

        type array = ::Array[ForwardLoggerOptions | _ToProto]

        type hash[KEY] = ::Hash[KEY, ForwardLoggerOptions | _ToProto]
      end

      class OtelCollectorOptions < ::Protobuf::Message
        attr_accessor url(): ::String

        def url!: () -> ::String?

        attr_accessor headers(): ::Protobuf::field_hash[::String, ::String]

        def headers=: (::Hash[::String, ::String]) -> ::Hash[::String, ::String]
                    | ...

        def headers!: () -> ::Protobuf::field_hash[::String, ::String]?

        def initialize: (?url: ::String, ?headers: ::Hash[::String, ::String]) -> void

        def []: (:url) -> ::String
              | (:headers) -> ::Protobuf::field_hash[::String, ::String]
              | (::Symbol) -> untyped

        def []=: (:url, ::String) -> ::String
               | (:headers, ::Protobuf::field_hash[::String, ::String]) -> ::Protobuf::field_hash[::String, ::String]
               | (:headers, ::Hash[::String, ::String]) -> ::Hash[::String, ::String]
               | (::Symbol, untyped) -> untyped

        interface _ToProto
          def to_proto: () -> OtelCollectorOptions
        end

        # The type of `#initialize` parameter.
        type init = OtelCollectorOptions | _ToProto

        # The type of `repeated` field.
        type field_array = ::Protobuf::Field::FieldArray[OtelCollectorOptions, OtelCollectorOptions | _ToProto]

        # The type of `map` field.
        type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, OtelCollectorOptions, OtelCollectorOptions | _ToProto]

        type array = ::Array[OtelCollectorOptions | _ToProto]

        type hash[KEY] = ::Hash[KEY, OtelCollectorOptions | _ToProto]
      end

      class PrometheusOptions < ::Protobuf::Message
        attr_accessor export_bind_address(): ::String

        def export_bind_address!: () -> ::String?

        def initialize: (?export_bind_address: ::String) -> void

        def []: (:export_bind_address) -> ::String
              | (::Symbol) -> untyped

        def []=: (:export_bind_address, ::String) -> ::String
               | (::Symbol, untyped) -> untyped

        interface _ToProto
          def to_proto: () -> PrometheusOptions
        end

        # The type of `#initialize` parameter.
        type init = PrometheusOptions | _ToProto

        # The type of `repeated` field.
        type field_array = ::Protobuf::Field::FieldArray[PrometheusOptions, PrometheusOptions | _ToProto]

        # The type of `map` field.
        type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, PrometheusOptions, PrometheusOptions | _ToProto]

        type array = ::Array[PrometheusOptions | _ToProto]

        type hash[KEY] = ::Hash[KEY, PrometheusOptions | _ToProto]
      end

      attr_accessor tracing_filter(): ::String

      def tracing_filter!: () -> ::String?

      attr_accessor console(): ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::ConsoleLoggerOptions?

      def console=: [M < ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::ConsoleLoggerOptions::_ToProto] (M?) -> M?
                  | ...

      def console!: () -> ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::ConsoleLoggerOptions?

      attr_accessor forward(): ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::ForwardLoggerOptions?

      def forward=: [M < ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::ForwardLoggerOptions::_ToProto] (M?) -> M?
                  | ...

      def forward!: () -> ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::ForwardLoggerOptions?

      attr_accessor otel_tracing(): ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::OtelCollectorOptions?

      def otel_tracing=: [M < ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::OtelCollectorOptions::_ToProto] (M?) -> M?
                       | ...

      def otel_tracing!: () -> ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::OtelCollectorOptions?

      attr_accessor otel_metrics(): ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::OtelCollectorOptions?

      def otel_metrics=: [M < ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::OtelCollectorOptions::_ToProto] (M?) -> M?
                       | ...

      def otel_metrics!: () -> ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::OtelCollectorOptions?

      attr_accessor prometheus(): ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::PrometheusOptions?

      def prometheus=: [M < ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::PrometheusOptions::_ToProto] (M?) -> M?
                     | ...

      def prometheus!: () -> ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::PrometheusOptions?

      def initialize: (?tracing_filter: ::String, ?console: ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::ConsoleLoggerOptions::init?, ?forward: ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::ForwardLoggerOptions::init?, ?otel_tracing: ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::OtelCollectorOptions::init?, ?otel_metrics: ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::OtelCollectorOptions::init?, ?prometheus: ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::PrometheusOptions::init?) -> void

      def []: (:tracing_filter) -> ::String
            | (:console) -> ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::ConsoleLoggerOptions?
            | (:forward) -> ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::ForwardLoggerOptions?
            | (:otel_tracing) -> ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::OtelCollectorOptions?
            | (:otel_metrics) -> ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::OtelCollectorOptions?
            | (:prometheus) -> ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::PrometheusOptions?
            | (::Symbol) -> untyped

      def []=: (:tracing_filter, ::String) -> ::String
             | (:console, ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::ConsoleLoggerOptions?) -> ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::ConsoleLoggerOptions?
             | [M < ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::ConsoleLoggerOptions::_ToProto] (:console, M?) -> M?
             | (:forward, ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::ForwardLoggerOptions?) -> ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::ForwardLoggerOptions?
             | [M < ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::ForwardLoggerOptions::_ToProto] (:forward, M?) -> M?
             | (:otel_tracing, ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::OtelCollectorOptions?) -> ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::OtelCollectorOptions?
             | [M < ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::OtelCollectorOptions::_ToProto] (:otel_tracing, M?) -> M?
             | (:otel_metrics, ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::OtelCollectorOptions?) -> ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::OtelCollectorOptions?
             | [M < ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::OtelCollectorOptions::_ToProto] (:otel_metrics, M?) -> M?
             | (:prometheus, ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::PrometheusOptions?) -> ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::PrometheusOptions?
             | [M < ::Temporalio::Bridge::Api::Bridge::InitTelemetryRequest::PrometheusOptions::_ToProto] (:prometheus, M?) -> M?
             | (::Symbol, untyped) -> untyped

      interface _ToProto
        def to_proto: () -> InitTelemetryRequest
      end

      # The type of `#initialize` parameter.
      type init = InitTelemetryRequest | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[InitTelemetryRequest, InitTelemetryRequest | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, InitTelemetryRequest, InitTelemetryRequest | _ToProto]

      type array = ::Array[InitTelemetryRequest | _ToProto]

      type hash[KEY] = ::Hash[KEY, InitTelemetryRequest | _ToProto]
    end

    class CreateClientRequest < ::Protobuf::Message
      class TlsConfig < ::Protobuf::Message
        attr_accessor server_root_ca_cert(): ::String

        def server_root_ca_cert!: () -> ::String?

        attr_accessor domain(): ::String

        def domain!: () -> ::String?

        attr_accessor client_cert(): ::String

        def client_cert!: () -> ::String?

        attr_accessor client_private_key(): ::String

        def client_private_key!: () -> ::String?

        def initialize: (?server_root_ca_cert: ::String, ?domain: ::String, ?client_cert: ::String, ?client_private_key: ::String) -> void

        def []: (:server_root_ca_cert) -> ::String
              | (:domain) -> ::String
              | (:client_cert) -> ::String
              | (:client_private_key) -> ::String
              | (::Symbol) -> untyped

        def []=: (:server_root_ca_cert, ::String) -> ::String
               | (:domain, ::String) -> ::String
               | (:client_cert, ::String) -> ::String
               | (:client_private_key, ::String) -> ::String
               | (::Symbol, untyped) -> untyped

        interface _ToProto
          def to_proto: () -> TlsConfig
        end

        # The type of `#initialize` parameter.
        type init = TlsConfig | _ToProto

        # The type of `repeated` field.
        type field_array = ::Protobuf::Field::FieldArray[TlsConfig, TlsConfig | _ToProto]

        # The type of `map` field.
        type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, TlsConfig, TlsConfig | _ToProto]

        type array = ::Array[TlsConfig | _ToProto]

        type hash[KEY] = ::Hash[KEY, TlsConfig | _ToProto]
      end

      class RetryConfig < ::Protobuf::Message
        attr_accessor initial_interval(): ::Google::Protobuf::Duration?

        def initial_interval=: [M < ::Google::Protobuf::Duration::_ToProto] (M?) -> M?
                             | ...

        def initial_interval!: () -> ::Google::Protobuf::Duration?

        attr_accessor randomization_factor(): ::Google::Protobuf::DoubleValue?

        def randomization_factor=: [M < ::Google::Protobuf::DoubleValue::_ToProto] (M?) -> M?
                                 | ...

        def randomization_factor!: () -> ::Google::Protobuf::DoubleValue?

        attr_accessor multiplier(): ::Google::Protobuf::DoubleValue?

        def multiplier=: [M < ::Google::Protobuf::DoubleValue::_ToProto] (M?) -> M?
                       | ...

        def multiplier!: () -> ::Google::Protobuf::DoubleValue?

        attr_accessor max_interval(): ::Google::Protobuf::Duration?

        def max_interval=: [M < ::Google::Protobuf::Duration::_ToProto] (M?) -> M?
                         | ...

        def max_interval!: () -> ::Google::Protobuf::Duration?

        attr_accessor max_elapsed_time(): ::Google::Protobuf::Duration?

        def max_elapsed_time=: [M < ::Google::Protobuf::Duration::_ToProto] (M?) -> M?
                             | ...

        def max_elapsed_time!: () -> ::Google::Protobuf::Duration?

        attr_accessor max_retries(): ::Google::Protobuf::UInt32Value?

        def max_retries=: [M < ::Google::Protobuf::UInt32Value::_ToProto] (M?) -> M?
                        | ...

        def max_retries!: () -> ::Google::Protobuf::UInt32Value?

        def initialize: (?initial_interval: ::Google::Protobuf::Duration::init?, ?randomization_factor: ::Google::Protobuf::DoubleValue::init?, ?multiplier: ::Google::Protobuf::DoubleValue::init?, ?max_interval: ::Google::Protobuf::Duration::init?, ?max_elapsed_time: ::Google::Protobuf::Duration::init?, ?max_retries: ::Google::Protobuf::UInt32Value::init?) -> void

        def []: (:initial_interval) -> ::Google::Protobuf::Duration?
              | (:randomization_factor) -> ::Google::Protobuf::DoubleValue?
              | (:multiplier) -> ::Google::Protobuf::DoubleValue?
              | (:max_interval) -> ::Google::Protobuf::Duration?
              | (:max_elapsed_time) -> ::Google::Protobuf::Duration?
              | (:max_retries) -> ::Google::Protobuf::UInt32Value?
              | (::Symbol) -> untyped

        def []=: (:initial_interval, ::Google::Protobuf::Duration?) -> ::Google::Protobuf::Duration?
               | [M < ::Google::Protobuf::Duration::_ToProto] (:initial_interval, M?) -> M?
               | (:randomization_factor, ::Google::Protobuf::DoubleValue?) -> ::Google::Protobuf::DoubleValue?
               | [M < ::Google::Protobuf::DoubleValue::_ToProto] (:randomization_factor, M?) -> M?
               | (:multiplier, ::Google::Protobuf::DoubleValue?) -> ::Google::Protobuf::DoubleValue?
               | [M < ::Google::Protobuf::DoubleValue::_ToProto] (:multiplier, M?) -> M?
               | (:max_interval, ::Google::Protobuf::Duration?) -> ::Google::Protobuf::Duration?
               | [M < ::Google::Protobuf::Duration::_ToProto] (:max_interval, M?) -> M?
               | (:max_elapsed_time, ::Google::Protobuf::Duration?) -> ::Google::Protobuf::Duration?
               | [M < ::Google::Protobuf::Duration::_ToProto] (:max_elapsed_time, M?) -> M?
               | (:max_retries, ::Google::Protobuf::UInt32Value?) -> ::Google::Protobuf::UInt32Value?
               | [M < ::Google::Protobuf::UInt32Value::_ToProto] (:max_retries, M?) -> M?
               | (::Symbol, untyped) -> untyped

        interface _ToProto
          def to_proto: () -> RetryConfig
        end

        # The type of `#initialize` parameter.
        type init = RetryConfig | _ToProto

        # The type of `repeated` field.
        type field_array = ::Protobuf::Field::FieldArray[RetryConfig, RetryConfig | _ToProto]

        # The type of `map` field.
        type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, RetryConfig, RetryConfig | _ToProto]

        type array = ::Array[RetryConfig | _ToProto]

        type hash[KEY] = ::Hash[KEY, RetryConfig | _ToProto]
      end

      attr_accessor target_url(): ::String

      def target_url!: () -> ::String?

      attr_accessor namespace(): ::String

      def namespace!: () -> ::String?

      attr_accessor client_name(): ::String

      def client_name!: () -> ::String?

      attr_accessor client_version(): ::String

      def client_version!: () -> ::String?

      attr_accessor identity(): ::String

      def identity!: () -> ::String?

      attr_accessor tls_config(): ::Temporalio::Bridge::Api::Bridge::CreateClientRequest::TlsConfig?

      def tls_config=: [M < ::Temporalio::Bridge::Api::Bridge::CreateClientRequest::TlsConfig::_ToProto] (M?) -> M?
                     | ...

      def tls_config!: () -> ::Temporalio::Bridge::Api::Bridge::CreateClientRequest::TlsConfig?

      attr_accessor retry_config(): ::Temporalio::Bridge::Api::Bridge::CreateClientRequest::RetryConfig?

      def retry_config=: [M < ::Temporalio::Bridge::Api::Bridge::CreateClientRequest::RetryConfig::_ToProto] (M?) -> M?
                       | ...

      def retry_config!: () -> ::Temporalio::Bridge::Api::Bridge::CreateClientRequest::RetryConfig?

      def initialize: (?target_url: ::String, ?namespace: ::String, ?client_name: ::String, ?client_version: ::String, ?identity: ::String, ?tls_config: ::Temporalio::Bridge::Api::Bridge::CreateClientRequest::TlsConfig::init?, ?retry_config: ::Temporalio::Bridge::Api::Bridge::CreateClientRequest::RetryConfig::init?) -> void

      def []: (:target_url) -> ::String
            | (:namespace) -> ::String
            | (:client_name) -> ::String
            | (:client_version) -> ::String
            | (:identity) -> ::String
            | (:tls_config) -> ::Temporalio::Bridge::Api::Bridge::CreateClientRequest::TlsConfig?
            | (:retry_config) -> ::Temporalio::Bridge::Api::Bridge::CreateClientRequest::RetryConfig?
            | (::Symbol) -> untyped

      def []=: (:target_url, ::String) -> ::String
             | (:namespace, ::String) -> ::String
             | (:client_name, ::String) -> ::String
             | (:client_version, ::String) -> ::String
             | (:identity, ::String) -> ::String
             | (:tls_config, ::Temporalio::Bridge::Api::Bridge::CreateClientRequest::TlsConfig?) -> ::Temporalio::Bridge::Api::Bridge::CreateClientRequest::TlsConfig?
             | [M < ::Temporalio::Bridge::Api::Bridge::CreateClientRequest::TlsConfig::_ToProto] (:tls_config, M?) -> M?
             | (:retry_config, ::Temporalio::Bridge::Api::Bridge::CreateClientRequest::RetryConfig?) -> ::Temporalio::Bridge::Api::Bridge::CreateClientRequest::RetryConfig?
             | [M < ::Temporalio::Bridge::Api::Bridge::CreateClientRequest::RetryConfig::_ToProto] (:retry_config, M?) -> M?
             | (::Symbol, untyped) -> untyped

      interface _ToProto
        def to_proto: () -> CreateClientRequest
      end

      # The type of `#initialize` parameter.
      type init = CreateClientRequest | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[CreateClientRequest, CreateClientRequest | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, CreateClientRequest, CreateClientRequest | _ToProto]

      type array = ::Array[CreateClientRequest | _ToProto]

      type hash[KEY] = ::Hash[KEY, CreateClientRequest | _ToProto]
    end

    class InitResponse < ::Protobuf::Message
      class Error < ::Protobuf::Message
        attr_accessor message(): ::String

        def message!: () -> ::String?

        def initialize: (?message: ::String) -> void

        def []: (:message) -> ::String
              | (::Symbol) -> untyped

        def []=: (:message, ::String) -> ::String
               | (::Symbol, untyped) -> untyped

        interface _ToProto
          def to_proto: () -> Error
        end

        # The type of `#initialize` parameter.
        type init = Error | _ToProto

        # The type of `repeated` field.
        type field_array = ::Protobuf::Field::FieldArray[Error, Error | _ToProto]

        # The type of `map` field.
        type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, Error, Error | _ToProto]

        type array = ::Array[Error | _ToProto]

        type hash[KEY] = ::Hash[KEY, Error | _ToProto]
      end

      attr_accessor error(): ::Temporalio::Bridge::Api::Bridge::InitResponse::Error?

      def error=: [M < ::Temporalio::Bridge::Api::Bridge::InitResponse::Error::_ToProto] (M?) -> M?
                | ...

      def error!: () -> ::Temporalio::Bridge::Api::Bridge::InitResponse::Error?

      def initialize: (?error: ::Temporalio::Bridge::Api::Bridge::InitResponse::Error::init?) -> void

      def []: (:error) -> ::Temporalio::Bridge::Api::Bridge::InitResponse::Error?
            | (::Symbol) -> untyped

      def []=: (:error, ::Temporalio::Bridge::Api::Bridge::InitResponse::Error?) -> ::Temporalio::Bridge::Api::Bridge::InitResponse::Error?
             | [M < ::Temporalio::Bridge::Api::Bridge::InitResponse::Error::_ToProto] (:error, M?) -> M?
             | (::Symbol, untyped) -> untyped

      interface _ToProto
        def to_proto: () -> InitResponse
      end

      # The type of `#initialize` parameter.
      type init = InitResponse | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[InitResponse, InitResponse | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, InitResponse, InitResponse | _ToProto]

      type array = ::Array[InitResponse | _ToProto]

      type hash[KEY] = ::Hash[KEY, InitResponse | _ToProto]
    end

    class CreateWorkerRequest < ::Protobuf::Message
      attr_accessor task_queue(): ::String

      def task_queue!: () -> ::String?

      attr_accessor max_cached_workflows(): ::Google::Protobuf::UInt32Value?

      def max_cached_workflows=: [M < ::Google::Protobuf::UInt32Value::_ToProto] (M?) -> M?
                               | ...

      def max_cached_workflows!: () -> ::Google::Protobuf::UInt32Value?

      attr_accessor max_outstanding_workflow_tasks(): ::Google::Protobuf::UInt32Value?

      def max_outstanding_workflow_tasks=: [M < ::Google::Protobuf::UInt32Value::_ToProto] (M?) -> M?
                                         | ...

      def max_outstanding_workflow_tasks!: () -> ::Google::Protobuf::UInt32Value?

      attr_accessor max_outstanding_activities(): ::Google::Protobuf::UInt32Value?

      def max_outstanding_activities=: [M < ::Google::Protobuf::UInt32Value::_ToProto] (M?) -> M?
                                     | ...

      def max_outstanding_activities!: () -> ::Google::Protobuf::UInt32Value?

      attr_accessor max_outstanding_local_activities(): ::Google::Protobuf::UInt32Value?

      def max_outstanding_local_activities=: [M < ::Google::Protobuf::UInt32Value::_ToProto] (M?) -> M?
                                           | ...

      def max_outstanding_local_activities!: () -> ::Google::Protobuf::UInt32Value?

      attr_accessor max_concurrent_wft_polls(): ::Google::Protobuf::UInt32Value?

      def max_concurrent_wft_polls=: [M < ::Google::Protobuf::UInt32Value::_ToProto] (M?) -> M?
                                   | ...

      def max_concurrent_wft_polls!: () -> ::Google::Protobuf::UInt32Value?

      attr_accessor nonsticky_to_sticky_poll_ratio(): ::Google::Protobuf::FloatValue?

      def nonsticky_to_sticky_poll_ratio=: [M < ::Google::Protobuf::FloatValue::_ToProto] (M?) -> M?
                                         | ...

      def nonsticky_to_sticky_poll_ratio!: () -> ::Google::Protobuf::FloatValue?

      attr_accessor max_concurrent_at_polls(): ::Google::Protobuf::UInt32Value?

      def max_concurrent_at_polls=: [M < ::Google::Protobuf::UInt32Value::_ToProto] (M?) -> M?
                                  | ...

      def max_concurrent_at_polls!: () -> ::Google::Protobuf::UInt32Value?

      attr_accessor no_remote_activities(): bool

      def no_remote_activities!: () -> bool?

      attr_accessor sticky_queue_schedule_to_start_timeout(): ::Google::Protobuf::Duration?

      def sticky_queue_schedule_to_start_timeout=: [M < ::Google::Protobuf::Duration::_ToProto] (M?) -> M?
                                                 | ...

      def sticky_queue_schedule_to_start_timeout!: () -> ::Google::Protobuf::Duration?

      attr_accessor max_heartbeat_throttle_interval(): ::Google::Protobuf::Duration?

      def max_heartbeat_throttle_interval=: [M < ::Google::Protobuf::Duration::_ToProto] (M?) -> M?
                                          | ...

      def max_heartbeat_throttle_interval!: () -> ::Google::Protobuf::Duration?

      attr_accessor default_heartbeat_throttle_interval(): ::Google::Protobuf::Duration?

      def default_heartbeat_throttle_interval=: [M < ::Google::Protobuf::Duration::_ToProto] (M?) -> M?
                                              | ...

      def default_heartbeat_throttle_interval!: () -> ::Google::Protobuf::Duration?

      def initialize: (?task_queue: ::String, ?max_cached_workflows: ::Google::Protobuf::UInt32Value::init?, ?max_outstanding_workflow_tasks: ::Google::Protobuf::UInt32Value::init?, ?max_outstanding_activities: ::Google::Protobuf::UInt32Value::init?, ?max_outstanding_local_activities: ::Google::Protobuf::UInt32Value::init?, ?max_concurrent_wft_polls: ::Google::Protobuf::UInt32Value::init?, ?nonsticky_to_sticky_poll_ratio: ::Google::Protobuf::FloatValue::init?, ?max_concurrent_at_polls: ::Google::Protobuf::UInt32Value::init?, ?no_remote_activities: bool, ?sticky_queue_schedule_to_start_timeout: ::Google::Protobuf::Duration::init?, ?max_heartbeat_throttle_interval: ::Google::Protobuf::Duration::init?, ?default_heartbeat_throttle_interval: ::Google::Protobuf::Duration::init?) -> void

      def []: (:task_queue) -> ::String
            | (:max_cached_workflows) -> ::Google::Protobuf::UInt32Value?
            | (:max_outstanding_workflow_tasks) -> ::Google::Protobuf::UInt32Value?
            | (:max_outstanding_activities) -> ::Google::Protobuf::UInt32Value?
            | (:max_outstanding_local_activities) -> ::Google::Protobuf::UInt32Value?
            | (:max_concurrent_wft_polls) -> ::Google::Protobuf::UInt32Value?
            | (:nonsticky_to_sticky_poll_ratio) -> ::Google::Protobuf::FloatValue?
            | (:max_concurrent_at_polls) -> ::Google::Protobuf::UInt32Value?
            | (:no_remote_activities) -> bool
            | (:sticky_queue_schedule_to_start_timeout) -> ::Google::Protobuf::Duration?
            | (:max_heartbeat_throttle_interval) -> ::Google::Protobuf::Duration?
            | (:default_heartbeat_throttle_interval) -> ::Google::Protobuf::Duration?
            | (::Symbol) -> untyped

      def []=: (:task_queue, ::String) -> ::String
             | (:max_cached_workflows, ::Google::Protobuf::UInt32Value?) -> ::Google::Protobuf::UInt32Value?
             | [M < ::Google::Protobuf::UInt32Value::_ToProto] (:max_cached_workflows, M?) -> M?
             | (:max_outstanding_workflow_tasks, ::Google::Protobuf::UInt32Value?) -> ::Google::Protobuf::UInt32Value?
             | [M < ::Google::Protobuf::UInt32Value::_ToProto] (:max_outstanding_workflow_tasks, M?) -> M?
             | (:max_outstanding_activities, ::Google::Protobuf::UInt32Value?) -> ::Google::Protobuf::UInt32Value?
             | [M < ::Google::Protobuf::UInt32Value::_ToProto] (:max_outstanding_activities, M?) -> M?
             | (:max_outstanding_local_activities, ::Google::Protobuf::UInt32Value?) -> ::Google::Protobuf::UInt32Value?
             | [M < ::Google::Protobuf::UInt32Value::_ToProto] (:max_outstanding_local_activities, M?) -> M?
             | (:max_concurrent_wft_polls, ::Google::Protobuf::UInt32Value?) -> ::Google::Protobuf::UInt32Value?
             | [M < ::Google::Protobuf::UInt32Value::_ToProto] (:max_concurrent_wft_polls, M?) -> M?
             | (:nonsticky_to_sticky_poll_ratio, ::Google::Protobuf::FloatValue?) -> ::Google::Protobuf::FloatValue?
             | [M < ::Google::Protobuf::FloatValue::_ToProto] (:nonsticky_to_sticky_poll_ratio, M?) -> M?
             | (:max_concurrent_at_polls, ::Google::Protobuf::UInt32Value?) -> ::Google::Protobuf::UInt32Value?
             | [M < ::Google::Protobuf::UInt32Value::_ToProto] (:max_concurrent_at_polls, M?) -> M?
             | (:no_remote_activities, bool) -> bool
             | (:sticky_queue_schedule_to_start_timeout, ::Google::Protobuf::Duration?) -> ::Google::Protobuf::Duration?
             | [M < ::Google::Protobuf::Duration::_ToProto] (:sticky_queue_schedule_to_start_timeout, M?) -> M?
             | (:max_heartbeat_throttle_interval, ::Google::Protobuf::Duration?) -> ::Google::Protobuf::Duration?
             | [M < ::Google::Protobuf::Duration::_ToProto] (:max_heartbeat_throttle_interval, M?) -> M?
             | (:default_heartbeat_throttle_interval, ::Google::Protobuf::Duration?) -> ::Google::Protobuf::Duration?
             | [M < ::Google::Protobuf::Duration::_ToProto] (:default_heartbeat_throttle_interval, M?) -> M?
             | (::Symbol, untyped) -> untyped

      def no_remote_activities?: () -> bool

      interface _ToProto
        def to_proto: () -> CreateWorkerRequest
      end

      # The type of `#initialize` parameter.
      type init = CreateWorkerRequest | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[CreateWorkerRequest, CreateWorkerRequest | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, CreateWorkerRequest, CreateWorkerRequest | _ToProto]

      type array = ::Array[CreateWorkerRequest | _ToProto]

      type hash[KEY] = ::Hash[KEY, CreateWorkerRequest | _ToProto]
    end

    class RegisterWorkerResponse < ::Protobuf::Message
      class Error < ::Protobuf::Message
        attr_accessor message(): ::String

        def message!: () -> ::String?

        def initialize: (?message: ::String) -> void

        def []: (:message) -> ::String
              | (::Symbol) -> untyped

        def []=: (:message, ::String) -> ::String
               | (::Symbol, untyped) -> untyped

        interface _ToProto
          def to_proto: () -> Error
        end

        # The type of `#initialize` parameter.
        type init = Error | _ToProto

        # The type of `repeated` field.
        type field_array = ::Protobuf::Field::FieldArray[Error, Error | _ToProto]

        # The type of `map` field.
        type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, Error, Error | _ToProto]

        type array = ::Array[Error | _ToProto]

        type hash[KEY] = ::Hash[KEY, Error | _ToProto]
      end

      attr_accessor error(): ::Temporalio::Bridge::Api::Bridge::RegisterWorkerResponse::Error?

      def error=: [M < ::Temporalio::Bridge::Api::Bridge::RegisterWorkerResponse::Error::_ToProto] (M?) -> M?
                | ...

      def error!: () -> ::Temporalio::Bridge::Api::Bridge::RegisterWorkerResponse::Error?

      def initialize: (?error: ::Temporalio::Bridge::Api::Bridge::RegisterWorkerResponse::Error::init?) -> void

      def []: (:error) -> ::Temporalio::Bridge::Api::Bridge::RegisterWorkerResponse::Error?
            | (::Symbol) -> untyped

      def []=: (:error, ::Temporalio::Bridge::Api::Bridge::RegisterWorkerResponse::Error?) -> ::Temporalio::Bridge::Api::Bridge::RegisterWorkerResponse::Error?
             | [M < ::Temporalio::Bridge::Api::Bridge::RegisterWorkerResponse::Error::_ToProto] (:error, M?) -> M?
             | (::Symbol, untyped) -> untyped

      interface _ToProto
        def to_proto: () -> RegisterWorkerResponse
      end

      # The type of `#initialize` parameter.
      type init = RegisterWorkerResponse | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[RegisterWorkerResponse, RegisterWorkerResponse | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, RegisterWorkerResponse, RegisterWorkerResponse | _ToProto]

      type array = ::Array[RegisterWorkerResponse | _ToProto]

      type hash[KEY] = ::Hash[KEY, RegisterWorkerResponse | _ToProto]
    end

    class PollWorkflowActivationRequest < ::Protobuf::Message
      def initialize: () -> void

      interface _ToProto
        def to_proto: () -> PollWorkflowActivationRequest
      end

      # The type of `#initialize` parameter.
      type init = PollWorkflowActivationRequest | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[PollWorkflowActivationRequest, PollWorkflowActivationRequest | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, PollWorkflowActivationRequest, PollWorkflowActivationRequest | _ToProto]

      type array = ::Array[PollWorkflowActivationRequest | _ToProto]

      type hash[KEY] = ::Hash[KEY, PollWorkflowActivationRequest | _ToProto]
    end

    class PollWorkflowActivationResponse < ::Protobuf::Message
      class Error < ::Protobuf::Message
        attr_accessor message(): ::String

        def message!: () -> ::String?

        attr_accessor shutdown(): bool

        def shutdown!: () -> bool?

        def initialize: (?message: ::String, ?shutdown: bool) -> void

        def []: (:message) -> ::String
              | (:shutdown) -> bool
              | (::Symbol) -> untyped

        def []=: (:message, ::String) -> ::String
               | (:shutdown, bool) -> bool
               | (::Symbol, untyped) -> untyped

        def shutdown?: () -> bool

        interface _ToProto
          def to_proto: () -> Error
        end

        # The type of `#initialize` parameter.
        type init = Error | _ToProto

        # The type of `repeated` field.
        type field_array = ::Protobuf::Field::FieldArray[Error, Error | _ToProto]

        # The type of `map` field.
        type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, Error, Error | _ToProto]

        type array = ::Array[Error | _ToProto]

        type hash[KEY] = ::Hash[KEY, Error | _ToProto]
      end

      attr_accessor activation(): ::Temporalio::Bridge::Api::WorkflowActivation::WorkflowActivation?

      def activation=: [M < ::Temporalio::Bridge::Api::WorkflowActivation::WorkflowActivation::_ToProto] (M?) -> M?
                     | ...

      def activation!: () -> ::Temporalio::Bridge::Api::WorkflowActivation::WorkflowActivation?

      attr_accessor error(): ::Temporalio::Bridge::Api::Bridge::PollWorkflowActivationResponse::Error?

      def error=: [M < ::Temporalio::Bridge::Api::Bridge::PollWorkflowActivationResponse::Error::_ToProto] (M?) -> M?
                | ...

      def error!: () -> ::Temporalio::Bridge::Api::Bridge::PollWorkflowActivationResponse::Error?

      def initialize: (?activation: ::Temporalio::Bridge::Api::WorkflowActivation::WorkflowActivation::init?, ?error: ::Temporalio::Bridge::Api::Bridge::PollWorkflowActivationResponse::Error::init?) -> void

      def []: (:activation) -> ::Temporalio::Bridge::Api::WorkflowActivation::WorkflowActivation?
            | (:error) -> ::Temporalio::Bridge::Api::Bridge::PollWorkflowActivationResponse::Error?
            | (::Symbol) -> untyped

      def []=: (:activation, ::Temporalio::Bridge::Api::WorkflowActivation::WorkflowActivation?) -> ::Temporalio::Bridge::Api::WorkflowActivation::WorkflowActivation?
             | [M < ::Temporalio::Bridge::Api::WorkflowActivation::WorkflowActivation::_ToProto] (:activation, M?) -> M?
             | (:error, ::Temporalio::Bridge::Api::Bridge::PollWorkflowActivationResponse::Error?) -> ::Temporalio::Bridge::Api::Bridge::PollWorkflowActivationResponse::Error?
             | [M < ::Temporalio::Bridge::Api::Bridge::PollWorkflowActivationResponse::Error::_ToProto] (:error, M?) -> M?
             | (::Symbol, untyped) -> untyped

      interface _ToProto
        def to_proto: () -> PollWorkflowActivationResponse
      end

      # The type of `#initialize` parameter.
      type init = PollWorkflowActivationResponse | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[PollWorkflowActivationResponse, PollWorkflowActivationResponse | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, PollWorkflowActivationResponse, PollWorkflowActivationResponse | _ToProto]

      type array = ::Array[PollWorkflowActivationResponse | _ToProto]

      type hash[KEY] = ::Hash[KEY, PollWorkflowActivationResponse | _ToProto]
    end

    class PollActivityTaskRequest < ::Protobuf::Message
      def initialize: () -> void

      interface _ToProto
        def to_proto: () -> PollActivityTaskRequest
      end

      # The type of `#initialize` parameter.
      type init = PollActivityTaskRequest | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[PollActivityTaskRequest, PollActivityTaskRequest | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, PollActivityTaskRequest, PollActivityTaskRequest | _ToProto]

      type array = ::Array[PollActivityTaskRequest | _ToProto]

      type hash[KEY] = ::Hash[KEY, PollActivityTaskRequest | _ToProto]
    end

    class PollActivityTaskResponse < ::Protobuf::Message
      class Error < ::Protobuf::Message
        attr_accessor message(): ::String

        def message!: () -> ::String?

        attr_accessor shutdown(): bool

        def shutdown!: () -> bool?

        def initialize: (?message: ::String, ?shutdown: bool) -> void

        def []: (:message) -> ::String
              | (:shutdown) -> bool
              | (::Symbol) -> untyped

        def []=: (:message, ::String) -> ::String
               | (:shutdown, bool) -> bool
               | (::Symbol, untyped) -> untyped

        def shutdown?: () -> bool

        interface _ToProto
          def to_proto: () -> Error
        end

        # The type of `#initialize` parameter.
        type init = Error | _ToProto

        # The type of `repeated` field.
        type field_array = ::Protobuf::Field::FieldArray[Error, Error | _ToProto]

        # The type of `map` field.
        type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, Error, Error | _ToProto]

        type array = ::Array[Error | _ToProto]

        type hash[KEY] = ::Hash[KEY, Error | _ToProto]
      end

      attr_accessor task(): ::Temporalio::Bridge::Api::ActivityTask::ActivityTask?

      def task=: [M < ::Temporalio::Bridge::Api::ActivityTask::ActivityTask::_ToProto] (M?) -> M?
               | ...

      def task!: () -> ::Temporalio::Bridge::Api::ActivityTask::ActivityTask?

      attr_accessor error(): ::Temporalio::Bridge::Api::Bridge::PollActivityTaskResponse::Error?

      def error=: [M < ::Temporalio::Bridge::Api::Bridge::PollActivityTaskResponse::Error::_ToProto] (M?) -> M?
                | ...

      def error!: () -> ::Temporalio::Bridge::Api::Bridge::PollActivityTaskResponse::Error?

      def initialize: (?task: ::Temporalio::Bridge::Api::ActivityTask::ActivityTask::init?, ?error: ::Temporalio::Bridge::Api::Bridge::PollActivityTaskResponse::Error::init?) -> void

      def []: (:task) -> ::Temporalio::Bridge::Api::ActivityTask::ActivityTask?
            | (:error) -> ::Temporalio::Bridge::Api::Bridge::PollActivityTaskResponse::Error?
            | (::Symbol) -> untyped

      def []=: (:task, ::Temporalio::Bridge::Api::ActivityTask::ActivityTask?) -> ::Temporalio::Bridge::Api::ActivityTask::ActivityTask?
             | [M < ::Temporalio::Bridge::Api::ActivityTask::ActivityTask::_ToProto] (:task, M?) -> M?
             | (:error, ::Temporalio::Bridge::Api::Bridge::PollActivityTaskResponse::Error?) -> ::Temporalio::Bridge::Api::Bridge::PollActivityTaskResponse::Error?
             | [M < ::Temporalio::Bridge::Api::Bridge::PollActivityTaskResponse::Error::_ToProto] (:error, M?) -> M?
             | (::Symbol, untyped) -> untyped

      interface _ToProto
        def to_proto: () -> PollActivityTaskResponse
      end

      # The type of `#initialize` parameter.
      type init = PollActivityTaskResponse | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[PollActivityTaskResponse, PollActivityTaskResponse | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, PollActivityTaskResponse, PollActivityTaskResponse | _ToProto]

      type array = ::Array[PollActivityTaskResponse | _ToProto]

      type hash[KEY] = ::Hash[KEY, PollActivityTaskResponse | _ToProto]
    end

    class CompleteWorkflowActivationRequest < ::Protobuf::Message
      attr_accessor completion(): ::Temporalio::Bridge::Api::WorkflowCompletion::WorkflowActivationCompletion?

      def completion=: [M < ::Temporalio::Bridge::Api::WorkflowCompletion::WorkflowActivationCompletion::_ToProto] (M?) -> M?
                     | ...

      def completion!: () -> ::Temporalio::Bridge::Api::WorkflowCompletion::WorkflowActivationCompletion?

      def initialize: (?completion: ::Temporalio::Bridge::Api::WorkflowCompletion::WorkflowActivationCompletion::init?) -> void

      def []: (:completion) -> ::Temporalio::Bridge::Api::WorkflowCompletion::WorkflowActivationCompletion?
            | (::Symbol) -> untyped

      def []=: (:completion, ::Temporalio::Bridge::Api::WorkflowCompletion::WorkflowActivationCompletion?) -> ::Temporalio::Bridge::Api::WorkflowCompletion::WorkflowActivationCompletion?
             | [M < ::Temporalio::Bridge::Api::WorkflowCompletion::WorkflowActivationCompletion::_ToProto] (:completion, M?) -> M?
             | (::Symbol, untyped) -> untyped

      interface _ToProto
        def to_proto: () -> CompleteWorkflowActivationRequest
      end

      # The type of `#initialize` parameter.
      type init = CompleteWorkflowActivationRequest | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[CompleteWorkflowActivationRequest, CompleteWorkflowActivationRequest | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, CompleteWorkflowActivationRequest, CompleteWorkflowActivationRequest | _ToProto]

      type array = ::Array[CompleteWorkflowActivationRequest | _ToProto]

      type hash[KEY] = ::Hash[KEY, CompleteWorkflowActivationRequest | _ToProto]
    end

    class CompleteWorkflowActivationResponse < ::Protobuf::Message
      class Error < ::Protobuf::Message
        attr_accessor message(): ::String

        def message!: () -> ::String?

        def initialize: (?message: ::String) -> void

        def []: (:message) -> ::String
              | (::Symbol) -> untyped

        def []=: (:message, ::String) -> ::String
               | (::Symbol, untyped) -> untyped

        interface _ToProto
          def to_proto: () -> Error
        end

        # The type of `#initialize` parameter.
        type init = Error | _ToProto

        # The type of `repeated` field.
        type field_array = ::Protobuf::Field::FieldArray[Error, Error | _ToProto]

        # The type of `map` field.
        type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, Error, Error | _ToProto]

        type array = ::Array[Error | _ToProto]

        type hash[KEY] = ::Hash[KEY, Error | _ToProto]
      end

      attr_accessor error(): ::Temporalio::Bridge::Api::Bridge::CompleteWorkflowActivationResponse::Error?

      def error=: [M < ::Temporalio::Bridge::Api::Bridge::CompleteWorkflowActivationResponse::Error::_ToProto] (M?) -> M?
                | ...

      def error!: () -> ::Temporalio::Bridge::Api::Bridge::CompleteWorkflowActivationResponse::Error?

      def initialize: (?error: ::Temporalio::Bridge::Api::Bridge::CompleteWorkflowActivationResponse::Error::init?) -> void

      def []: (:error) -> ::Temporalio::Bridge::Api::Bridge::CompleteWorkflowActivationResponse::Error?
            | (::Symbol) -> untyped

      def []=: (:error, ::Temporalio::Bridge::Api::Bridge::CompleteWorkflowActivationResponse::Error?) -> ::Temporalio::Bridge::Api::Bridge::CompleteWorkflowActivationResponse::Error?
             | [M < ::Temporalio::Bridge::Api::Bridge::CompleteWorkflowActivationResponse::Error::_ToProto] (:error, M?) -> M?
             | (::Symbol, untyped) -> untyped

      interface _ToProto
        def to_proto: () -> CompleteWorkflowActivationResponse
      end

      # The type of `#initialize` parameter.
      type init = CompleteWorkflowActivationResponse | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[CompleteWorkflowActivationResponse, CompleteWorkflowActivationResponse | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, CompleteWorkflowActivationResponse, CompleteWorkflowActivationResponse | _ToProto]

      type array = ::Array[CompleteWorkflowActivationResponse | _ToProto]

      type hash[KEY] = ::Hash[KEY, CompleteWorkflowActivationResponse | _ToProto]
    end

    class CompleteActivityTaskRequest < ::Protobuf::Message
      attr_accessor completion(): ::Temporalio::Bridge::Api::CoreInterface::ActivityTaskCompletion?

      def completion=: [M < ::Temporalio::Bridge::Api::CoreInterface::ActivityTaskCompletion::_ToProto] (M?) -> M?
                     | ...

      def completion!: () -> ::Temporalio::Bridge::Api::CoreInterface::ActivityTaskCompletion?

      def initialize: (?completion: ::Temporalio::Bridge::Api::CoreInterface::ActivityTaskCompletion::init?) -> void

      def []: (:completion) -> ::Temporalio::Bridge::Api::CoreInterface::ActivityTaskCompletion?
            | (::Symbol) -> untyped

      def []=: (:completion, ::Temporalio::Bridge::Api::CoreInterface::ActivityTaskCompletion?) -> ::Temporalio::Bridge::Api::CoreInterface::ActivityTaskCompletion?
             | [M < ::Temporalio::Bridge::Api::CoreInterface::ActivityTaskCompletion::_ToProto] (:completion, M?) -> M?
             | (::Symbol, untyped) -> untyped

      interface _ToProto
        def to_proto: () -> CompleteActivityTaskRequest
      end

      # The type of `#initialize` parameter.
      type init = CompleteActivityTaskRequest | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[CompleteActivityTaskRequest, CompleteActivityTaskRequest | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, CompleteActivityTaskRequest, CompleteActivityTaskRequest | _ToProto]

      type array = ::Array[CompleteActivityTaskRequest | _ToProto]

      type hash[KEY] = ::Hash[KEY, CompleteActivityTaskRequest | _ToProto]
    end

    class CompleteActivityTaskResponse < ::Protobuf::Message
      class Error < ::Protobuf::Message
        attr_accessor message(): ::String

        def message!: () -> ::String?

        def initialize: (?message: ::String) -> void

        def []: (:message) -> ::String
              | (::Symbol) -> untyped

        def []=: (:message, ::String) -> ::String
               | (::Symbol, untyped) -> untyped

        interface _ToProto
          def to_proto: () -> Error
        end

        # The type of `#initialize` parameter.
        type init = Error | _ToProto

        # The type of `repeated` field.
        type field_array = ::Protobuf::Field::FieldArray[Error, Error | _ToProto]

        # The type of `map` field.
        type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, Error, Error | _ToProto]

        type array = ::Array[Error | _ToProto]

        type hash[KEY] = ::Hash[KEY, Error | _ToProto]
      end

      attr_accessor error(): ::Temporalio::Bridge::Api::Bridge::CompleteActivityTaskResponse::Error?

      def error=: [M < ::Temporalio::Bridge::Api::Bridge::CompleteActivityTaskResponse::Error::_ToProto] (M?) -> M?
                | ...

      def error!: () -> ::Temporalio::Bridge::Api::Bridge::CompleteActivityTaskResponse::Error?

      def initialize: (?error: ::Temporalio::Bridge::Api::Bridge::CompleteActivityTaskResponse::Error::init?) -> void

      def []: (:error) -> ::Temporalio::Bridge::Api::Bridge::CompleteActivityTaskResponse::Error?
            | (::Symbol) -> untyped

      def []=: (:error, ::Temporalio::Bridge::Api::Bridge::CompleteActivityTaskResponse::Error?) -> ::Temporalio::Bridge::Api::Bridge::CompleteActivityTaskResponse::Error?
             | [M < ::Temporalio::Bridge::Api::Bridge::CompleteActivityTaskResponse::Error::_ToProto] (:error, M?) -> M?
             | (::Symbol, untyped) -> untyped

      interface _ToProto
        def to_proto: () -> CompleteActivityTaskResponse
      end

      # The type of `#initialize` parameter.
      type init = CompleteActivityTaskResponse | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[CompleteActivityTaskResponse, CompleteActivityTaskResponse | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, CompleteActivityTaskResponse, CompleteActivityTaskResponse | _ToProto]

      type array = ::Array[CompleteActivityTaskResponse | _ToProto]

      type hash[KEY] = ::Hash[KEY, CompleteActivityTaskResponse | _ToProto]
    end

    class RecordActivityHeartbeatRequest < ::Protobuf::Message
      attr_accessor heartbeat(): ::Temporalio::Bridge::Api::CoreInterface::ActivityHeartbeat?

      def heartbeat=: [M < ::Temporalio::Bridge::Api::CoreInterface::ActivityHeartbeat::_ToProto] (M?) -> M?
                    | ...

      def heartbeat!: () -> ::Temporalio::Bridge::Api::CoreInterface::ActivityHeartbeat?

      def initialize: (?heartbeat: ::Temporalio::Bridge::Api::CoreInterface::ActivityHeartbeat::init?) -> void

      def []: (:heartbeat) -> ::Temporalio::Bridge::Api::CoreInterface::ActivityHeartbeat?
            | (::Symbol) -> untyped

      def []=: (:heartbeat, ::Temporalio::Bridge::Api::CoreInterface::ActivityHeartbeat?) -> ::Temporalio::Bridge::Api::CoreInterface::ActivityHeartbeat?
             | [M < ::Temporalio::Bridge::Api::CoreInterface::ActivityHeartbeat::_ToProto] (:heartbeat, M?) -> M?
             | (::Symbol, untyped) -> untyped

      interface _ToProto
        def to_proto: () -> RecordActivityHeartbeatRequest
      end

      # The type of `#initialize` parameter.
      type init = RecordActivityHeartbeatRequest | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[RecordActivityHeartbeatRequest, RecordActivityHeartbeatRequest | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, RecordActivityHeartbeatRequest, RecordActivityHeartbeatRequest | _ToProto]

      type array = ::Array[RecordActivityHeartbeatRequest | _ToProto]

      type hash[KEY] = ::Hash[KEY, RecordActivityHeartbeatRequest | _ToProto]
    end

    class RecordActivityHeartbeatResponse < ::Protobuf::Message
      class Error < ::Protobuf::Message
        attr_accessor message(): ::String

        def message!: () -> ::String?

        def initialize: (?message: ::String) -> void

        def []: (:message) -> ::String
              | (::Symbol) -> untyped

        def []=: (:message, ::String) -> ::String
               | (::Symbol, untyped) -> untyped

        interface _ToProto
          def to_proto: () -> Error
        end

        # The type of `#initialize` parameter.
        type init = Error | _ToProto

        # The type of `repeated` field.
        type field_array = ::Protobuf::Field::FieldArray[Error, Error | _ToProto]

        # The type of `map` field.
        type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, Error, Error | _ToProto]

        type array = ::Array[Error | _ToProto]

        type hash[KEY] = ::Hash[KEY, Error | _ToProto]
      end

      attr_accessor error(): ::Temporalio::Bridge::Api::Bridge::RecordActivityHeartbeatResponse::Error?

      def error=: [M < ::Temporalio::Bridge::Api::Bridge::RecordActivityHeartbeatResponse::Error::_ToProto] (M?) -> M?
                | ...

      def error!: () -> ::Temporalio::Bridge::Api::Bridge::RecordActivityHeartbeatResponse::Error?

      def initialize: (?error: ::Temporalio::Bridge::Api::Bridge::RecordActivityHeartbeatResponse::Error::init?) -> void

      def []: (:error) -> ::Temporalio::Bridge::Api::Bridge::RecordActivityHeartbeatResponse::Error?
            | (::Symbol) -> untyped

      def []=: (:error, ::Temporalio::Bridge::Api::Bridge::RecordActivityHeartbeatResponse::Error?) -> ::Temporalio::Bridge::Api::Bridge::RecordActivityHeartbeatResponse::Error?
             | [M < ::Temporalio::Bridge::Api::Bridge::RecordActivityHeartbeatResponse::Error::_ToProto] (:error, M?) -> M?
             | (::Symbol, untyped) -> untyped

      interface _ToProto
        def to_proto: () -> RecordActivityHeartbeatResponse
      end

      # The type of `#initialize` parameter.
      type init = RecordActivityHeartbeatResponse | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[RecordActivityHeartbeatResponse, RecordActivityHeartbeatResponse | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, RecordActivityHeartbeatResponse, RecordActivityHeartbeatResponse | _ToProto]

      type array = ::Array[RecordActivityHeartbeatResponse | _ToProto]

      type hash[KEY] = ::Hash[KEY, RecordActivityHeartbeatResponse | _ToProto]
    end

    class RequestWorkflowEvictionRequest < ::Protobuf::Message
      attr_accessor run_id(): ::String

      def run_id!: () -> ::String?

      def initialize: (?run_id: ::String) -> void

      def []: (:run_id) -> ::String
            | (::Symbol) -> untyped

      def []=: (:run_id, ::String) -> ::String
             | (::Symbol, untyped) -> untyped

      interface _ToProto
        def to_proto: () -> RequestWorkflowEvictionRequest
      end

      # The type of `#initialize` parameter.
      type init = RequestWorkflowEvictionRequest | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[RequestWorkflowEvictionRequest, RequestWorkflowEvictionRequest | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, RequestWorkflowEvictionRequest, RequestWorkflowEvictionRequest | _ToProto]

      type array = ::Array[RequestWorkflowEvictionRequest | _ToProto]

      type hash[KEY] = ::Hash[KEY, RequestWorkflowEvictionRequest | _ToProto]
    end

    class RequestWorkflowEvictionResponse < ::Protobuf::Message
      class Error < ::Protobuf::Message
        attr_accessor message(): ::String

        def message!: () -> ::String?

        def initialize: (?message: ::String) -> void

        def []: (:message) -> ::String
              | (::Symbol) -> untyped

        def []=: (:message, ::String) -> ::String
               | (::Symbol, untyped) -> untyped

        interface _ToProto
          def to_proto: () -> Error
        end

        # The type of `#initialize` parameter.
        type init = Error | _ToProto

        # The type of `repeated` field.
        type field_array = ::Protobuf::Field::FieldArray[Error, Error | _ToProto]

        # The type of `map` field.
        type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, Error, Error | _ToProto]

        type array = ::Array[Error | _ToProto]

        type hash[KEY] = ::Hash[KEY, Error | _ToProto]
      end

      attr_accessor error(): ::Temporalio::Bridge::Api::Bridge::RequestWorkflowEvictionResponse::Error?

      def error=: [M < ::Temporalio::Bridge::Api::Bridge::RequestWorkflowEvictionResponse::Error::_ToProto] (M?) -> M?
                | ...

      def error!: () -> ::Temporalio::Bridge::Api::Bridge::RequestWorkflowEvictionResponse::Error?

      def initialize: (?error: ::Temporalio::Bridge::Api::Bridge::RequestWorkflowEvictionResponse::Error::init?) -> void

      def []: (:error) -> ::Temporalio::Bridge::Api::Bridge::RequestWorkflowEvictionResponse::Error?
            | (::Symbol) -> untyped

      def []=: (:error, ::Temporalio::Bridge::Api::Bridge::RequestWorkflowEvictionResponse::Error?) -> ::Temporalio::Bridge::Api::Bridge::RequestWorkflowEvictionResponse::Error?
             | [M < ::Temporalio::Bridge::Api::Bridge::RequestWorkflowEvictionResponse::Error::_ToProto] (:error, M?) -> M?
             | (::Symbol, untyped) -> untyped

      interface _ToProto
        def to_proto: () -> RequestWorkflowEvictionResponse
      end

      # The type of `#initialize` parameter.
      type init = RequestWorkflowEvictionResponse | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[RequestWorkflowEvictionResponse, RequestWorkflowEvictionResponse | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, RequestWorkflowEvictionResponse, RequestWorkflowEvictionResponse | _ToProto]

      type array = ::Array[RequestWorkflowEvictionResponse | _ToProto]

      type hash[KEY] = ::Hash[KEY, RequestWorkflowEvictionResponse | _ToProto]
    end

    class ShutdownWorkerRequest < ::Protobuf::Message
      def initialize: () -> void

      interface _ToProto
        def to_proto: () -> ShutdownWorkerRequest
      end

      # The type of `#initialize` parameter.
      type init = ShutdownWorkerRequest | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[ShutdownWorkerRequest, ShutdownWorkerRequest | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, ShutdownWorkerRequest, ShutdownWorkerRequest | _ToProto]

      type array = ::Array[ShutdownWorkerRequest | _ToProto]

      type hash[KEY] = ::Hash[KEY, ShutdownWorkerRequest | _ToProto]
    end

    class ShutdownWorkerResponse < ::Protobuf::Message
      class Error < ::Protobuf::Message
        attr_accessor message(): ::String

        def message!: () -> ::String?

        def initialize: (?message: ::String) -> void

        def []: (:message) -> ::String
              | (::Symbol) -> untyped

        def []=: (:message, ::String) -> ::String
               | (::Symbol, untyped) -> untyped

        interface _ToProto
          def to_proto: () -> Error
        end

        # The type of `#initialize` parameter.
        type init = Error | _ToProto

        # The type of `repeated` field.
        type field_array = ::Protobuf::Field::FieldArray[Error, Error | _ToProto]

        # The type of `map` field.
        type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, Error, Error | _ToProto]

        type array = ::Array[Error | _ToProto]

        type hash[KEY] = ::Hash[KEY, Error | _ToProto]
      end

      attr_accessor error(): ::Temporalio::Bridge::Api::Bridge::ShutdownWorkerResponse::Error?

      def error=: [M < ::Temporalio::Bridge::Api::Bridge::ShutdownWorkerResponse::Error::_ToProto] (M?) -> M?
                | ...

      def error!: () -> ::Temporalio::Bridge::Api::Bridge::ShutdownWorkerResponse::Error?

      def initialize: (?error: ::Temporalio::Bridge::Api::Bridge::ShutdownWorkerResponse::Error::init?) -> void

      def []: (:error) -> ::Temporalio::Bridge::Api::Bridge::ShutdownWorkerResponse::Error?
            | (::Symbol) -> untyped

      def []=: (:error, ::Temporalio::Bridge::Api::Bridge::ShutdownWorkerResponse::Error?) -> ::Temporalio::Bridge::Api::Bridge::ShutdownWorkerResponse::Error?
             | [M < ::Temporalio::Bridge::Api::Bridge::ShutdownWorkerResponse::Error::_ToProto] (:error, M?) -> M?
             | (::Symbol, untyped) -> untyped

      interface _ToProto
        def to_proto: () -> ShutdownWorkerResponse
      end

      # The type of `#initialize` parameter.
      type init = ShutdownWorkerResponse | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[ShutdownWorkerResponse, ShutdownWorkerResponse | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, ShutdownWorkerResponse, ShutdownWorkerResponse | _ToProto]

      type array = ::Array[ShutdownWorkerResponse | _ToProto]

      type hash[KEY] = ::Hash[KEY, ShutdownWorkerResponse | _ToProto]
    end

    class FetchBufferedLogsRequest < ::Protobuf::Message
      def initialize: () -> void

      interface _ToProto
        def to_proto: () -> FetchBufferedLogsRequest
      end

      # The type of `#initialize` parameter.
      type init = FetchBufferedLogsRequest | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[FetchBufferedLogsRequest, FetchBufferedLogsRequest | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, FetchBufferedLogsRequest, FetchBufferedLogsRequest | _ToProto]

      type array = ::Array[FetchBufferedLogsRequest | _ToProto]

      type hash[KEY] = ::Hash[KEY, FetchBufferedLogsRequest | _ToProto]
    end

    class FetchBufferedLogsResponse < ::Protobuf::Message
      class LogEntry < ::Protobuf::Message
        attr_accessor message(): ::String

        def message!: () -> ::String?

        attr_accessor timestamp(): ::Google::Protobuf::Timestamp?

        def timestamp=: [M < ::Google::Protobuf::Timestamp::_ToProto] (M?) -> M?
                      | ...

        def timestamp!: () -> ::Google::Protobuf::Timestamp?

        attr_accessor level(): ::Temporalio::Bridge::Api::Bridge::LogLevel

        def level=: (::Temporalio::Bridge::Api::Bridge::LogLevel::values) -> ::Temporalio::Bridge::Api::Bridge::LogLevel::values
                  | ...

        def level!: () -> ::Temporalio::Bridge::Api::Bridge::LogLevel?

        def initialize: (?message: ::String, ?timestamp: ::Google::Protobuf::Timestamp::init?, ?level: ::Temporalio::Bridge::Api::Bridge::LogLevel::init) -> void

        def []: (:message) -> ::String
              | (:timestamp) -> ::Google::Protobuf::Timestamp?
              | (:level) -> ::Temporalio::Bridge::Api::Bridge::LogLevel
              | (::Symbol) -> untyped

        def []=: (:message, ::String) -> ::String
               | (:timestamp, ::Google::Protobuf::Timestamp?) -> ::Google::Protobuf::Timestamp?
               | [M < ::Google::Protobuf::Timestamp::_ToProto] (:timestamp, M?) -> M?
               | (:level, ::Temporalio::Bridge::Api::Bridge::LogLevel) -> ::Temporalio::Bridge::Api::Bridge::LogLevel
               | (:level, ::Temporalio::Bridge::Api::Bridge::LogLevel::values) -> ::Temporalio::Bridge::Api::Bridge::LogLevel::values
               | (::Symbol, untyped) -> untyped

        interface _ToProto
          def to_proto: () -> LogEntry
        end

        # The type of `#initialize` parameter.
        type init = LogEntry | _ToProto

        # The type of `repeated` field.
        type field_array = ::Protobuf::Field::FieldArray[LogEntry, LogEntry | _ToProto]

        # The type of `map` field.
        type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, LogEntry, LogEntry | _ToProto]

        type array = ::Array[LogEntry | _ToProto]

        type hash[KEY] = ::Hash[KEY, LogEntry | _ToProto]
      end

      attr_accessor entries(): ::Temporalio::Bridge::Api::Bridge::FetchBufferedLogsResponse::LogEntry::field_array

      def entries=: (::Temporalio::Bridge::Api::Bridge::FetchBufferedLogsResponse::LogEntry::array) -> ::Temporalio::Bridge::Api::Bridge::FetchBufferedLogsResponse::LogEntry::array
                  | ...

      def entries!: () -> ::Temporalio::Bridge::Api::Bridge::FetchBufferedLogsResponse::LogEntry::field_array?

      def initialize: (?entries: ::Temporalio::Bridge::Api::Bridge::FetchBufferedLogsResponse::LogEntry::array) -> void

      def []: (:entries) -> ::Temporalio::Bridge::Api::Bridge::FetchBufferedLogsResponse::LogEntry::field_array
            | (::Symbol) -> untyped

      def []=: (:entries, ::Temporalio::Bridge::Api::Bridge::FetchBufferedLogsResponse::LogEntry::field_array) -> ::Temporalio::Bridge::Api::Bridge::FetchBufferedLogsResponse::LogEntry::field_array
             | (:entries, ::Temporalio::Bridge::Api::Bridge::FetchBufferedLogsResponse::LogEntry::array) -> ::Temporalio::Bridge::Api::Bridge::FetchBufferedLogsResponse::LogEntry::array
             | (::Symbol, untyped) -> untyped

      interface _ToProto
        def to_proto: () -> FetchBufferedLogsResponse
      end

      # The type of `#initialize` parameter.
      type init = FetchBufferedLogsResponse | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[FetchBufferedLogsResponse, FetchBufferedLogsResponse | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, FetchBufferedLogsResponse, FetchBufferedLogsResponse | _ToProto]

      type array = ::Array[FetchBufferedLogsResponse | _ToProto]

      type hash[KEY] = ::Hash[KEY, FetchBufferedLogsResponse | _ToProto]
    end
  end
end
