module Temporalio
  module Workflow
    class ExternalWorkflowHandle
      def id: -> String
      def run_id: -> String?

      def signal: (
        Workflow::Definition::Signal | Symbol | String signal,
        *Object? args,
        ?cancellation: Cancellation,
        ?arg_hints: Array[Object]?
      ) -> void

      def cancel: -> void
    end
  end
end