module Temporalio
  class Connection
    attr_reader core_connection: Temporalio::Bridge::Connection

    def initialize: (
      ?String? address,
      ?tls: TlsOptions?,
      ?metadata: Hash[String, String]?,
      ?retry_config: RetryConfig?,
    ) -> void
    def workflow_service: -> Temporalio::Connection::WorkflowService
    def test_service: -> Temporalio::Connection::TestService

    private

    @workflow_service: Temporalio::Connection::WorkflowService?
    @test_service: Temporalio::Connection::TestService?

    def parse_url: (String?) -> [String, Integer]
  end
end
