module Temporalio
  module RetryState
    type values =
      :IN_PROGRESS | :NON_RETRYABLE_FAILURE | :TIMEOUT | :MAXIMUM_ATTEMPTS_REACHED |
      :RETRY_POLICY_NOT_SET | :INTERNAL_SERVER_ERROR | :CANCEL_REQUESTED

    IN_PROGRESS: :IN_PROGRESS
    NON_RETRYABLE_FAILURE: :NON_RETRYABLE_FAILURE
    TIMEOUT: :TIMEOUT
    MAXIMUM_ATTEMPTS_REACHED: :MAXIMUM_ATTEMPTS_REACHED
    RETRY_POLICY_NOT_SET: :RETRY_POLICY_NOT_SET
    INTERNAL_SERVER_ERROR: :INTERNAL_SERVER_ERROR
    CANCEL_REQUESTED: :CANCEL_REQUESTED
    STATES: Array[values]
    API_MAP: Hash[Temporalio::Api::Enums::V1::RetryState::init, values]

    def self.to_raw: (values) -> Temporalio::Api::Enums::V1::RetryState::init
    def self.from_raw: (Temporalio::Api::Enums::V1::RetryState::init) -> values
  end
end
