module Temporalio
  module Testing
    DEFAULT_NAMESPACE: String

    def self.start_local_environment: (
      ?namespace: String,
      ?ip: String,
      ?port: Integer?,
      ?download_dir: String?,
      ?ui: bool,
      ?temporalite_existing_path: String?,
      ?temporalite_database_filename: String?,
      ?temporalite_log_format: String,
      ?temporalite_log_level: String,
      ?temporalite_download_version: String,
      ?temporalite_extra_args: Array[String]
    ) { (Temporalio::Testing::WorkflowEnvironment) -> untyped } -> (Temporalio::Testing::WorkflowEnvironment | untyped)

    def self.start_time_skipping_environment: (
      ?port: Integer?,
      ?download_dir: String?,
      ?test_server_existing_path: String?,
      ?test_server_download_version: String,
      ?test_server_extra_args: Array[String]
    ) { (Temporalio::Testing::WorkflowEnvironment) -> untyped } -> (Temporalio::Testing::WorkflowEnvironment | untyped)

    private

    def self.init_workflow_environment_for: (Temporalio::Bridge::TestServer server, String namespace) -> WorkflowEnvironment
    def self.run_server: (
      Temporalio::Bridge::TestServer server,
      Temporalio::Testing::WorkflowEnvironment env
    ) { (Temporalio::Testing::WorkflowEnvironment) -> untyped } -> void
  end
end
