inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - ext/**/*
    - lib/temporalio/api/**/*
    - lib/temporalio/internal/bridge/api/**/*
    - target/**/*
    - tmp/**/*
    - vendor/**/*

# Keep cop rule settings in alphabetical order. For each rule setting, provide
# justification for the change from default.

# We want our classes in a certain order
Layout/ClassStructure:
  Enabled: true

# RBS annotations allowed
Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

# Don't need super for activities
Lint/MissingSuper:
  AllowedParentClasses:
    - Temporalio::Activity::Definition
    - Temporalio::Workflow::Definition

# Allow tests to nest methods
Lint/NestedMethodDefinition:
  Exclude:
    - test/**/*

# The default is too small and triggers simply setting lots of values on a proto
Metrics/AbcSize:
  Max: 200

# The default is too small
Metrics/BlockLength:
  Max: 100

# The default is too small
Metrics/ClassLength:
  Max: 1000

# The default is too small
Metrics/CyclomaticComplexity:
  Max: 100

# The default is too small
Metrics/MethodLength:
  Max: 100

# The default is too small
Metrics/ModuleLength:
  Max: 1000

# The default is too small
Metrics/PerceivedComplexity:
  Max: 40

# We want the `*args` syntax instead of `*` so we can document clearly in YARD
Style/ArgumentsForwarding:
  UseAnonymousForwarding: false

# We want classes to be documented
Style/Documentation:
  Enabled: true
  Exclude:
    - lib/temporalio/internal/**/*

# We want methods to be documented
Style/DocumentationMethod:
  Enabled: true
  Exclude:
    - lib/temporalio/internal/**/*

# Ok to have global vars in tests
Style/GlobalVars:
  Exclude:
    - test/**/*

# We're ok with two compound comparisons before doing Array.include?
Style/MultipleComparison:
  ComparisonsThreshold: 3

# We want our require lists to be in order
Style/RequireOrder:
  Enabled: true

# We are ok with large amount of keyword args
Metrics/ParameterLists:
  CountKeywordArgs: false