# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

group :development do
  gem 'activemodel'
  gem 'activerecord'
  gem 'async'
  gem 'base64'
  gem 'grpc', '~> 1.69'
  gem 'grpc-tools', '~> 1.69'
  gem 'minitest'
  # Have to explicitly depend on openssl for macos issue in GH CI described at
  # https://github.com/rails/rails/issues/55886 until 3.4.8 is released
  gem 'openssl' if RUBY_PLATFORM.include?('darwin')
  # We are intentionally not pinning OTel versions here so that CI tests the latest. This also means that the OTel
  # contrib library also does not require specific versions, we are relying on the compatibility rigor of OTel.
  gem 'opentelemetry-api'
  gem 'opentelemetry-sdk'
  gem 'rake'
  gem 'rake-compiler'
  gem 'rbs', '~> 3.5.3'
  gem 'rb_sys', '~> 0.9.63'
  gem 'rubocop'
  gem 'sqlite3'
  gem 'steep', '~> 1.7.1'
  gem 'yard'
end
