# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

group :development do
  gem 'activemodel'
  gem 'activerecord'
  gem 'async'
  gem 'base64'
  gem 'googleapis-common-protos-types'
  gem 'grpc-tools', '~> 1.69'
  gem 'irb'
  gem 'minitest'
  # Have to explicitly depend on openssl for macos issue in GH CI described at
  # https://github.com/rails/rails/issues/55886 until 3.4.8 is released
  gem 'openssl' if RUBY_PLATFORM.include?('darwin')
  # We are intentionally not pinning OTel versions here so that CI tests the latest. This also means that the OTel
  # contrib library also does not require specific versions, we are relying on the compatibility rigor of OTel.
  gem 'opentelemetry-api'
  gem 'opentelemetry-sdk'
  gem 'rake'
  gem 'rake-compiler'
  gem 'rbs', '~> 3.10'
  gem 'rb_sys', '~> 0.9'
  gem 'rdoc'
  # TODO: Unpin when https://github.com/rubocop/rubocop/pull/14838 is released
  gem 'rubocop', '1.84.0'
  gem 'sqlite3'
  gem 'steep', '~> 1.10'
  gem 'yard'
end
