# frozen_string_literal: true

# rubocop:disable Lint/MissingCopEnableDirective, Style/DocumentationMethod

require 'bundler/gem_tasks'
require 'rb_sys/cargo/metadata'
require 'rb_sys/extensiontask'

task build: :compile

GEMSPEC = Gem::Specification.load('temporalio.gemspec')

begin
  RbSys::ExtensionTask.new('temporalio_bridge', GEMSPEC) do |ext|
    ext.lib_dir = 'lib/temporalio/internal/bridge'
  end
rescue RbSys::CargoMetadataError
  raise 'Source gem cannot be installed directly, must be a supported platform'
end

require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.warning = false
  t.libs << 'test'
  t.libs << 'lib'
  t.test_files = FileList['test/**/*_test.rb', 'extra/release/test/**/*_test.rb']
end

namespace :test do
  desc 'List tests excluded from Temporal Cloud by reason'
  task :cloud_inventory do
    ENV['TESTOPTS'] = [
      ENV.fetch('TESTOPTS', nil),
      '--cloud-inventory',
      '--name=/CloudTestInventoryTest#test_report/'
    ].compact.join(' ')
    Rake::Task[:test].invoke
  end

  desc 'Run tests eligible for Temporal Cloud using envconfig'
  task :cloud do
    ENV['TEMPORAL_TEST_ENV_CONFIG_SERVER'] = '1'
    ENV['TESTOPTS'] = [ENV.fetch('TESTOPTS', nil), '--cloud'].compact.join(' ')
    Rake::Task[:test].invoke
  end
end

require 'rubocop/rake_task'

RuboCop::RakeTask.new

require 'steep/rake_task'

Steep::RakeTask.new

require 'yard'

module CustomizeYardWarnings # rubocop:disable Style/Documentation
  def process
    super
  rescue YARD::Parser::UndocumentableError
    # We ignore if it's an API warning
    last_file = statement.last.file
    raise unless (last_file.start_with?('lib/temporalio/api/') && last_file.count('/') > 3) ||
                 last_file.start_with?('lib/temporalio/internal/bridge/api/')
  end
end

YARD::Handlers::Ruby::ConstantHandler.prepend(CustomizeYardWarnings)

YARD::Rake::YardocTask.new { |t| t.options = ['--fail-on-warning'] }

Rake::Task[:yard].enhance([:copy_parent_files]) do
  rm ['LICENSE', 'README.md']
end

namespace :proto do
  desc 'Generate API and Core protobufs'
  task :generate do
    require_relative 'extra/proto_gen'
    ProtoGen.new.run
  end

  desc 'Fail if checked-in generated proto files are out of date'
  task check_generated: :generate do
    require_relative 'extra/proto_gen'
    proto_generated_paths = ProtoGen.generated_paths

    changed_paths = IO.popen(['git', 'status', '--porcelain', '--', *proto_generated_paths], &:read)
    next if changed_paths.empty?

    sh 'git', 'diff', '--', *proto_generated_paths
    raise 'Protos changed'
  end
end

namespace :rbs do
  desc 'RBS tasks'
  task :install_collection do
    sh 'rbs collection install'
  end
end

# We have to copy some parent files to this dir for gem
task :copy_parent_files do
  cp '../LICENSE', 'LICENSE'
  cp '../README.md', 'README.md'
end
Rake::Task[:build].enhance([:copy_parent_files]) do
  rm ['LICENSE', 'README.md']
end

task :rust_lint do
  sh 'cargo', 'clippy', '-p', 'temporalio_bridge', '--no-deps', '--', '-Dwarnings'
  sh 'cargo', 'fmt', '--check'
end

namespace :changelog do
  desc 'Validate pending changelog fragments'
  task :check do
    require_relative 'extra/release/scripts/changelog'
    Changelog.run('check')
  end

  desc 'Generate release notes (VERSION required; optional FROM and OUTPUT)'
  task :release_notes do
    require_relative 'extra/release/scripts/changelog'
    args = ['release-notes', '--submodule', Changelog::CORE_PATH, '--version', ENV.fetch('VERSION')]
    args.push('--from', ENV.fetch('FROM')) if ENV.key?('FROM')
    args.push('--output', ENV.fetch('OUTPUT')) if ENV.key?('OUTPUT')
    Changelog.run(*args)
  end
end

namespace :core do
  desc 'Update Core and import its changelog fragments (optional REVISION)'
  task :update do
    require_relative 'extra/release/scripts/changelog'
    args = ['update-core', '--submodule', Changelog::CORE_PATH]
    args.push('--revision', ENV.fetch('REVISION')) if ENV.key?('REVISION')
    Changelog.run(*args)
    sh 'cargo', 'fetch'
  end
end

task default: ['rubocop', 'yard', 'rbs:install_collection', 'steep', 'rust_lint', 'compile', 'test']
