# frozen_string_literal: true

D = Steep::Diagnostic

common_diagnostics = {
  # Steep >= 1.9 started becoming too noisy in these cases
  D::Ruby::UnannotatedEmptyCollection => :information,
  D::Ruby::UndeclaredMethodDefinition => :information
}

target :lib do
  signature 'sig'
  check 'lib'
  ignore 'lib/protoc-gen-openapiv2'
  library 'uri', 'objspace', 'etc'
  configure_code_diagnostics do |hash|
    hash.update(common_diagnostics)
  end
end

target :test do
  signature 'sig', 'test/sig'
  check 'test'
  library 'uri', 'objspace', 'etc'
  configure_code_diagnostics do |hash|
    hash.update(common_diagnostics)
    hash[D::Ruby::UnknownConstant] = :information
    # Steep cannot infer some things, so we can ignore them in tests
    hash[D::Ruby::InsufficientKeywordArguments] = :information
  end
end
