# frozen_string_literal: true

D = Steep::Diagnostic

target :lib do
  signature 'sig', 'test/sig'

  check 'lib', 'test'

  ignore 'lib/temporalio/api', 'lib/temporalio/internal/bridge/api'

  library 'uri', 'objspace'

  configure_code_diagnostics do |hash|
    # TODO(cretz): Fix as more protos are generated
    hash[D::Ruby::UnknownConstant] = :information
  end
end
