module Google
  module Protobuf
    # A generic empty message that you can re-use to avoid defining duplicated
    #  empty messages in your APIs. A typical example is to use it as the request
    #  or the response type of an API method. For instance:
    #
    #      service Foo {
    #        rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);
    #      }
    #
    class Empty < ::Protobuf::Message
      # Encode the message to a binary string
      # 
      def self.encode: (Empty) -> String

      def initialize: () -> void

      interface _ToProto
        def to_proto: () -> Empty
      end

      # The type of `#initialize` parameter.
      type init = Empty | _ToProto

      # The type of `repeated` field.
      type field_array = ::Protobuf::Field::FieldArray[Empty, Empty | _ToProto]

      # The type of `map` field.
      type field_hash[KEY] = ::Protobuf::Field::FieldHash[KEY, Empty, Empty | _ToProto]

      type array = ::Array[Empty | _ToProto]

      type hash[KEY] = ::Hash[KEY, Empty | _ToProto]
    end
  end
end
