name: Continuous Integration
on:
  push:
    branches:
      - main
      - "releases/*"

permissions:
  contents: read

jobs:
  build-lint-test:
    strategy:
      fail-fast: false
      matrix:
        # TODO(cretz): Enable ubuntu-24.04-arm when setup-ruby-and-rust supports it, see
        # https://github.com/oxidize-rb/actions/issues/53
        # 
        # TODO(cretz): Enable x64-mingw-ucrt if we can figure out Windows issue, see
        # https://github.com/temporalio/sdk-ruby/issues/172
        os: [ubuntu-latest, macos-latest]
        # Earliest and latest supported
        rubyVersion: ["3.3", "4.0"]
        
        include:
          - os: ubuntu-latest
            rubyVersion: "4.0"
            checkTarget: true
            docsTarget: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: recursive

      - name: Read protoc version
        shell: bash
        run: echo "PROTOC_VERSION=$(tr -d '\n' < .protoc-version)" >> "$GITHUB_ENV"

      # This is a temporary fix until Ruby 3.4.8 comes out.
      #
      # Per https://github.com/ruby/openssl/issues/949 (by way of
      # https://github.com/rails/rails/issues/55886), newer Ruby + OpenSSL has an
      # issue on macOS. This works around it until next Ruby release.
      - name: Fixate OpenSSL (macos + 3.4 only)
        if: ${{ matrix.os == 'macos-latest' && matrix.rubyVersion == '3.4' }}
        shell: bash
        run: echo "RUBY_CONFIGURE_OPTS=--with-openssl-dir=$(brew --prefix openssl@3.5)" >> "$GITHUB_ENV"

      - name: Setup Ruby and Rust
        uses: oxidize-rb/actions/setup-ruby-and-rust@e5f9a49a7812a078584072f6e3f657ad247c8771 # v1
        with:
          ruby-version: ${{ matrix.rubyVersion }}
          bundler-cache: true
          cargo-cache: true
          working-directory: ./temporalio

      # Needed for tests currently
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: stable

      - name: Install protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3
        with:
          version: ${{ env.PROTOC_VERSION }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install bundle
        working-directory: ./temporalio
        run: bundle install

      - name: Check generated protos
        if: ${{ matrix.checkTarget }}
        working-directory: ./temporalio
        run: |
          bundle exec rake proto:check_generated

      - name: Lint, compile, test Ruby
        working-directory: ./temporalio
        # Timeout just in case there's a hanging part in rake
        timeout-minutes: 20
        # Set env vars for cloud tests. If secrets aren't present, tests will be skipped.
        env:
          # For mTLS tests
          TEMPORAL_CLOUD_MTLS_TEST_TARGET_HOST: ${{ vars.TEMPORAL_CLIENT_NAMESPACE }}.tmprl.cloud:7233
          TEMPORAL_CLOUD_MTLS_TEST_NAMESPACE: ${{ vars.TEMPORAL_CLIENT_NAMESPACE }}
          TEMPORAL_CLOUD_MTLS_TEST_CLIENT_CERT: ${{ secrets.TEMPORAL_CLIENT_CERT }}
          TEMPORAL_CLOUD_MTLS_TEST_CLIENT_KEY: ${{ secrets.TEMPORAL_CLIENT_KEY }}

          # For API key tests
          TEMPORAL_CLOUD_API_KEY_TEST_TARGET_HOST: us-east-1.aws.api.temporal.io:7233
          TEMPORAL_CLOUD_API_KEY_TEST_NAMESPACE: ${{ vars.TEMPORAL_CLIENT_NAMESPACE }}
          TEMPORAL_CLOUD_API_KEY_TEST_API_KEY: ${{ secrets.TEMPORAL_CLIENT_CLOUD_API_KEY }}

          # For cloud ops tests
          TEMPORAL_CLOUD_OPS_TEST_TARGET_HOST: saas-api.tmprl.cloud:443
          TEMPORAL_CLOUD_OPS_TEST_NAMESPACE: ${{ vars.TEMPORAL_CLIENT_NAMESPACE }}
          TEMPORAL_CLOUD_OPS_TEST_API_KEY: ${{ secrets.TEMPORAL_CLIENT_CLOUD_API_KEY }}
          TEMPORAL_CLOUD_OPS_TEST_API_VERSION: 2024-05-13-00

        run: bundle exec rake TESTOPTS="--verbose"

      - name: Deploy docs
        # Only deploy on main merge, not in PRs
        if: ${{ github.ref == 'refs/heads/main' && matrix.docsTarget }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: npx vercel deploy temporalio/doc --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
